ansible-collections/community.vmware

- requirements.txt
Add the `requirements.txt` and `test-requirements.txt` files. They will
allow anyone to quickly pull the correct dependencies with the following
command:
pip -rrequirements.txt
Depends-on: https://github.com/ansible/ansible-zuul-jobs/pull/366
> add the requirements.txt file

- plugins/modules/vmware_vm_info.py
Shows the datacenter name and folder path for each VM found.
vmware_vm_info
> Add datacenter and folder info to module vmware_vm_info

- plugins/modules/vmware_cluster.py
Fixes #43
vmware_cluster
Document alternatives for deprecated parameters.
> vmware_cluster: Improve documentation for deprecated parameters

- changelogs/fragments/performance_fix_vmware_inventory.yml
- plugins/inventory/vmware_vm_inventory.py
- tests/integration/targets/inventory_vmware_vm_inventory/aliases
- tests/integration/targets/inventory_vmware_vm_inventory/test_vmware_vm_inventory.yml
Fixes: #56786
changelogs/fragments/performance_fix_vmware_inventory.yml
tests/integration/targets/inventory_vmware_vm_inventory/aliases
tests/integration/targets/inventory_vmware_vm_inventory/test_vmware_vm_inventory.yml
> VMware: vmware_vm_inventory performance improvement

- changelogs/fragments/56-vmware_rest.yml
- plugins/module_utils/vmware_rest_client.py
Handle exceptions raised in connect_to_vsphere_client API
> Handle SSL exception raise in vmware_rest_client

- test-requirements.txt
- tests/integration/targets/vmware_vm_inventory/aliases
- tests/integration/targets/vmware_vm_inventory/ansible.cfg
- tests/integration/targets/vmware_vm_inventory/prepare_environment.yml
- tests/integration/targets/vmware_vm_inventory/runme.sh
- tests/integration/targets/vmware_vm_inventory/test_inventory.yml
Run the inventory plugin in Zuul CI against real lab.
> functional test for inventory

- tests/integration/targets/inventory_vmware_vm_inventory/runme.sh
tests/integration/targets/inventory_vmware_vm_inventory/runme.sh
> vmware_vm_inventory: Test fix

- .gitignore
- plugins/module_utils/vmware_rest_client.py
- plugins/modules/vmware_datacenter_info.py
- tests/integration/targets/vmware_datacenter_info/aliases
- tests/integration/targets/vmware_datacenter_info/tasks/main.yml
Fixes: https://github.com/ansible-collections/vmware/issues/19
plugins/modules/vmware_datacenter_info.py
tests/integration/targets/vmware_datacenter_info/aliases
tests/integration/targets/vmware_datacenter_info/tasks/main.yml
> VMware: Add new module : vmware_datacenter_info

- plugins/modules/vmware_guest_network.py
Depends-On: https://github.com/ansible-collections/vmware/pull/86
Since vCenter 7.0.0, we cannot pass more than one device in `deviceChange`.
> vmware_guest_network: one device at a time

- tests/integration/targets/prepare_vmware_tests/tasks/init_real_lab.yml
- tests/integration/targets/vmware_category/aliases
- tests/integration/targets/vmware_cluster_facts/tasks/main.yml
- tests/integration/targets/vmware_cluster_info/tasks/main.yml
- tests/integration/targets/vmware_tag/aliases
- tests/integration/targets/vmware_tag_info/aliases
- tests/integration/targets/vmware_tag_manager/aliases
tests/integration/targets/prepare_vmware_tests/tasks/init_real_lab.yml
tests/integration/targets/vmware_category/aliases
tests/integration/targets/vmware_cluster_facts/tasks/main.yml
tests/integration/targets/vmware_cluster_info/tasks/main.yml
tests/integration/targets/vmware_tag/aliases
tests/integration/targets/vmware_tag_info/aliases
tests/integration/targets/vmware_tag_manager/aliases
> Temporarily disable Tag and Category tests

- changelogs/fragments/129_vmware_vm_inventory.yml
- plugins/inventory/vmware_vm_inventory.py
- tests/integration/targets/inventory_vmware_vm_inventory/ansible.cfg
- tests/integration/targets/inventory_vmware_vm_inventory/playbook/build_inventory.yml
- tests/integration/targets/inventory_vmware_vm_inventory/playbook/build_inventory_with_cache.yml
- tests/integration/targets/inventory_vmware_vm_inventory/playbook/build_inventory_without_cache.yml
- tests/integration/targets/inventory_vmware_vm_inventory/playbook/install_dependencies.yml
- tests/integration/targets/inventory_vmware_vm_inventory/playbook/prepare_vmware.yml
- tests/integration/targets/inventory_vmware_vm_inventory/playbook/test_inventory_cache.yml
- tests/integration/targets/inventory_vmware_vm_inventory/playbook/test_options.yml
- tests/integration/targets/inventory_vmware_vm_inventory/playbook/test_vmware_vm_inventory.yml
- tests/integration/targets/inventory_vmware_vm_inventory/runme.sh
- tests/integration/targets/vmware_vm_inventory/prepare_environment.yml
- tests/integration/targets/vmware_vm_inventory/test_inventory.yml
This is a part of several PRs, which incrementally adds inventory plugin enhancement based upon ansible-collections/vmware#80
> Inventory plugin enhancement - Part I

- changelogs/fragments/46-Vcenter-infra-profile-config-operations.yml
- plugins/modules/vmware_vc_infraprofile_info.py
- tests/integration/targets/vmware_vc_infraprofile_info/aliases
- tests/integration/targets/vmware_vc_infraprofile_info/tasks/main.yml
vmware_vc_infraprofile
new code module for new feature for operations of VCenter infra profile config.
> New module for Vcenter infra profile config operations

- changelogs/fragments/109-vmware_host_logbundle.yml
- plugins/modules/vmware_host_logbundle.py
- tests/integration/targets/vmware_host_logbundle/aliases
- tests/integration/targets/vmware_host_logbundle/tasks/main.yml
Depends-On: https://github.com/ansible-collections/vmware/pull/122
This PR adds a module that fetches logbundle from ESXi.
For example, if useful when fetch logbundle from multiple ESXi.
**example playbook**
```yaml
---
- name: example playbook
hosts: all
gather_facts: no
collections:
- community.vmware
tasks:
- name: test
vmware_host_logbundle:
validate_certs: no
esxi_hostname: "{{ inventory_hostname }}"
dest: "{{ save_path }}"
```
**eample inventory**
```
[all]
esxi-08.local vcenter_hostname=vcenter04.local save_path=./esxi-08.local.tgz
esxi-13.local vcenter_hostname=vcenter10.local save_path=./esxi-13.local.tgz
esxi-test-01.local …
```
> VMware: add new vmware module vmware_host_logbundle

- galaxy.yml
- plugins/modules/vmware_content_deploy_ovf_template.py
- plugins/modules/vmware_export_ovf.py
- plugins/modules/vmware_guest.py
- plugins/modules/vmware_guest_network.py
- plugins/modules/vmware_guest_tools_upgrade.py
- remove `license` key from `galaxy.yml`
- adjust the DOCUMENTATION sections of the following modules:
- vmware_content_deploy_ovf_template
- vmware_export_ovf
- vmware_guest
- vmware_guest_network
- vmware_guest_tools_upgrade
> galaxy: ensure the import works

- README.md
- changelogs/fragments/154_update_doc.yml
Depends-On: https://github.com/ansible-collections/vmware/pull/194
Update documentation for required Python library installation.
Fixes: #154
README.md
changelogs/fragments/154_update_doc.yml
> Update README for requirements

- tests/integration/targets/vcenter_extension_info/aliases
- tests/integration/targets/vcenter_extension_info/meta/main.yml
- tests/integration/targets/vcenter_extension_info/tasks/main.yml
Add a simple functional test for `vcenter_extension_info`.
> add functional test for vcenter_extension_info

- plugins/modules/vmware_host_facts.py
Fail module when gathering facts from ESXi hostsystem.
plugins/modules/vmware_host_facts.py
> Follow fix for vmware_host_facts

- meta/runtime.yml
> Add requires_ansible version constraints to runtime.yml

- CHANGELOG.rst
- changelogs/changelog.yaml
Depends-On: https://github.com/ansible-collections/vmware/pull/254
Depends-On: https://github.com/ansible-collections/vmware/pull/253
Depends-On: https://github.com/ansible-collections/vmware/pull/255
> import changelog for 1.0.0 release

- plugins/doc_fragments/vmware.py
- plugins/module_utils/vca.py
- scripts/inventory/vmware.py
- scripts/inventory/vmware_inventory.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/563
Add import boilerplate to pass the two following tests:
- future-import-boilerplate
- future-import-boilerplate
> sanity: add import boilerplate

- plugins/modules/vmware_guest_network.py
- plugins/modules/vmware_guest_vnc.py
- plugins/modules/vmware_tag_manager.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/563
We can now pass `pep8` check again.
> sanity: address some pep8 error

- changelogs/fragments/243_vmware_guest_snapshot_info.yml
- plugins/modules/vmware_guest_snapshot_info.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/563
Fixes #243 
vmware_guest_snapshot_info
> vmware_guest_snapshot_info: document that folder is a required parameter if you use VM name

- changelogs/fragments/275_vmware_vcenter_settings_info.yml
- plugins/modules/vmware_vcenter_settings_info.py
- tests/integration/targets/vmware_vcenter_settings_info/aliases
- tests/integration/targets/vmware_vcenter_settings_info/tasks/main.yml
This PR adds a module that gather information vCenter settings.
fixes: https://github.com/ansible-collections/vmware/issues/170
vmware_vcenter_settings_info
tested with vCenter 6.7
> VMware: Add new module vmware_vcenter_settings_info 

- changelogs/fragments/vmware_vm_storage_policy_module.yml
- meta/runtime.yml
- plugins/modules/vmware_vm_storage_policy.py
- tests/integration/targets/vmware_vm_storage_policy/aliases
- tests/integration/targets/vmware_vm_storage_policy/tasks/main.yml
Fixes #236 , Added support for storage policy creation based on pre-existing tags.  Does not support VSAN storage policies at this time, but could eventually be configured to do so.
vmware_vm_storage_policy
Sample add playbook:
```yaml
---
- hosts: all
connection: local
tasks:
- name: "create storage policy"
community.vmware.vmware_vm_storage_policy:
hostname:        "vcenter.example.com"
username:        "svc.kubernetes"
password:        "Testing"
validate_certs:  false
tag_name:        'test'
tag_category:    'test'
name:            'test'
description:     'test'
state:           "present"
```
```text
TASK [create storage policy] **************************************************************************************
task path: …
```
> Feature add vmware vm storage policy

- plugins/modules/vsphere_copy.py
- tests/sanity/ignore-2.10.txt
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/593
* vsphere_copy
plugins/modules/vsphere_copy.py
> sanity: Doc fixes

- tests/integration/targets/vmware_cluster_facts/tasks/main.yml
- tests/integration/targets/vmware_cluster_info/tasks/main.yml
The test currently triggers too to much job failure.
See: https://github.com/ansible-collections/vmware/issues/301
> test: disable cluster tagging test

- changelogs/fragments/274_vmware_guest.yml
- plugins/modules/vmware_guest.py
Depends-On: https://github.com/ansible-collections/vmware/pull/302
Fixes #274 
vmware_guest
```paste below
```
> vmware_guest: convert cdrom controller_number and unit_number parameters to integer firstly

- plugins/modules/vmware_vmkernel.py
- tests/sanity/ignore-2.10.txt
plugins/modules/vmware_vmkernel.py
> sanity: Doc fixes for vmware_vmkernel

- plugins/modules/vmware_vcenter_settings.py
- tests/sanity/ignore-2.10.txt
plugins/modules/vmware_vcenter_settings.py
> Sanity: Doc fixes for vmware_vcenter_settings

- plugins/modules/vmware_vcenter_statistics.py
- tests/sanity/ignore-2.10.txt
plugins/modules/vmware_vcenter_statistics.py
> sanity: Doc fixes for vmware_vcenter_statistics

- changelogs/fragments/vmware_pg_options.yml
- plugins/modules/vmware_portgroup.py
- tests/sanity/ignore-2.10.txt
changelogs/fragments/vmware_pg_options.yml
plugins/modules/vmware_portgroup.py
> sanity: Doc fixes for vmware_portgroup

- plugins/modules/vmware_guest_disk.py
- tests/integration/targets/vmware_guest_disk/tasks/main.yml
Depends-On: https://github.com/ansible-collections/vmware/pull/250
Rebase of https://github.com/ansible-collections/vmware/pull/37.
>  Reset disk['destroy'] to False when user set not remove disk file explicitly #37 

- plugins/modules/vmware_local_role_manager.py
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.9.txt
plugins/modules/vmware_local_role_manager.py
tests/sanity/ignore-2.9.txt
> sanity: Doc fixes for vmware_local_role_manager

- plugins/modules/vmware_guest.py
- tests/sanity/ignore-2.10.txt
> sanity: Doc fixes for vmware_guest

- tests/integration/targets/vmware_vmkernel_ip_config/aliases
- tests/integration/targets/vmware_vmkernel_ip_config/tasks/main.yml
This PR is to add an integration test for the vmware_vmkernel_ip_config module.
vmware_vmkernel_ip_config
tested with vCenter/ESXi 7.0
> add an integration test for vmware_vmkernel_ip_config module

- changelogs/fragments/321-vmware_cluster_info.yml
- plugins/modules/vmware_cluster_info.py
- tests/integration/targets/vmware_cluster_info/aliases
- tests/integration/targets/vmware_cluster_info/tasks/main.yml
This PR is to add the properties parameter and clusters resource summary information to the vmware_cluster_info module.
fixes: https://github.com/ansible-collections/vmware/issues/273
plugins/modules/vmware_cluster_info.py
tested with vCenter/ESXi 6.7
> add the properties parameter and clusters resource summary information to the vmware_cluster_info module

- changelogs/fragments/182_content_library.yml
- plugins/modules/vmware_content_deploy_ovf_template.py
- plugins/modules/vmware_content_deploy_template.py
Added exception handling in vmware_content_deploy_template and
vmware_content_deploy_ovf_template modules.
changelogs/fragments/182_content_library.yml
plugins/modules/vmware_content_deploy_ovf_template.py
plugins/modules/vmware_content_deploy_template.py
> vmware_content_deploy_*: Handle exception while deploying template

- tests/integration/targets/vmware_migrate_vmk/aliases
- tests/integration/targets/vmware_migrate_vmk/tasks/main.yml
This PR is to add an integration test for the vmware_migrate_vmk module.
tested with vCenter/ESXi 7.0
> add an integration test for the vmware_migrate_vmk module

- README.md
Depends-On: Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/559
> doc: explain how to push a release

- plugins/inventory/vmware_vm_inventory.py
Add an example of host filter with OR conditions in vmware inventory plugin
vmware inventory plugin
> add an example of host filter with OR conditions in vmware inventory plugin

- plugins/inventory/vmware_vm_inventory.py
Add a host filter example with regex
vmware_vm_inventory inventory plugin
> add a host filter example with regex

- changelogs/fragments/381-vmware_guest.yml
- plugins/modules/vmware_guest.py
Fixes #381 
vmware_guest
```paste below
```
> vmware_guest: fix issue of checking specified hardware version when disk controller is nvme

- changelogs/fragments/440_vmware_drs_rule.yml
- plugins/modules/vmware_vm_vm_drs_rule.py
- tests/integration/targets/vmware_vm_vm_drs_rule/tasks/main.yml
Fixes: #440
changelogs/fragments/440_vmware_drs_rule.yml
plugins/modules/vmware_vm_vm_drs_rule.py
tests/integration/targets/vmware_vm_vm_drs_rule/tasks/main.yml
> vmware_vm_vm_drs_rule: report changes in check mode

- changelogs/fragments/453_vmware_cluster_info.yml
- plugins/module_utils/vmware_rest_client.py
- plugins/modules/vmware_cluster_info.py
- tests/integration/targets/vmware_cluster_info/tasks/main.yml
Fixes: #453
changelogs/fragments/453_vmware_cluster_info.yml
plugins/modules/vmware_cluster_info.py
tests/integration/targets/vmware_cluster_info/tasks/main.yml
> vmware_cluster_info: Return tag information

- changelogs/fragments/441_vmware_vm_inventory_performance.yaml
- plugins/inventory/vmware_vm_inventory.py
Possible fixes #434
- Improve Orphaned VM check
- Improve `to_nested_dict` function
- `plugins/inventory/vmware_vm_inventory.py`
```paste below
```
> vmware_vm_inventory: Improve plugin performance

- plugins/modules/vmware_category.py
- tests/integration/targets/vmware_cluster_info/tasks/main.yml
plugins/modules/vmware_category.py
tests/integration/targets/vmware_cluster_info/tasks/main.yml
> Disable Category test for cluster

- changelogs/fragments/451_vmware_cluster_ha.yml
- plugins/modules/vmware_cluster_ha.py
- tests/integration/targets/vmware_cluster_ha/tasks/main.yml
Depends-On: #495
Adding "all paths down" and "permanent device loss" config options.
Fixes #451
> vmware_cluster_ha: Add APD and PDL configuration

- changelogs/fragments/vmware_guest_ctrl.yml
- plugins/modules/vmware_guest_controller.py
Handle error raised due to task error in vmware_guest_controller.
changelogs/fragments/vmware_guest_ctrl.yml
plugins/modules/vmware_guest_controller.py
> vmware_guest_controller: Add error handling

- docs/community.vmware.vmware_guest_module.rst
- plugins/modules/vmware_guest.py
> Shorten URL for vApp Properties

- plugins/modules/vmware_deploy_ovf.py
- plugins/modules/vmware_guest_controller.py
- plugins/modules/vmware_guest_file_operation.py
- plugins/modules/vmware_vmkernel.py
- plugins/modules/vmware_vsan_health_info.py
plugins/modules/vmware_guest_controller.py
plugins/modules/vmware_guest_file_operation.py
plugins/modules/vmware_vmkernel.py
plugins/modules/vmware_vsan_health_info.py
> Fix CI for default boolean

- plugins/modules/vmware_datastore_info.py
Fixes: #556
plugins/modules/vmware_datastore_info.py
> vmware_datastore_info: Fix documentation example

- changelogs/fragments/554_vsphere_copy.yml
- plugins/modules/vsphere_copy.py
Fixes: #554
changelogs/fragments/554_vsphere_copy.yml
plugins/modules/vsphere_copy.py
> vsphere_copy: Handle unboundlocalerror

- README.md
- testing.md
> Initial commit for testing document

- README.md
- docs/community.vmware.vmware_datastore_cluster_manager_module.rst
- meta/runtime.yml
- plugins/module_utils/vmware.py
- plugins/modules/vmware_datastore_cluster_manager.py
- tests/integration/targets/vmware_datastore_cluster_manager/aliases
- tests/integration/targets/vmware_datastore_cluster_manager/tasks/main.yml
Module to manage datastores in the given datastore cluster.
Fixes: #503
README.md
docs/community.vmware.vmware_datastore_cluster_manager_module.rst
plugins/modules/vmware_datastore_cluster_manager.py
tests/integration/targets/vmware_datastore_cluster_manager/aliases
tests/integration/targets/vmware_datastore_cluster_manager/tasks/main.yml
> vmware_datastore_cluster_manager: new module

- changelogs/fragments/570_vmware_guest.yml
- plugins/modules/vmware_guest.py
Depends-On: https://github.com/ansible-collections/community.vmware/pull/568
Fixes: #570
changelogs/fragments/570_vmware_guest.yml
> vmware_guest: handle computer name while customization

- docs/community.vmware.vmware_host_iscsi_module.rst
- plugins/modules/vmware_host_iscsi.py
This PR will update the EXAMPLE block in the module.  
Change the module part to FQCN.
plugins/modules/vmware_host_iscsi.py
> vmware_host_iscsi: update EXAMPLE block

- changelogs/fragments/575_vmware_cluster.yml
- plugins/modules/vmware_cluster.py
- plugins/modules/vmware_cluster_drs.py
- plugins/modules/vmware_cluster_ha.py
- plugins/modules/vmware_cluster_vsan.py
Fixes: #575
changelogs/fragments/575_vmware_cluster.yml
plugins/modules/vmware_cluster.py
> vmware_cluster: Consider datacenter while create cluster

- changelogs/fragments/vsan_health_info_refactor.yml
- plugins/modules/vmware_vsan_health_info.py
* Refactor code
* Update documentation
* Add support for using datacenter to find the cluster
changelogs/fragments/vsan_health_info_refactor.yml
plugins/modules/vmware_vsan_health_info.py
> vmware_vsan_health_info: Add new parameter 'datacenter'

- docs/community.vmware.vmware_host_iscsi_info_module.rst
- plugins/modules/vmware_host_iscsi_info.py
This PR will update the module part to a correct FQCN in the EXAMPLE block.
docs/community.vmware.vmware_host_iscsi_info_module.rst
plugins/modules/vmware_host_iscsi_info.py
> vmware_host_iscsi_info: Update the module part in EXAMPLE block

- changelogs/fragments/608_vmware_dvswitch.yml
- plugins/modules/vmware_dvswitch.py
- tests/integration/targets/vmware_dvswitch/tasks/main.yml
Depends-On: #620 
Fixes: #608
changelogs/fragments/608_vmware_dvswitch.yml
plugins/modules/vmware_dvswitch.py
> vmware_dvswitch: correctly add contact information

- changelogs/fragments/633-vmware_host_lockdown.yml
- plugins/modules/vmware_host_lockdown.py
- tests/integration/targets/vmware_host_lockdown/aliases
- tests/integration/targets/vmware_host_lockdown/tasks/main.yml
Support check mode in vmware_host_lockdown module.
vmware_host_lockdown
> vmware_host_lockdown: Support check mode

- README.md
- changelogs/fragments/618_vmware_content_deploy_ovf_template.yml
- docs/community.vmware.vmware_content_deploy_ovf_template_module.rst
- plugins/modules/vmware_content_deploy_ovf_template.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/755
Fixes: #618
README.md
changelogs/fragments/618_vmware_content_deploy_ovf_template.yml
docs/community.vmware.vmware_content_deploy_ovf_template_module.rst
plugins/modules/vmware_content_deploy_ovf_template.py
> vmware_content_deploy_ovf_template: Consistent eagerZeroedThick value

- changelogs/fragments/602_vmware_guest.yml
- plugins/module_utils/vmware.py
- plugins/modules/vmware_guest.py
- plugins/modules/vmware_guest_info.py
There has been much confusion around customvalues in the `vmware_guest` module and what this field should be setting.  This is my attempt to clarify and resolve the situation.
vmware_guest
vmware_guest_info
https://github.com/ansible/ansible/pull/49800
https://github.com/ansible/ansible/issues/64291
> Fix vmware_guest advanced_settings and customvalues

- test-requirements.txt
- tests/unit/module_utils/test_vmware.py
- tests/unit/modules/cloud/vmware/test_vmware_host_sriov.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/785
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/786
> ensure the unittests run fine

- plugins/modules/vmware_guest.py
- tests/integration/targets/vmware_guest/defaults/main.yml
- tests/integration/targets/vmware_guest/tasks/advanced_settings.yml
* Added correct check of advanced_settings
* Update testcases to cover advanced_settings
Fixes: #699
tests/integration/targets/vmware_guest/defaults/main.yml
tests/integration/targets/vmware_guest/tasks/advanced_settings.yml
> vmware_guest: Correct check for advanced_settings

- changelogs/fragments/no_log_sanity.yml
- plugins/modules/vcenter_extension.py
- plugins/modules/vmware_dvs_host.py
- plugins/modules/vmware_guest_custom_attribute_defs.py
- plugins/modules/vmware_guest_sendkey.py
- plugins/modules/vmware_host_iscsi.py
- plugins/modules/vmware_vc_infraprofile_info.py
changelogs/fragments/no_log_sanity.yml
plugins/modules/vmware_host_iscsi.py
plugins/modules/vmware_vc_infraprofile_info.py
tests/sanity/ignore-2.9.txt
> Sanity: no_log check sanity test fixes

- tests/integration/targets/vmware_guest_register_operation/tasks/main.yml
- pass the cluster parameters
- use vmware_vm_info instead of vmware_vm_facts
> vmware_guest_register_operation: fix the test-suite

- tests/integration/targets/vcenter_domain_user_group_info/aliases
- tests/integration/targets/vcenter_extension_info/aliases
- tests/integration/targets/vcenter_folder/aliases
Ensure `ansible-test` pull the `prepare_vmware_tests` dependency.
> vcenter_* tests: add dep on prepare_vmware_tests

- changelogs/fragments/is_template.yml
- docs/community.vmware.vmware_guest_module.rst
- plugins/modules/vmware_guest.py
Replaces https://github.com/ansible-collections/community.vmware/pull/786
@Akasurde This time I followed the correct procedure for modifying the sources that generate docs, generating the docs locally and committing both.
> Clarify is_template in vmware_guest docs

- tests/sanity/ignore-2.12.txt
> fix sanity checks

- plugins/modules/vmware_vcenter_settings_info.py
plugins/modules/vmware_vcenter_settings_info.py
> vmware_vcenter_settings_info: Update logic

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/644-vmware_dvs_portgroup.yml
- changelogs/fragments/712_vmware_vm_inventory.yml
- changelogs/fragments/721_vmware_guest.yml
- changelogs/fragments/729-vmware_host_iscsi_info.yml
- changelogs/fragments/732_vmware_vm_shell.yml
- changelogs/fragments/739-vmware_cluster_drs.yml
- changelogs/fragments/764-vmware_evc_mode.yml
- changelogs/fragments/777_vapp_info.yml
- changelogs/fragments/788-vmware_vm_storage_policy_info.yml
- changelogs/fragments/790-vmware_tag.yml
- changelogs/fragments/791_vmware.yml
- changelogs/fragments/803-vmware_vmotion-better-error-msg.yml
- changelogs/fragments/805-vmware_cluster_info.yml
- changelogs/fragments/825-vmware.yml
- changelogs/fragments/is_template.yml
- docs/community.vmware.vmware_cluster_drs_module.rst
- docs/community.vmware.vmware_cluster_ha_module.rst
- docs/community.vmware.vmware_cluster_vsan_module.rst
- docs/community.vmware.vmware_dvs_portgroup_info_module.rst
- docs/community.vmware.vmware_dvs_portgroup_module.rst
- docs/community.vmware.vmware_vm_inventory_inventory.rst
It's May! Let's push the release.
> prepare 1.10 release

- plugins/inventory/vmware_host_inventory.py
- plugins/module_utils/inventory.py
- tests/integration/targets/inventory_vmware_host_inventory/aliases
- tests/integration/targets/inventory_vmware_host_inventory/playbook/build_inventory.yml
- tests/integration/targets/inventory_vmware_host_inventory/playbook/build_inventory_with_cache.yml
- tests/integration/targets/inventory_vmware_host_inventory/playbook/build_inventory_without_cache.yml
- tests/integration/targets/inventory_vmware_host_inventory/playbook/install_dependencies.yml
- tests/integration/targets/inventory_vmware_host_inventory/playbook/prepare_vmware.yml
- tests/integration/targets/inventory_vmware_host_inventory/playbook/test_inventory_cache.yml
- tests/integration/targets/inventory_vmware_host_inventory/playbook/test_options.yml
- tests/integration/targets/inventory_vmware_host_inventory/playbook/test_vmware_host_inventory.yml
- tests/integration/targets/inventory_vmware_host_inventory/runme.sh
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.12.txt
- tests/sanity/ignore-2.9.txt
* Add inventory plugins for ESXi host
Fixes: #669
plugins/inventory/vmware_host_inventory.py
plugins/module_utils/inventory.py
> Add vmware_host_inventory

- README.md
- docs/community.vmware.vmware_object_role_permission_info_module.rst
- meta/runtime.yml
- plugins/modules/vmware_object_role_permission_info.py
- tests/integration/targets/vmware_object_role_permission_info/alias
- tests/integration/targets/vmware_object_role_permission_info/tasks/main.yml
- tests/integration/targets/vmware_object_role_permission_info/tasks/vmware_object_role_permission_tests.yml
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.12.txt
- tests/sanity/ignore-2.9.txt
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/869
plugins/modules/vmware_object_role_permission_info.py
> vmware_object_role_permission_info: new module

- .github/BOTMETA.yml
As requested on IRC today by LLoyd.
> do not notify lparkes

- changelogs/fragments/874-vmware_object_role_permission_info-principal_permissions.yml
- docs/community.vmware.vmware_object_role_permission_info_module.rst
- plugins/modules/vmware_object_role_permission_info.py
Depends-On: #877
Fixes Issue #868 If principal is provided, will return actual permissions for principal on specified object; otherwise, it returns as originally designed.
vmware_object_role_permission_info.py
```
"changed": false, 
"hostname": "vc.company.com", 
"moid": null, 
"object_name": "myvm", 
"object_type": "VirtualMachine", 
"password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
"port": 443, 
"principal": "some.user@company.com", 
"proxy_host": null, 
"proxy_port": null, 
"username": "vc.user@company.com", 
"validate_certs": false
}
}, 
"permission_info": [
{
"_vimtype": "vim.AuthorizationManager.UserPrivilegeResult", 
"entity": "vim.VirtualMachine:vm-220", 
"privileges": [
"System.Anonymous", 
"System.View", 
"System.Read", …
```
> vmware_object_role_permission_info - principal permissions

- CHANGELOG.rst
- changelogs/changelog.yaml
- docs/community.vmware.vmware_content_deploy_ovf_template_module.rst
- docs/community.vmware.vmware_content_deploy_template_module.rst
- docs/community.vmware.vmware_host_inventory_inventory.rst
- docs/community.vmware.vmware_vm_inventory_inventory.rst
Minor Changes
-------------
- vmware - add processing to answer if the answer question is occurred in starting the vm (https://github.com/ansible-collections/community.vmware/pull/821).
- vmware - find_folder_by_fqpn added to support specifying folders by their fully qualified path name, defined as I(datacenter)/I(folder_type)/subfolder1/subfolder2/.
- vmware - folder field default changed from None to vm.
- vmware_content_deploy_ovf_template - storage_provisioning default changed from None to thin, in keeping with VMware best practices for flash storage.
- vmware_dvs_host - implement adding pNICs to LAGs (https://github.com/ansible-collections/community.vmware/issues/112).
- vmware_guest_instant_clone - added a new option to wait until the vmware tools start …
> prepare 1.12.0 release

- plugins/modules/vmware_guest_info.py
Depends-on #930
The link https://code.vmware.com/web/sdk/60/vcloudsuite-python no longer exists
vmware_guest_info
> Update SDK URL for vmware_guest_info

- tests/integration/targets/inventory_vmware_host_inventory/aliases
- tests/integration/targets/inventory_vmware_vm_inventory/aliases
- tests/integration/targets/vmware_host_service_manager/aliases
Some integration tests are failing and prevent us from going forward.
inventory_vmware_host_inventory
inventory_vmware_vm_inventory
vmware_host_service_manager
#939, #941 and #943
> Disable some tests

- test-requirements.txt
We don't need any feature from the real selinux package. Let's mock it.
> test: use selinux_please_lie_to_me

- tests/integration/targets/vmware_host_ntp/aliases
- tests/integration/targets/vmware_host_ntp/tasks/main.yml
This PR will fix vmware_host_ntp integration test errors.
tests/integration/targets/vmware_host_ntp/aliases
tests/integration/targets/vmware_host_ntp/tasks/main.yml
tested on vCenter/ESXi 7.0.2
> vmware_host_ntp: Fix integration test errors

- tests/integration/targets/prepare_vmware_tests/tasks/init_vcsim_with_systemd.yml
Wait for 1 second to be sure the service is actually available.
tests
> govcsim: wait for govcsim to open up port 8080

- tests/integration/targets/vmware_first_class_disk/aliases
- tests/integration/targets/vmware_guest/aliases
- tests/integration/targets/vmware_guest_disk_info/aliases
- tests/integration/targets/vmware_guest_instant_clone/aliases
- tests/integration/targets/vmware_guest_network/aliases
- tests/integration/targets/vmware_guest_powerstate/aliases
- tests/integration/targets/vmware_guest_screenshot/aliases
- tests/integration/targets/vmware_guest_tools_wait/aliases
- tests/integration/targets/vmware_vm_inventory/aliases
I think that #957 broke the CI pipeline and would like to revert it.
> Revert PR 957

- changelogs/fragments/850_vmware_inventory.yml
- plugins/inventory/vmware_host_inventory.py
- plugins/inventory/vmware_vm_inventory.py
Fixes: #850
changelogs/fragments/850_vmware_inventory.yml
plugins/inventory/vmware_host_inventory.py
> vmware: filter hosts before templating inventory

- changelogs/fragments/853-vmware_guest.yml
- plugins/module_utils/vm_device_helper.py
- plugins/module_utils/vmware_spbm.py
- plugins/modules/vmware_guest.py
1. create new VM with virtual NVDIMM device
2. add, reconfigure, or remove new NVDIMM device from existing VM
Fixes #853 
vmware_guest
```paste below
```
> Add NVDIMM device support in vmware_guest module

- CHANGELOG.rst
- changelogs/changelog.yaml
- docs/community.vmware.vmware_host_inventory_inventory.rst
- docs/community.vmware.vmware_host_service_manager_module.rst
- docs/community.vmware.vmware_vm_inventory_inventory.rst
- tools/prepare_minor_release.yml
New minor release, 1.14.0.
Fixes #1004
This PR also includes a new playbook, `prepare_minor_release.yml`, which I've used to create this release.
> prepare 1.14.0 release

- requirements.txt
- test-requirements.txt
Reduce the range of supported release of pyVmomi.
https://github.com/ansible-collections/community.vmware/pull/1023#issuecomment-919398669
> depends on pyvmomi 6.7+

- README.md
- tools/create_documentation.yml
- tools/prepare_minor_release.yml
- tools/prepare_release.yml
- tools/update_documentation.yml
Document docs update and ~prepare_minor_release.yml~ prepare_release.yml
Fixes #986
README.md
see this [comment](https://github.com/ansible-collections/community.vmware/pull/1019#issuecomment-910642440)
cc @Akasurde @sky-joker
> README: Document docs update and how to prepare a release

- plugins/modules/vmware_drs_group.py
- plugins/modules/vmware_drs_group_facts.py
- plugins/modules/vmware_drs_group_info.py
- plugins/modules/vmware_host_passthrough.py
- plugins/modules/vmware_vm_host_drs_rule.py
- scripts/inventory/vmware.py
- tests/unit/mock/loader.py
- tests/unit/modules/cloud/vmware/test_vmware_host_sriov.py
Fixes #1045
vmware_drs_group
vmware_drs_group_facts
vmware_drs_group_info
vmware_host_passthrough
vmware_vm_host_drs_rule
see [this comment](https://github.com/ansible-collections/community.vmware/pull/1010#issuecomment-924295225) and following
> Fix sanity / pylint tests

- changelogs/fragments/164-vmware_deploy_ovf.yml
- plugins/module_utils/vmware.py
- plugins/modules/vmware_deploy_ovf.py
Fixes #164 
```paste below
```
> Fix deploy ovf issue when there are multiple datacenters

- changelogs/fragments/1043_vmware_guest_serial.yml
- plugins/modules/vmware_guest_serial_port.py
Fixes: #1043
changelogs/fragments/1043_vmware_guest_serial.yml
plugins/modules/vmware_guest_serial_port.py
> vmware_guest_serial_port: Handle serial backing type

- docs/community.vmware.vmware_vswitch_module.rst
- plugins/modules/vmware_vswitch.py
Add example to delete a vswitch on a ESXi host.
vmware_vswitch.py
vmware_vswitch_module.rst
```paste below
```
> vmware_vswitch: Add example to delete a vswitch on a ESXi host

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/1043_vmware_guest_serial.yml
- changelogs/fragments/1082_vmware.yml
- changelogs/fragments/1083_vmware_host_lockdown.yml
- changelogs/fragments/840_vmware_vswitch.yml
- changelogs/fragments/996_vmware_guest_cross_vc_clone.yml
- docs/community.vmware.vmware_guest_cross_vc_clone_module.rst
- docs/community.vmware.vmware_guest_tpm_module.rst
> prepare 1.16.0 release

- testing.md
We often ask people to test a PR and tell us if it fixes their issue. But we haven't documented how to do this. There are several ways, but we should document at least one.
testing.md
Just to _have_ some additional information, I'll link to [this comment](https://github.com/ansible-collections/community.vmware/pull/1055#issuecomment-956215075).
> Document checking out a PR

- tests/integration/targets/vmware_guest_disk/tasks/main.yml
vmware_guest_disk needs vmx-13 to reconfigure the disks.
> vmware_guest_disk/test: use vmx-13

- tests/integration/targets/vmware_migrate_vmk/aliases
See: https://github.com/ansible-collections/community.vmware/issues/1114
> temporarily disable vmware_migrate_vmk

- tests/integration/targets/vmware_datastore_cluster/tasks/main.yml
Clean up the datastore cluster.
> vmware_datastore_cluster/test: clean up resources

- tests/integration/targets/vmware_guest/tasks/network_with_device.yml
> vmware_guest/test: reduce network_with_device res usage

- plugins/modules/vmware_vmotion.py
- plugins/modules/vmware_vspan_session.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1241
Update the example task names in the 2 modules
vmware_vmotion.py
vmware_vspan_session.py
vmware_vspan_session.py - Update the name of the 3rd example. Replace Create with Delete as the example has state set to absent
vmware_vmotion.py - Remove duplicate "of" string in the 3rd example.
> Update example task names in vmotion and vspan modules

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1013-vmware_rdm_updates.yml
- changelogs/fragments/1017-vmware_guest-fix_administrator_password.yml
- changelogs/fragments/1044_add_syscontact_syslocation_vmware_host_snmp.yml
- changelogs/fragments/1085_add_show_tag_to_vmware_datastore_info.yml
- changelogs/fragments/1117_add_additional_usb_scan_codes.yml
- changelogs/fragments/rescan_VMFS_feature.yml
- docs/community.vmware.vmware_datastore_info_module.rst
- docs/community.vmware.vmware_guest_disk_module.rst
- docs/community.vmware.vmware_guest_module.rst
- docs/community.vmware.vmware_guest_sendkey_module.rst
- docs/community.vmware.vmware_host_inventory_inventory.rst
- docs/community.vmware.vmware_host_scanhba_module.rst
- docs/community.vmware.vmware_host_snmp_module.rst
- docs/community.vmware.vmware_vm_inventory_inventory.rst
- docs/community.vmware.vmware_vmotion_module.rst
- docs/community.vmware.vmware_vspan_session_module.rst
- docs/community.vmware.vmware_vswitch_facts_module.rst
- docs/community.vmware.vmware_vswitch_info_module.rst
> prepare 1.17.0 release

- changelogs/fragments/1112-vcenter_folder.yml
- plugins/modules/vcenter_folder.py
- tests/integration/targets/vcenter_folder/tasks/main.yml
- tests/integration/targets/vcenter_folder/tasks/regression_folder_collision.yml
fixes #1112
added `recursion` flag in `get_folder` method for behavior  managing and fixed bug with folders collision
added regression test for catching the bug in future
vcenter_folder
> fix folders collision

- changelogs/fragments/vmware_guest-vbs.yml
- plugins/modules/vmware_guest.py
#351 made me think about how we handle virtualization based security and I don't like it. I really don't think it's a good idea if modules silently configure something, I think it should always be explicit.
vmware_guest
#816
> vmware_guest: Make VBS requirements explicit

- tests/integration/targets/vmware_datastore_info/aliases
- tests/integration/targets/vmware_guest/aliases
- tests/integration/targets/vmware_guest_disk/aliases
- tests/integration/targets/vmware_host_scsidisk_info/aliases
Depends-On: https://github.com/ansible-collections/community.vmware/pull/1194
> tests/govcsim: ignore some broken tests

- changelogs/fragments/25-vmware_guest_network-catch_taskerror.yml
- plugins/modules/vmware_guest_network.py
- plugins/modules/vmware_host_firewall_manager.py
- plugins/modules/vmware_resource_pool.py
- plugins/modules/vsphere_copy.py
- tests/integration/targets/vmware_datastore_info/aliases
- tests/integration/targets/vmware_guest/aliases
- tests/integration/targets/vmware_guest_disk/aliases
Backport bugfix #1169 and documentation improvements from #1191 and #1194.
vmware_host_firewall_manager
vmware_resource_pool
vsphere_copy
> backport vmware_guest_network: Fix uncaught exception and doc improvements

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/25-vmware_guest_network-catch_taskerror.yml
- docs/community.vmware.vmware_guest_module.rst
- docs/community.vmware.vmware_guest_network_module.rst
- docs/community.vmware.vmware_resource_pool_module.rst
Bug fix release for 1.17.
`ansible-playbook --extra-vars "version=1.17.1" tools/prepare_release.yml`
> prepare 1.17.1 release

- tests/integration/targets/inventory_vmware_vm_inventory/aliases
The test is broken.
Closes: #1219
> don't test inventory_vmware_vm_inventory with govcsim

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/1176-vmware_dv_portgroup.yml
- changelogs/fragments/1203-vmware_guest_storage_policy-controller_number-param.yml
- changelogs/fragments/datastore_url-added-to-vm_info.yaml
- changelogs/fragments/remove_pre-collection_version_added.yml
- changelogs/fragments/vmware_vm_config_option.yml
- docs/community.vmware.vcenter_license_module.rst
- docs/community.vmware.vcenter_standard_key_provider_module.rst
- docs/community.vmware.vmware_guest_storage_policy_module.rst
- docs/community.vmware.vmware_host_user_manager_module.rst
- docs/community.vmware.vmware_object_role_permission_module.rst
- docs/community.vmware.vmware_vm_info_module.rst
- docs/community.vmware.vmware_vm_inventory_inventory.rst
New major release 2.1.0!
ansible-playbook --extra-vars "version=2.1.0" tools/prepare_release.yml
> prepare 2.1.0 release

- README.md
Announcing EOL of version 1 for November 2022 (EOL of ansible-core 2.11) and version 2 for May 2023 (EOL of ansible-core 2.12).
Fixes #1208
README.md
> REAMDE.md: Add EOL

- plugins/connection/vmware_tools.py
- plugins/httpapi/vmware.py
- plugins/inventory/vmware_host_inventory.py
- plugins/inventory/vmware_vm_inventory.py
Fixes #1244
plugins/connection/vmware_tools
plugins/httpapi/vmware
plugins/inventory/vmware_host_inventory
plugins/inventory/vmware_vm_inventory
The validate-modules sanity test now also validates plugins: https://github.com/ansible-collections/news-for-maintainers/issues/9
> Fix validate-modules issues

- README.md
- changelogs/fragments/1176-vmware_dv_portgroup.yml
- changelogs/fragments/1243-vmware-dvs-host-uplink-ordering.yml
- changelogs/fragments/datastore_url-added-to-vm_info.yaml
- changelogs/fragments/remove_pre-collection_version_added.yml
- changelogs/fragments/vmware_vm_config_option.yml
- plugins/connection/vmware_tools.py
- plugins/doc_fragments/vmware.py
- plugins/httpapi/vmware.py
- plugins/inventory/vmware_host_inventory.py
- plugins/inventory/vmware_vm_inventory.py
- plugins/modules/vmware_dvs_host.py
- plugins/modules/vmware_object_role_permission.py
- plugins/modules/vmware_vm_config_option.py
- plugins/modules/vmware_vm_info.py
- tests/integration/targets/inventory_vmware_host_inventory/runme.sh
- tests/integration/targets/inventory_vmware_vm_inventory/runme.sh
- tests/integration/targets/vmware_vm_inventory/ansible.cfg
- tools/prepare_release.yml
Backports for 1.18:
- #1143
- #1171
- #1215
- #1176
- #1228
- #1211
- #1237
- #1245
- #1243
vmware_vm_info
> Backports 1.18

- plugins/connection/vmware_tools.py
Depends-On: https://github.com/ansible-collections/community.vmware/pull/1194
Clarify the user vars, to avoid others running in to the same issue as explained here:
https://github.com/ansible-collections/community.vmware/issues/912#issuecomment-1013696171
Fixes: #912 
vmware_tools.py
> Document user variable usage

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1176-vmware_dv_portgroup.yml
- changelogs/fragments/1243-vmware-dvs-host-uplink-ordering.yml
- changelogs/fragments/datastore_url-added-to-vm_info.yaml
- changelogs/fragments/remove_pre-collection_version_added.yml
- changelogs/fragments/vmware_vm_config_option.yml
- docs/community.vmware.vcenter_license_module.rst
- docs/community.vmware.vmware_httpapi.rst
- docs/community.vmware.vmware_object_role_permission_module.rst
- docs/community.vmware.vmware_tools_connection.rst
- docs/community.vmware.vmware_vm_info_module.rst
- docs/community.vmware.vmware_vm_inventory_inventory.rst
> prepare 1.18.0 release

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1241-vmware_vm_info-add_the_posibility_to_get_only_one_vm_by_name.yaml
- changelogs/fragments/1243-vmware-dvs-host-uplink-ordering.yml
- changelogs/fragments/fix_shutdownguest_state_idempotency.yml
- changelogs/fragments/vmware_vm_config_option.yml
- docs/community.vmware.vmware_httpapi.rst
- docs/community.vmware.vmware_tools_connection.rst
- docs/community.vmware.vmware_vm_info_module.rst
> prepare 2.2.0 release

- plugins/modules/vmware_cluster_dpm.py
- tests/integration/targets/vmware_cluster_dpm/aliases
- tests/integration/targets/vmware_cluster_dpm/tasks/main.yml
SUMMARY
New module to manage Distributed Power Management (DPM) on VMware vSphere clusters
ISSUE TYPE
New Module Pull Request
COMPONENT NAME
vmware_cluster_dpm.py
ADDITIONAL INFORMATION
no additional information
> add vmware_cluster_dpm.py

- .github/BOTMETA.yml
- changelogs/fragments/1294-remove_vcsim.yml
- docs/docsite/extra-docs.yml
- docs/docsite/rst/dev_guide.rst
- docs/docsite/rst/vmware_scenarios/vmware_external_doc_links.rst
- plugins/modules/vmware_datastore_info.py
- plugins/modules/vmware_dvs_portgroup_info.py
- plugins/modules/vmware_guest.py
- testing.md
- tests/integration/cloud-config-vcenter.ini.sample
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1511
This is a follow-up PR to #1293.
I wanted to remove VCSIM from the Developer Guide but was asked to move it to the collection (ansible/ansible#77585). I'll start with this and then check if VCSIM mentioned somewhere else in the documentation.
> VCSIM removal part 4

- tools/prepare_release.yml
Do not try to commit the generated changelog if there is actually
nothing to commit.
> prepare_release.yml: only commit changes is needed

- docs/docsite/rst/dev_guide.rst
Sorry, gave the wrong initial instructions. Each rst has to have a unique anchor. The current anchor is a duplicate of what is used in the scenario guide so modifying this to make it unique.
Related to https://github.com/ansible/ansible/pull/77723
docs/docsite/rst/dev_guide.rst
```paste below
```
> make dev guide anchor unique

- changelogs/fragments/1311-vmware_maintenancemode-check_mode.yml
- plugins/modules/vmware_maintenancemode.py
Add support for `check_mode` to the `vmware_maintenancemode` module.
vmware_maintenancemode
> vmware_maintenancemode: Add support for check_mode

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1297-vmware_migrate_vmk-add_vlan.yml
- changelogs/fragments/1298-vmware_vswitch-add_network_policy_support.yml
- changelogs/fragments/1309-vmware_vswitch_info-add_network_policy_support.yml
- changelogs/fragments/1311-vmware_maintenancemode-check_mode.yml
- changelogs/fragments/disutils.version.yml
- docs/community.vmware.vmware_migrate_vmk_module.rst
- docs/community.vmware.vmware_vm_inventory_inventory.rst
- docs/community.vmware.vmware_vswitch_info_module.rst
- docs/community.vmware.vmware_vswitch_module.rst
> prepare 2.4.0 release

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1283-vmware_vm_info-allocaded_storag_cpu_memory_output.yaml
- galaxy.yml
> prepare 2.5.0 release

- galaxy.yml
Reset the version in `galaxy.yml`.
galaxy.yml
> Remove version 2.5.0 from galaxy.yml

- changelogs/fragments/184_vmware_host_facts.yml
- plugins/modules/vmware_host_facts.py
- tests/integration/targets/vmware_host_facts/aliases
- tests/integration/targets/vmware_host_facts/tasks/main.yml
The module crashes when a host is disconnected from vCenter.
Fixes: #184
#318
> vmware_host_facts: Fix module when host is disconnected

- docs/docsite/rst/dev_guide.rst
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.12.txt
Fix some sanity and lint issues.
docs/docsite/rst/dev_guide.rst
tests/sanity/ignore-2.12.txt
> Fix some sanity and lint issues

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1240-vmware_vmotion-add_cluster_storage_cluster.yaml
- changelogs/fragments/1270-vmware_cfg_backup-failed_to_write_backup_file.yaml
- changelogs/fragments/1337_vmware_host_vmnic_info-fix_disconnected.yml
- changelogs/fragments/184_vmware_host_facts.yml
- docs/community.vmware.vmware_host_facts_module.rst
- docs/community.vmware.vmware_vmotion_module.rst
- galaxy.yml
> prepare 2.6.0 release

- galaxy.yml
Reset the version in `galaxy.yml`.
galaxy.yml
> Remove version 2.6.0 from galaxy.yml

- changelogs/fragments/1337_vmware_host_vmnic_info-fix_disconnected.yml
- plugins/modules/vmware_host_vmnic_info.py
- tests/integration/targets/vmware_host_vmnic_info/tasks/main.yml
Backport PR #1337 to `stable-1`.
vmware_host_vmnic_info
> Backport PR #1337 to stable-1

- changelogs/fragments/1270-vmware_cfg_backup-failed_to_write_backup_file.yaml
- plugins/modules/vmware_cfg_backup.py
Backport PR #1335 to `stable-1`.
vmware_cfg_backup
> Backport PR #1335 to stable-1

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/1270-vmware_cfg_backup-failed_to_write_backup_file.yaml
- changelogs/fragments/1337_vmware_host_vmnic_info-fix_disconnected.yml
- changelogs/fragments/184_vmware_host_facts.yml
- docs/community.vmware.vmware_host_facts_module.rst
- docs/community.vmware.vmware_host_inventory_inventory.rst
- docs/community.vmware.vmware_vm_inventory_inventory.rst
New bugfix release 1.18.1
vmware_cfg_backup 
vmware_host_vmnic_info
`ansible-playbook tools/prepare_release.yml --extra-vars "version=1.18.1"`
> prepare 1.18.1 release

- changelogs/fragments/1338-vmware_object_role_permission-and-vmware_object_role_permission_info.yaml
- plugins/modules/vmware_object_role_permission.py
- plugins/modules/vmware_object_role_permission_info.py
Add StoragePod to the List of object types
- vmware_object_role_permission.py
- vmware_object_role_permission_info.py
> vmware_object_role_permission and info - Add StoragePod to the List of object types

- changelogs/fragments/1351-vmaware_dvswitch_nioc.yaml
- plugins/modules/vmware_dvswitch_nioc.py
Add backupNfc and nvmetcp to the resources.
vmware_dvswitch_nioc.py
```
> vmware_dvswitch_nioc - Add backupNfc and nvmetcp to the resources

- changelogs/fragments/1362.yml
Add missing changelog fragment for PR #1362
> Changelog fragment for PR #1362

- changelogs/fragments/1362.yml
- plugins/modules/vmware_content_deploy_ovf_template.py
- plugins/modules/vmware_content_deploy_template.py
Backport PR #1362 to `stable-1`
#1290
> Backport PR #1362 to stable-1

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1321-vmware_vm_info-allocaded_storag_cpu_memory_output.yaml
- changelogs/fragments/1362.yml
New bugfix release 1.18.2
`ansible-playbook tools/prepare_release.yml --extra-vars "version=1.18.2"`
> prepare 1.18.2 release

- changelogs/fragments/1318-vmware_guest_network-attribute_error.yml
Add a changelog fragment for PR #1318.
> Changelog fragment for PR #1318

- changelogs/fragments/1402-vmware_guest_change_to_fail_json.yml
- plugins/modules/vmware_guest.py
Signed-off-by: Diane Wang <dianew@vmware.com>
Fixes #1401 
vmware_guest
```paste below
```
> vmware_guest: change fail to fail_json function

- plugins/modules/vmware_dvswitch.py
- plugins/modules/vmware_guest_register_operation.py
- plugins/modules/vmware_vspan_session.py
It looks like there are some new linter tests that we run into.
vmware_guest_register_operation
vmware_vspan_session
Originally, I wanted to fix this in #1416 but maybe it's better to have a dedicated PR for this.
> Fix new lint errors

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1376-vmware_guest_sendkey-add-ctrl_x-support.yaml
- changelogs/fragments/1388-vmware_cfg_backup-improve_error_msg.yml
- changelogs/fragments/1392-proposed_fixes_for_backup_behavior_1383.yml
- changelogs/fragments/1402-vmware_guest_change_to_fail_json.yml
- changelogs/fragments/1407-vmware_vm_info-inaccessible_vm.yml
- changelogs/fragments/1418_vmware_host_vmnic_info.yml
- changelogs/fragments/1419-vmware_dvs_portgroup-problem_with_spec_numPorts_is_none_solved.yaml
- galaxy.yml
I'm afraid there are a lot of open issues and PRs I didn't find the time to work on... nevertheless, there _are_ some changes that are worth shipping imho.
> prepare 2.8.0 release

- galaxy.yml
ansible-playbook tools/unset_version.yml
> Remove version 2.8.0 from galaxy.yml

- plugins/connection/vmware_tools.py
- plugins/modules/vmware_cluster_vsan.py
- plugins/modules/vmware_local_user_info.py
- plugins/modules/vmware_vsan_health_info.py
- scripts/inventory/vmware.py
- scripts/inventory/vmware_inventory.py
Fix pylint issues
vmware_tools
vmware_local_user_info
scripts/inventory/vmware.py
scripts/inventory/vmware_inventory.py
> Fix pylint issues

- changelogs/fragments/1420-vmware_cluster_ha-add_apd_settings.yaml
- plugins/modules/vmware_cluster_ha.py
- plugins/modules/vmware_dvswitch.py
- plugins/modules/vmware_guest_register_operation.py
- plugins/modules/vmware_vspan_session.py
Add:
- The response recovery delay time in sec for storage failures categorized as All Paths Down (APD).
- VM response recovery reaction for storage failures categorized as All Paths Down (APD).
vmware_cluster_ha.py
> vmware_cluster_ha - Add APD delay time and vm reaction

- changelogs/fragments/1430-vmware_content_library_info-add_subscribed_libraries.yaml
- plugins/modules/vmware_content_library_info.py
Add Subscribed Libraries to the module.
Fixes #1430
vmware_content_library_info
> vmware_content_library_info: Add Subscribed Libraries

- galaxy.yml
ansible-playbook tools/unset_version.yml
> Remove version 2.9.1 from galaxy.yml

- tests/sanity/ignore-2.15.txt
> Fix sanity for 2.15 tests

- tests/sanity/ignore-2.15.txt
Fix sanity for 2.15 tests
Backport #1467
> Fix sanity for 2.15 tests (#1467)

- changelogs/fragments/1443-vmware_dvs_portgroup-update_netflow_not_work.yaml
- plugins/modules/vmware_dvs_portgroup.py
Backport #1443
vmware_dvs_portgroup.py
> vmware_dvs_portgroup - Update Netflow Settings of DVS not Work (#1443)

- plugins/modules/vmware_datastore.py
- tests/integration/targets/vmware_datastore/aliases
- tests/integration/targets/vmware_datastore/tasks/main.yml
New Module to Change Settings on the Datastore.
Settings like:
- storage_io_control
- congestion_threshold_percentage
- congestion_threshold_manual
- statistic_collection
vmware_datastore.py
#1381
> New module vmware_datastore

- changelogs/fragments/1481-required_ansible_version.yml
- meta/runtime.yml
Fix required ansible-core version
Fixes #1480
> Fix required ansible-core version

- README.md
Add upcoming release 3.0.0 to `README.md`.
README.md
> Add 3.0.0 to README

- README.md
Add upcoming release 3.0.0 to `README.md`.
README.md
> Add 3.0.0 to README (backport #1488)

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/1265-vmware_tag_manager-set_idempotency.yml
- changelogs/fragments/1443-vmware_dvs_portgroup-update_netflow_not_work.yaml
- changelogs/fragments/1466-vmware_guest_disk-change_iolimit_without_size.yml
- changelogs/fragments/1481-required_ansible_version.yml
- galaxy.yml
> prepare 2.10.0 release

- galaxy.yml
> Remove version 3.0.0 from galaxy.yml

- galaxy.yml
> Remove version 2.10.0 from galaxy.yml

- changelogs/fragments/1503-vmware_tag_manager-fix_performance_issue_during_tag_processing.yml
- plugins/module_utils/vmware_rest_client.py
- plugins/modules/vmware_tag_manager.py
Backport of #1504: This fix solves the performance issue during tag processing.
#1503
> Backport vmware_tag_manager: Tag processing is very slow

- README.md
Document that 1.x is unmaintained.
README.md
> Document 1.x as unmaintained

- test-requirements.txt
> 2.x test-requirements: add pytest-fork

- README.md
Document that 1.x is unmaintained.
README.md
Backport #1519
> 2.x: Document 1.x as unmaintained

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/1323-vmware_guest_file_operation.yml
- changelogs/fragments/1485-vmware_guest_add_script_text.yml
- changelogs/fragments/1501-vmware_tag_manager-Fix_failure_when_changing_single_cardinal_tag_category.yml
- changelogs/fragments/1503-vmware_tag_manager-fix_performance_issue_during_tag_processing.yml
- changelogs/fragments/1508-vmware_dvs_portgroup.yaml
- changelogs/fragments/1514-vmware_host_lockdown-remove-deprecated-api-calls.yml
- docs/community.vmware.vmware_dvs_portgroup_module.rst
- docs/community.vmware.vmware_guest_file_operation_module.rst
- docs/community.vmware.vmware_guest_module.rst
- docs/community.vmware.vmware_host_lockdown_exceptions_module.rst
- galaxy.yml
> prepare 3.1.0 release

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1501-vmware_tag_manager-Fix_failure_when_changing_single_cardinal_tag_category.yml
- changelogs/fragments/1503-vmware_tag_manager-fix_performance_issue_during_tag_processing.yml
- galaxy.yml
New bugfix release 2.10.1!
`ansible-playbook tools/prepare_release.yml --extra-vars "version=2.10.1"`
> prepare 2.10.1 release

- galaxy.yml
> Remove version 3.1.0 from galaxy.yml

- galaxy.yml
> Remove version 2.10.1 from galaxy.yml

- changelogs/fragments/1511-vmware_guest-vpmc.yml
- plugins/modules/vmware_guest.py
Fixes #1511
Add support for virtual performance counters.
vmware_guest
This is a follow-up PR to #1534 that ports the implementation of vPMC to the main branch.
> vmware_guest: Add vPMC support

- meta/runtime.yml
`runtime.yml` isn't correct
Backport of #1562
> 2.x: Fix meta/runtime.yml

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/1511-vmware_guest-vpmc.yml
- changelogs/fragments/1511-vmware_vm_info.yml
- changelogs/fragments/1522-vmware_dvs_portgroup.yml
- changelogs/fragments/1532-vmware_guest_custom_attributes.yml
- changelogs/fragments/1539-vmware_guest_shares.yml
- changelogs/fragments/1540-vmware_host_lockdown.yml
- changelogs/fragments/1541-vmware_object_custom_attributes_info.yml
- changelogs/fragments/1543-vmware_guest_boot_manager.yml
- changelogs/fragments/1544-vmware_portgroup_info.yml
- changelogs/fragments/1555-vmware_guest_instant_clone-pyvmomi_8_0_0_1.yml
- docs/community.vmware.vcenter_standard_key_provider_module.rst
- docs/community.vmware.vmware_content_library_manager_module.rst
- docs/community.vmware.vmware_custom_attribute_manager_module.rst
- docs/community.vmware.vmware_custom_attribute_module.rst
- docs/community.vmware.vmware_dvswitch_nioc_module.rst
- docs/community.vmware.vmware_guest_boot_manager_module.rst
- docs/community.vmware.vmware_guest_custom_attributes_module.rst
- docs/community.vmware.vmware_guest_module.rst
- docs/community.vmware.vmware_guest_sendkey_module.rst
- docs/community.vmware.vmware_host_active_directory_module.rst
- docs/community.vmware.vmware_host_snmp_module.rst
- galaxy.yml
> prepare 3.2.0 release

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1477-vmware_object_custom_attributes_info.yml
- changelogs/fragments/1522-vmware_dvs_portgroup.yml
- changelogs/fragments/1544-vmware_portgroup_info.yml
- changelogs/fragments/1555-vmware_guest_instant_clone-pyvmomi_8_0_0_1.yml
- docs/community.vmware.vcenter_standard_key_provider_module.rst
- docs/community.vmware.vmware_content_library_manager_module.rst
- docs/community.vmware.vmware_dvs_host_module.rst
- docs/community.vmware.vmware_dvswitch_lacp_module.rst
- docs/community.vmware.vmware_dvswitch_nioc_module.rst
- docs/community.vmware.vmware_guest_module.rst
- docs/community.vmware.vmware_guest_network_module.rst
- docs/community.vmware.vmware_guest_sendkey_module.rst
- docs/community.vmware.vmware_host_active_directory_module.rst
- docs/community.vmware.vmware_host_snmp_module.rst
- galaxy.yml
New release 2.10.2!
`ansible-playbook tools/prepare_release.yml --extra-vars "version=2.10.2"`
> prepare 2.10.2 release

- galaxy.yml
> Remove version 3.2.0 from galaxy.yml

- galaxy.yml
> Remove version 2.10.2 from galaxy.yml

- changelogs/fragments/1272-vmware_guest-check_mode.yml
- plugins/modules/vmware_guest.py
- tests/integration/targets/vmware_guest/tasks/advanced_settings.yml
- tests/integration/targets/vmware_guest/tasks/cdrom_d1_c1_f0.yml
- tests/integration/targets/vmware_guest/tasks/cdrom_d1_c1_f1.yml
- tests/integration/targets/vmware_guest/tasks/check_mode.yml
- tests/integration/targets/vmware_guest/tasks/reconfig_vm_to_latest_version.yml
- tests/integration/targets/vmware_guest/tasks/windows_vbs_d1_c1_f0.yml
- tests/integration/targets/vmware_guest_instant_clone/tasks/main.yml
Fixes #1272
vmware_guest
This is a follow-up PR to #1534 that ports the fixes for check mode to the main branch.
> vmware_guest: Fix check mode

- plugins/modules/vmware_guest_vgpu_info.py
Fixes #1576
vmware_guest_vgpu_info
Provides information about vGPU profiles of a virtual machine
```paste below
```
> Add module vmware_guest_vgpu_info

- changelogs/fragments/1579-vmware_guest_network.yml
- plugins/module_utils/vm_device_helper.py
- plugins/modules/vmware_guest_network.py
- tests/integration/targets/vmware_guest_network/tasks/main.yml
Signed-off-by: Diane Wang <dianew@vmware.com>
```paste below
```
> vmware_guest_network: add support pvrdma network adapter

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1578-vmware_tools-pyvmomi_8_0_0_1.yml
- galaxy.yml
- tox.ini
New release 2.10.3!
`ansible-playbook tools/prepare_release.yml --extra-vars "version=2.10.3"`
> prepare 2.10.3 release

- galaxy.yml
> Remove version 3.3.0 from galaxy.yml

- galaxy.yml
> Remove version 2.10.3 from galaxy.yml

- changelogs/fragments/1610-scenario_guides.yml
- docs/docsite/rst/vmware_scenarios/vmware_inventory_filters.rst
- docs/docsite/rst/vmware_scenarios/vmware_inventory_hostnames.rst
- docs/docsite/rst/vmware_scenarios/vmware_inventory_vm_attributes.rst
> Fix broken references in scenario guides

- changelogs/fragments/1610-scenario_guides.yml
- docs/docsite/rst/vmware_scenarios/vmware_inventory_filters.rst
- docs/docsite/rst/vmware_scenarios/vmware_inventory_hostnames.rst
- docs/docsite/rst/vmware_scenarios/vmware_inventory_vm_attributes.rst
Backport #1611
scenario guides
#1610
> Fix broken references in scenario guides (#1611)

- changelogs/fragments/1618_pylint.yml
- plugins/modules/vmware_cluster_info.py
- plugins/modules/vmware_dvswitch.py
- plugins/modules/vmware_dvswitch_lacp.py
- plugins/modules/vmware_dvswitch_uplink_pg.py
- plugins/modules/vmware_portgroup.py
- plugins/modules/vmware_vcenter_settings.py
- plugins/modules/vmware_vcenter_statistics.py
- tests/unit/module_utils/test_vmware.py
Fixes #1618
vmware_dvswitch_lacp
vmware_dvswitch_uplink_pg
vmware_portgroup
vmware_vcenter_statistics
ansible-collections/news-for-maintainers#33 / ansible/ansible#79878
> 20230203 Fix pylint issues

- changelogs/fragments/1618_pylint.yml
- plugins/modules/vmware_cluster_info.py
- plugins/modules/vmware_dvswitch.py
- plugins/modules/vmware_dvswitch_lacp.py
- plugins/modules/vmware_dvswitch_uplink_pg.py
- plugins/modules/vmware_portgroup.py
- plugins/modules/vmware_vcenter_settings.py
- plugins/modules/vmware_vcenter_statistics.py
- tests/unit/module_utils/test_vmware.py
Backport #1619
vmware_dvswitch_lacp
vmware_dvswitch_uplink_pg
vmware_portgroup
vmware_vcenter_statistics
ansible-collections/news-for-maintainers#33 / ansible/ansible#79878
> Backport 1619: Fix pylint issues

- tools/create_documentation_tasks.yml
The name of the task is `Refresh the README.md `, but it also updates the module documentation. Adding this to make it clearer.
tools/create_documentation_tasks.yml
https://github.com/ansible-collections/community.vmware/pull/1623#issuecomment-1421112743
> tools/create_documentation_tasks: Improve task name

- tools/create_documentation_tasks.yml
The name of the task is `Refresh the README.md`, but it also updates the module documentation. Adding this to make it clearer.
tools/create_documentation_tasks.yml
Backport #1624
> Backport tools/create_documentation_tasks: Improve task name

- changelogs/fragments/1641_extend_result_docs_guest_disk
- plugins/modules/vmware_guest_disk.py
Document the missing return value `disk_changes`.
Relates to: #621 
> Extend return value documentation for vmware_guest_disk

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1606-vmware_guest_custom_attributes.yml
- changelogs/fragments/1610-scenario_guides.yml
- changelogs/fragments/1615-wrong_key_for_return_value.yml
- changelogs/fragments/1616-vmware_guest_disk.yml
- changelogs/fragments/1618_pylint.yml
- changelogs/fragments/1629-vmware_vmotion.yml
- changelogs/fragments/1633-missing_quotation_mark.yml
- changelogs/fragments/1637-pylint-issues.yml
- changelogs/fragments/1641_extend_result_docs_guest_disk
- docs/community.vmware.vmware_guest_disk_module.rst
- docs/community.vmware.vmware_host_module.rst
- docs/community.vmware.vmware_vm_inventory_inventory.rst
- docs/community.vmware.vmware_vmotion_module.rst
- galaxy.yml
> prepare 3.4.0 release

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1610-scenario_guides.yml
- changelogs/fragments/1615-wrong_key_for_return_value.yml
- changelogs/fragments/1618_pylint.yml
- changelogs/fragments/1638-pylint-issues.yml
- galaxy.yml
New release 2.10.4!
`ansible-playbook tools/prepare_release.yml --extra-vars "version=2.10.4"`
> prepare 2.10.4 release

- galaxy.yml
> Remove version 3.4.0 from galaxy.yml

- galaxy.yml
> Remove version 2.10.4 from galaxy.yml

- changelogs/1657-vmware_guest.yml
- plugins/module_utils/vm_device_helper.py
- plugins/modules/vmware_guest.py
Fix the issue of adding new NVDIMM device to VM by connecting to ESXi host.
Fixes #1644
vmware_guest
```paste below
```
> vmware_guest: fix adding nvdimm device issue on ESXi host

- changelogs/fragments/1223-cross_vc_clone_timeout.yml
- plugins/modules/vmware_guest_cross_vc_clone.py
- plugins/modules/vmware_vmotion.py
I've overlooked a missing `version_added`, and also a wrong changelog fragement.
vmware_guest_cross_vc_clone
vmware_vmotion
#1629 #1676
> Add missing version_added and fix changelog fragment

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/1118-vmware_migrate_vmk.yml
- changelogs/fragments/1223-cross_vc_clone_timeout.yml
- changelogs/fragments/1603-fix_tagging_performance_issue.yml
- changelogs/fragments/1614-allow_to_use_category_names_for_tag_management.yml
- changelogs/fragments/1647-uuid_vmware_tools_connections.yml
- changelogs/fragments/1653-cross_vc_clone_ssl_thumbprint.yml
- changelogs/fragments/1657-vmware_guest.yml
- changelogs/fragments/1660_truthy.yml
- changelogs/fragments/1682_vmware_vm_info
- docs/community.vmware.vmware_guest_cross_vc_clone_module.rst
- docs/community.vmware.vmware_local_role_manager_module.rst
- docs/community.vmware.vmware_vm_info_module.rst
- docs/community.vmware.vmware_vmotion_module.rst
- docs/community.vmware.vmware_vsan_hcl_db_module.rst
- galaxy.yml
> prepare 3.5.0 release

- galaxy.yml
> Remove version 3.5.0 from galaxy.yml

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/1706-vmware_vsan_health_info.yml
- changelogs/fragments/1713-vmware_guest-custom_attributes_on_create.yaml
- docs/community.vmware.vsan_health_silent_checks_module.rst
- galaxy.yml
> prepare 3.6.0 release

- galaxy.yml
> Remove version 3.6.0 from galaxy.yml

- changelogs/fragments/1742-vmware_guest_serial_port-vspc.yml
- docs/community.vmware.vmware_guest_serial_port_module.rst
- galaxy.yml
- plugins/modules/vmware_guest_serial_port.py
Fixes #1742
vmware_guest_serial_port
> vmware_guest_serial_port: add support for proxyURI parameter

- plugins/modules/vmware_guest_serial_port.py
- tests/requirements.yml
- tox.ini
Related: ansible-community/community-topics#230
> [WIP] Fix test requirements

- .github/workflows/ansible-test.yml
- .github/workflows/extra-docs-linting.yml
Backport #1747: Move some tests to GH Actions.
#1746
> stable-2.x: Backport move some tests to GH Actions

- .github/workflows/ansible-test.yml
- plugins/modules/vmware_portgroup.py
- plugins/modules/vmware_vswitch.py
Fix 2.15 sanity tests.
#1749
#1752
> Fix 2.15 sanity tests

- .github/workflows/ansible-test.yml
- plugins/modules/vmware_portgroup.py
- plugins/modules/vmware_vswitch.py
Backport #1753: Fix 2.15 sanity tests.
> Backport 1753: Fix 2.15 sanity tests

- changelogs/fragments/1710_vmware_vm_info.yaml
- plugins/modules/vmware_vm_info.py
Fixes #1709 missing parameter show_folder
vmware_vm_info
```paste below
```
> add missing show_folder

- changelogs/fragments/1764_runtime.yaml
- meta/runtime.yml
Add missing modules to `meta/runtime.yml`.
runtime.yml
#1675
#1702
#1704
#1736
> meta/runtime.yml: Add missing modules

- galaxy.yml
> Remove version 3.7.0 from galaxy.yml

- changelogs/fragments/1590_vmware_deploy_ovf.yaml
This is a follow-up PR to #1593 adding the missing changelog fragment.
> PR 1593: Add changelog fragment

- tests/sanity/ignore-2.16.txt
Ignore some sanity tests in 2.16 that haven't been fixed yet.
> Ignore some sanity tests in 2.16

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1590_vmware_deploy_ovf.yaml
- changelogs/fragments/1751-autoselect_datastore-also-use-NFS-mounts.yml
- changelogs/fragments/1765_vmware_guest_disk.yaml
- changelogs/fragments/1774_vmware_vasa.yaml
- changelogs/fragments/1774_vmware_vasa_info.yaml
- galaxy.yml
- tools/antsibull-docs-wrapper.sh
> prepare 3.8.0 release

- galaxy.yml
> Remove version 3.8.0 from galaxy.yml

- plugins/modules/vmware_dvswitch_uplink_pg.py
Fixes #1812
portproup -> portgroup
vmware_dvswitch_uplink_pg
> vmware_dvswitch_uplink_pg: Fix typo

- plugins/modules/vmware_cluster_info.py
- plugins/modules/vmware_guest_disk.py
> stable-2.x: Fix linter errors

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/1069_vmware_guest.yml
- changelogs/fragments/1777-vmware_host_datastore-resignature_vvols.yaml
- changelogs/fragments/1805_vmware_vm_info.yml
- docs/community.vmware.vmware_deploy_ovf_module.rst
- docs/community.vmware.vmware_dvswitch_uplink_pg_module.rst
- docs/community.vmware.vmware_guest_module.rst
- docs/community.vmware.vmware_host_datastore_module.rst
- galaxy.yml
> prepare 3.9.0 release

- galaxy.yml
> Remove version 3.9.0 from galaxy.yml

- README.md
- docs/community.vmware.vmware_host_graphics_module.rst
- plugins/modules/vmware_host_graphics.py
New module for setup Host Graphics Settings
vmware_host_graphics
> Vmware host graphics

- plugins/modules/vmware_guest.py
> Fix typo in Docs for vmware_guest module

- README.md
Update Readme for 4.0.0 release
README.md
Backport #1860
> 3.x: Update Readme for 4.0.0 release

- changelogs/fragments/1853.yml
- plugins/modules/vmware_deploy_ovf.py
Fix issue #1853 
Backport #1854
cc @ihumster
> 3.x: fix #1853

- changelogs/fragments/issue_1772.yml
- plugins/modules/vmware_guest_custom_attributes.py
Backport #1846
vmware_guest_custom_attributes
cc @ihumster
> 3.x: fix issue #1772

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/1847_vmware_guest_snapshot.yml
- changelogs/fragments/1853.yml
- changelogs/fragments/1855_ vmware_dsv_portgroup_info.yml
- changelogs/fragments/issue_1772.yml
- docs/community.vmware.vcenter_root_password_expiration_module.rst
- galaxy.yml
> prepare 3.10.0 release

- galaxy.yml
> Remove version 3.10.0 from galaxy.yml

- changelogs/fragments/1799_configure_snmp_on_esxii_hosts_via_vcenter.yaml
- docs/community.vmware.vmware_host_snmp_module.rst
- plugins/modules/vmware_host_snmp.py
- tests/integration/targets/vmware_host_snmp/aliases
- tests/integration/targets/vmware_host_snmp/tasks/main.yml
Configure SNMP for ESXi hosts via vCenter
Backport of #1832
> stable-3.x: Configure SNMP for ESXi hosts via vCenter

- README.md
Document that 2.x is unmaintained.
README.md
> Document 2.x as unmaintained

- README.md
Document that 2.x is unmaintained.
README.md
Backport #1884
> stable-3.x: Document 2.x as unmaintained

- plugins/doc_fragments/vmware.py
- plugins/doc_fragments/vmware_rest_client.py
Start implementing semantic markup.
plugins/doc_fragments/vmware.py
plugins/doc_fragments/vmware_rest_client.py
#1771
> Implement semantic markup (1)

- README.md
- changelogs/fragments/1472-vmware_guest.yml
- changelogs/fragments/1517_vmware_host_lockdown.yml
- changelogs/fragments/1639.yml
- changelogs/fragments/1761_vmware_vm_info.yml
- changelogs/fragments/1799_configure_snmp_on_esxii_hosts_via_vcenter.yaml
- changelogs/fragments/1847_vmware_guest_snapshot.yml
- changelogs/fragments/1853.yml
- changelogs/fragments/1855_ vmware_dsv_portgroup_info.yml
- changelogs/fragments/1855_vmware_dsv_portgroup_info.yml
- changelogs/fragments/1872-vmware_host_acceptance.yml
- changelogs/fragments/1898-vmware_rest_client.yml
- changelogs/fragments/802-vmware_deploy_ovf.yml
- changelogs/fragments/issue_1772.yml
Improve changelog fragments for 4.0.0
> Improve changelog fragments for 4.0.0

- changelogs/config.yaml
- tools/prepare_release.yml
Automatically remove changelog fragments
changelogs/config.yaml
tools/prepare_release.yml
> Automatically remove changelog fragments

- galaxy.yml
> Remove version 4.0.0 from galaxy.yml

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1799_configure_snmp_on_esxii_hosts_via_vcenter.yaml
- changelogs/fragments/802-vmware_deploy_ovf.yml
- docs/community.vmware.vmware_deploy_ovf_module.rst
- docs/community.vmware.vmware_host_snmp_module.rst
- galaxy.yml
> prepare 3.11.0 release

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/20231031-fix_3.11-release.yml
- galaxy.yml
`ansible-playbook tools/prepare_release.yml --extra-vars "version=3.11.1"`
> Prepare 3.11.1 release

- galaxy.yml
> Remove version 3.11.1 from galaxy.yml

- .github/workflows/ansible-test.yml
- tests/sanity/ignore-2.16.txt
Run GHA sanity tests against everything, not just the changed modules. Also, add sanity running tests with ansible-core 2.16.
ansible-collections/collection_template#65
> Update ansible-test GHA

- .github/workflows/ansible-test.yml
- tests/sanity/ignore-2.16.txt
Run GHA sanity tests against everything, not just the changed modules. Also, add sanity running tests with ansible-core 2.16.
ansible-collections/collection_template#65
> stable 3.x: Update ansible-test GHA

- .github/workflows/ansible-test.yml
Disable Codecov for now. I don't think it provides valuable information to us, at least not at the moment.
> Disable Codecov

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1919-vmware_vm_info.yml
- galaxy.yml
`ansible-playbook tools/prepare_release.yml --extra-vars "version=4.0.1"`
> prepare 4.0.1 release

- tests/integration/targets/vmware_about_info/tasks/main.yml
- tests/integration/targets/vmware_category/tasks/associable_obj_test.yml
- tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
- tests/integration/targets/vmware_folder_info/tasks/main.yml
- tests/integration/targets/vmware_guest_controller/tasks/main.yml
- tests/integration/targets/vmware_guest_network/tasks/main.yml
Fix integration tests.
vmware_about_info
vmware_folder_info
#1937
#1938
> Fix integration tests

- tests/integration/targets/vmware_about_info/tasks/main.yml
- tests/integration/targets/vmware_category/tasks/associable_obj_test.yml
- tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
- tests/integration/targets/vmware_folder_info/tasks/main.yml
- tests/integration/targets/vmware_guest_controller/tasks/main.yml
- tests/integration/targets/vmware_guest_network/tasks/main.yml
Fix integration tests
Backport of #1941
vmware_about_info
vmware_folder_info
> stable-3.x: Fix integration tests

- plugins/modules/vmware_category.py
Fixes #1935
Improve the documentation of the parameter `category_cardinality`.
> vmware_category: Improve documentation

- plugins/modules/vmware_category.py
Improve the documentation of the parameter `category_cardinality`.
Backport of #1938
> vmware_category: Improve documentation (#1938)

- changelogs/changelog.yaml
- changelogs/fragments/1937-vmware_guest.yml
Fix wrong changelog introduced in #1937 (sorry, I shouldn't have merged this... my fault).
vmware_guest
> Fix changelog

- testing.md
Fixed broken link to development guideline.
Because the page was deleted by  https://github.com/ansible/ansible/pull/79795 .
- `testing.md`
```paste below
N/A
```
> Fixed broken link to development guideline

- changelogs/fragments/1848-fix-vm-reconfiguration-with-enabled-vbs.yml
> Fix PR 1848 changelog

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1059-vmware_guest_tools_upgrade.yml
- changelogs/fragments/1848-fix-vm-reconfiguration-with-enabled-vbs.yml
- changelogs/fragments/1930-fix_ssl_deprecation_function.yml
- changelogs/fragments/1937-vmware_guest.yml
- changelogs/fragments/1959-vmware_guest_sendkey.yml
- changelogs/fragments/1969-InsecureRequestWarning.yml
- galaxy.yml
> Prepare 4.0.0 release

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1848-fix-vm-reconfiguration-with-enabled-vbs.yml
- changelogs/fragments/1969-InsecureRequestWarning.yml
- docs/community.vmware.vmware_category_module.rst
- docs/community.vmware.vmware_host_inventory_inventory.rst
- docs/community.vmware.vmware_vm_inventory_inventory.rst
- galaxy.yml
`ansible-playbook tools/prepare_release.yml --extra-vars "version=3.11.2"`
> Prepare 3.11.2 release

- galaxy.yml
> Remove version 4.1.0 from galaxy.yml

- galaxy.yml
> Remove version 3.11.2 from galaxy.yml

- plugins/modules/vmware_vmkernel.py
This is a follow-up PR to #1979 to add the missing `version_added`.
vmware_vmkernel
cc @Nina2244
> vmware_vmkernel: Add missing version_added

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1972-vm_inventory_subproperties.yml
- changelogs/fragments/1977-vsphere_file_add_env_fallback.yml
- changelogs/fragments/1978-vmware_vmkernel.yaml
- changelogs/fragments/1994-vmware-host-facts.yml
- changelogs/fragments/1995-vsphere_copy.yml
- changelogs/fragments/1996 - vmware_first_class_disk_info.yml
- galaxy.yml
> prepare 4.2.0 release

- galaxy.yml
> Remove version 4.2.0 from galaxy.yml

- tests/sanity/ignore-2.18.txt
Ignore some sanity tests in 2.18 that haven't been fixed yet.
> Ignore some sanity tests in 2.18

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1949-dvswitch_netflow_switch_ip.yml
- changelogs/fragments/2019-doc_fragments-case-sensitive.yml
- changelogs/fragments/2022-drop_sceanrio_guides.yml
- changelogs/fragments/2024027-fix_ci.yml
- changelogs/fragments/2033-vmware_guest_tools_info.yml
- changelogs/fragments/2036-missing_error_msg_in_vmware_guest.yml
- changelogs/fragments/2044-error_in_adding_disk_to_vm_in_vmware_guest.yml
- galaxy.yml
> prepare 4.3.0 release

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2022-drop_sceanrio_guides.yml
- changelogs/fragments/2024027-fix_ci.yml
- changelogs/fragments/2036-missing_error_msg_in_vmware_guest.yml
- changelogs/fragments/2044-error_in_adding_disk_to_vm_in_vmware_guest.yml
- galaxy.yml
`ansible-playbook tools/prepare_release.yml --extra-vars "version=3.11.3"`
> prepare 3.11.3 release

- galaxy.yml
> Remove version 4.3.0 from galaxy.yml

- galaxy.yml
> Remove version 3.11.3 from galaxy.yml

- changelogs/fragments/2057-vmware_cluster_dpm-handle-dpm-none-config.yml
- plugins/modules/vmware_cluster_dpm.py
> check if dpm config is None

- changelogs/fragments/2053-vmware_dvs_portgroup.yml
- plugins/modules/vmware_dvs_portgroup.py
> Backport vmware_dvs_portgroup: don't update on non-specified num_ports

- .github/workflows/ansible-test.yml
Prepare depending on [vmware.vmware](https://github.com/ansible-collections/vmware.vmware).
> Prepare depending on vmware.vmware

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2053-vmware_dvs_portgroup.yml
- changelogs/fragments/2055-vmware_dvs_portgroup-status_default.yml
- changelogs/fragments/2057-vmware_cluster_dpm-handle-dpm-none-config.yml
- changelogs/fragments/2071-clarify-pyvmomi-requirement.yml
- galaxy.yml
> prepare 4.4.0 release

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2053-vmware_dvs_portgroup.yml
- changelogs/fragments/2057-vmware_cluster_dpm-handle-dpm-none-config.yml
- galaxy.yml
`ansible-playbook tools/prepare_release.yml --extra-vars "version=3.11.4"`
> prepare 3.11.4 release

- galaxy.yml
> Remove version 4.4.0 from galaxy.yml

- galaxy.yml
> Remove version 3.11.4 from galaxy.yml

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2080_bugfix_hadnle_vcls_none_config.yml
- changelogs/fragments/2088_bugfix_correct_vcenter_folder_docs.yml
- changelogs/fragments/2090-vmware_host_logbundle.yml
- changelogs/fragments/2092-vmware_host_logbundle.yml
- galaxy.yml
> prepare 4.5.0 release

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2080_bugfix_hadnle_vcls_none_config.yml
- changelogs/fragments/2088_bugfix_correct_vcenter_folder_docs.yml
- docs/community.vmware.vcenter_folder_module.rst
- galaxy.yml
`ansible-playbook tools/prepare_release.yml --extra-vars "version=3.11.5"`
> Prepare 3.11.5 release

- galaxy.yml
> Remove version 4.5.0 from galaxy.yml

- changelogs/fragments/2110-vsphere_file.yml
- plugins/modules/vsphere_file.py
Fixes #2110
Follow-up to #1978 fixing the examples in the documentation.
vsphere_file
cc @rgadwagner
> vsphere_file: Fix examples

- galaxy.yml
> Remove version 3.11.5 from galaxy.yml

- README.md
Update communication section in `README.md`.
README.md
ansible-collections/collection_template#71
> README.md: Update Communication section

- README.md
Let's add the newly created forum group to the README.
README.md
#2119
ansible-collections/vmware.vmware#58
> README: Add forum group

- README.md
> stable-3.x: README.md: Update Communication section

- README.md
> stable-3.x: README.md: Update vSAN SDK link which redirects

- changelogs/fragments/2095_bugfix_vmware_guest_disk_round_size_to_int.yml
- plugins/modules/vmware_guest_disk.py
> stable-3.x: vmware_guest_disk: round size to int

- README.md
- changelogs/fragments/2127-require-requests.yml
- requirements.txt
> stable-3.x: Document requirement on requests

- README.md
> stable-3.x: README: Add forum group

- plugins/modules/vmware_vm_info.py
Fixed naming of vm_info variable for consistency.
vmware_vm_info
N/A
> Fixed naming of vm_info variable for consistency.

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2095_bugfix_vmware_guest_disk_round_size_to_int.yml
- changelogs/fragments/2127-require-requests.yml
- galaxy.yml
`ansible-playbook tools/prepare_release.yml --extra-vars "version=3.11.6"`
> prepare 3.11.6 release

- galaxy.yml
> Remove version 4.6.0 from galaxy.yml

- galaxy.yml
> Remove version 3.11.6 from galaxy.yml

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2143-deprecate-vmware_cluster.yml
- changelogs/fragments/2156-deprecate-vmware_cluster_vcls.yml
- galaxy.yml
> prepare 4.7.0 release

- galaxy.yml
> Remove version 4.7.0 from galaxy.yml

- README.md
Update Readme for 5.0.0 release
README.md
> Update Readme for 5.0.0 release

- README.md
Update Readme for 5.0.0 release
README.md
Backport #2170
> stable-4.x: Update Readme for 5.0.0 release

- changelogs/fragments/2175-drop-module_utils.vmware.run_command_in_guest.yml
- plugins/module_utils/vmware.py
It looks like we don't use `module_utils.vmware.run_command_in_guest` anywhere / anymore.
#2167
> Drop module_utils.vmware.run_command_in_guest

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1998-dvs_portgroup.yml
- changelogs/fragments/2078-vmware_guest_tools_info.yml
- changelogs/fragments/2138-vmware_all_snapshots_info.yml
- changelogs/fragments/2159-depend-on-vmware.vmware.yml
- changelogs/fragments/2174.yml
- changelogs/fragments/2175-drop-module_utils.vmware.run_command_in_guest.yml
- changelogs/fragments/5.0.0-required_ansible_version.yml
- changelogs/fragments/5.0.0-requirements.yml
- galaxy.yml
New major release 5.0.0!
`ansible-playbook tools/prepare_release.yml --extra-vars "version=5.0.0"`
> prepare 5.0.0 release

- galaxy.yml
> Remove version 5.0.0 from galaxy.yml

- changelogs/fragments/2186-fix-sanity-tests.yml
- plugins/inventory/vmware_host_inventory.py
- plugins/inventory/vmware_vm_inventory.py
- plugins/modules/vmware_dvswitch.py
- plugins/modules/vmware_dvswitch_pvlans.py
- plugins/modules/vmware_guest_tpm.py
- plugins/modules/vmware_host.py
- plugins/modules/vmware_host_dns.py
- plugins/modules/vmware_host_powerstate.py
- plugins/modules/vmware_vmotion.py
- tests/sanity/ignore-2.19.txt
Fix sanity tests.
vmware_dvswitch_pvlans
vmware_guest_tpm
vmware_host
vmware_host_dns
vmware_host_powerstate
vmware_vmotion
Backport of #2186
> stable-3.x: Fix sanity tests

- .github/workflows/extra-docs-linting.yml
- changelogs/fragments/2192-fix-documentation.yml
- plugins/connection/vmware_tools.py
- plugins/modules/vcenter_standard_key_provider.py
- plugins/modules/vmware_dvswitch_nioc.py
- plugins/modules/vmware_guest.py
- plugins/modules/vmware_guest_controller.py
- plugins/modules/vmware_guest_disk.py
- plugins/modules/vmware_guest_serial_port.py
It looks like there are some problems with the documentation (semantic markup?) that we should fix.
vmware_dvswitch_nioc
vmware_guest
vmware_guest_serial_port
vmware_tools
> Fix documentation

- galaxy.yml
> Remove version 5.0.1 from galaxy.yml

- galaxy.yml
> Remove version 4.7.1 from galaxy.yml

- galaxy.yml
> Remove version 3.11.7 from galaxy.yml

- changelogs/fragments/2194-vmware_vm_info.yml
- plugins/modules/vmware_vm_info.py
Improve the performance of retrieving custom attributes.
vmware_vm_info
Backport of #2194
cc @eddiehavila
> stable-4.x: Improve vmware_vm_info performance

- README.md
Document that 3.x is unmaintained.
README.md
> Document 3.x as unmaintained

- README.md
Backport of #2212
Document that 3.x is unmaintained.
README.md
> stable-4.x: Document 3.x as unmaintained

- README.md
Backport of #2212
Document that 3.x is unmaintained.
README.md
> stable-3.x: Document 3.x as unmaintained

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2173-fix-existing-disk-recreation-on-vm-with-8-or-more-disks.yml
- changelogs/fragments/2194-vmware_vm_info.yml
- changelogs/fragments/2208-vmware_vmotion.yml
- changelogs/fragments/2217-deprecate-vmware_cluster_dpm.yml
- changelogs/fragments/2218-deprecate-vmware_cluster_drs_recommendations.yml
- galaxy.yml
> prepare 5.1.0 release

- galaxy.yml
> Remove version 5.1.0 from galaxy.yml

- galaxy.yml
> Remove version 4.8.0 from galaxy.yml

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2173-fix-existing-disk-recreation-on-vm-with-8-or-more-disks.yml
- changelogs/fragments/2208-vmware_vmotion.yml
- galaxy.yml
`ansible-playbook tools/prepare_release.yml --extra-vars "version=3.11.8"`
BTW this is the last 3.x release.
> prepare 3.11.8 release

- galaxy.yml
> Remove version 3.11.8 from galaxy.yml

- changelogs/fragments/2010-fix-vm-hardware-version-upgrade-error-not-being-reported.yml
- plugins/modules/vmware_guest.py
> stable-4.x: Fix hardware version upgrade errors not reported

- tests/integration/targets/inventory_vmware_host_inventory/playbook/test_options.yml
Temporarily disable integration test
#2257
https://forum.ansible.com/t/11073
> Temporarily disable integration test

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2000-fix-vmware-guest-idempotency-with-dvswitch.yml
- changelogs/fragments/2009-fix-disk-add-failing-with-invalid-configuration-for-device.yml
- changelogs/fragments/2010-fix-vm-hardware-version-upgrade-error-not-being-reported.yml
- changelogs/fragments/2237-vmware_guest_tools_upgrade.yml
- changelogs/fragments/2241-vmware_guest_info-make-datacenter-property-optional.yaml
- galaxy.yml
> prepare 5.2.0 release

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2000-fix-vmware-guest-idempotency-with-dvswitch.yml
- changelogs/fragments/2009-fix-disk-add-failing-with-invalid-configuration-for-device.yml
- changelogs/fragments/2010-fix-vm-hardware-version-upgrade-error-not-being-reported.yml
- galaxy.yml
`ansible-playbook tools/prepare_release.yml --extra-vars "version=4.8.1"`
> prepare 4.8.1 release

- galaxy.yml
> Remove version 5.2.0 from galaxy.yml

- galaxy.yml
> Remove version 4.8.1 from galaxy.yml

- changelogs/fragments/2275-vm-ou-customization.yml
- plugins/modules/vmware_guest.py
Add new customization spec param
https://dp-downloads.broadcom.com/api-content/apis/API_VWSA_001/8.0U3/html/ReferenceGuides/vim.vm.customization.Identification.html
Fixes #2275 
vmware_guest
> add new spec param #2275

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2260-deprecate-vmware_cluster_info.yml
- galaxy.yml
`ansible-playbook tools/prepare_release.yml --extra-vars "version=4.8.2"`
> prepare 4.8.2 release

- galaxy.yml
> Remove version 5.3.0 from galaxy.yml

- galaxy.yml
> Remove version 4.8.2 from galaxy.yml

- .github/workflows/ansible-test.yml
Drop ubuntu-20.04 from GitHub workflow
.github/workflows/ansible-test.yml
https://forum.ansible.com/t/40187
> Drop ubuntu-20.04 from GitHub workflow

- plugins/inventory/vmware_vm_inventory.py
- scripts/inventory/vmware.py
- scripts/inventory/vmware_inventory.py
There is some Pylint disable stuff that makes problems in #2352.
However, it looks like the CI works fine without this. So I guess we can safely remove this stuff.
#2353
> Remove problematic Pylint disable

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2321-deprecate-vmware_cluster_ha.yml
- changelogs/fragments/2324-vmware_migrate_vmk.yml
- changelogs/fragments/2325-vmware_vm_vss_dvs_migrate.yml
- changelogs/fragments/2326-drop-test-lt7.yml
- changelogs/fragments/2327-drop-HAS_PYVMOMI.yml
- changelogs/fragments/2328-drop-HAS_PYVMOMI.yml
- changelogs/fragments/2332-deprecate-vmware_content_deploy_ovf_template-vmware_content_deploy_template.yml
- changelogs/fragments/2337-deprecate-vmware_host.yml
- changelogs/fragments/2340-deprecate-vcenter_folder.yml
- changelogs/fragments/2345-deprecate.vmware_content_library_manager.yml
- changelogs/fragments/2351-vmware_object_role_permission.yml
- galaxy.yml
> prepare 5.5.0 release

- galaxy.yml
> Remove version 5.5.0 from galaxy.yml

- galaxy.yml
> Remove version 4.8.3 from galaxy.yml

- changelogs/fragments/2374-vmware_object_role_permission.yml
> Fix changelog fragment

- galaxy.yml
> Remove version 5.6.0 from galaxy.yml

- galaxy.yml
> Remove version 4.8.5 from galaxy.yml

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/1719-vmotion-same_resource_pool_name.yml
- changelogs/fragments/2414-fix-pyvmomi-9.yml
- galaxy.yml
`ansible-playbook tools/prepare_release.yml --extra-vars "version=5.7.1"`
> prepare 5.7.1 release

- galaxy.yml
> Remove version 5.7.1 from galaxy.yml

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2428-vmware_vm_config_optiion.yml
- changelogs/fragments/fix-webhandle-range-check.yaml
- changelogs/fragments/fix_port_vmware_guest_file_operation.yml
- galaxy.yml
`ansible-playbook tools/prepare_release.yml --extra-vars "version=5.7.2"`
> prepare 5.7.2 release

- galaxy.yml
> Remove version 5.7.2 from galaxy.yml

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2451-vcenter_license_vcf_support.yml
- galaxy.yml
> prepare 5.8.0 release

- changelogs/fragments/2447-vmware_guest_file_operations_fix.yml
- plugins/connection/vmware_tools.py
- plugins/modules/vmware_guest_file_operation.py
Fix Issue #2447
Added conversion to the type str for replace() function.
vmware_guest_file_operation.py
> Fix Issue #2447

- galaxy.yml
> Remove version 6.0.0 from galaxy.yml

- changelogs/2487-vmware_dvs_portgroup_feature.yaml
- plugins/modules/vmware_dvs_portgroup.py
Fixes #2487 
vmware_dvs_portgroup.py
> Add portgroup_description argument_spec parameter
