- plugins/modules/vmware_guest.py
Bugfix for supplying multiple dns_suffix enties, thay are configured incorrectly.
Also when a vm is provisioned to a domain the supplied dns_suffixes are ignored.
vmware_guest
Given the following input (clone from windows template)
```yaml
vmware_guest:
...
customization:
domain: "{{ guest_domain }}"
dns_servers:
- 8.8.8.8
- 9.9.9.9
dns_suffix:
- example.com
- example2.com
```
The following DNS suffixes are configured
Expected (after this PR):
Original PR: https://github.com/ansible/ansible/pull/66987
> vmware_guest: fix dns_suffix list

- plugins/modules/vmware_vcenter_settings.py
In vcenter mail_server and mail_sender are optional and we don't use it in our company.
Additionally nobody knows how vcenter behaves internally when these params are set ;)
vmware_vcenter_settings.py
```paste below
changed: [vc-b-0.cc.qa-de-1.cloud.sap] => {
"changed": true,
"db_event_cleanup": true,
"db_event_retention": 30,
"db_max_connections": 50,
"db_task_cleanup": true,
"db_task_retention": 30,
"directory_query_limit": true,
"directory_query_limit_size": 5000,
"directory_timeout": 60,
"directory_validation": false,
"directory_validation_period": 1440,
"database": {
"event_cleanup": true,
"event_retention": 30,
"max_connections": 50,
"task_cleanup": true,
"task_retention": 30
},
"hostname": "xxxxxxxxxxxxxxxxx", …
```
> mail params are not mandatory

- plugins/modules/vmware_guest_network.py
- tests/integration/targets/vmware_guest_network/tasks/main.yml
Ensure the idempotency of the module if we try to delete a NIC two times
in a row.
See: https://github.com/ansible/ansible/pull/66993
> vmware_guest_network: idempotency with state=absent

- plugins/modules/vmware_guest_tools_upgrade.py
Clarified, that VMs will be rebooted when vmware tools are upgraded.
According to https://docs.ansible.com/ansible/latest/modules/vmware_guest_move_module.html#examples added an example how to get VM uuid
vmware_guest_tools_upgrade
Same as https://github.com/ansible/ansible/pull/67854 and https://github.com/ansible/ansible/pull/67926
```paste below
```
> Added info for reboot and example on how to get VM UUID

- plugins/modules/vmware_guest_move.py
According to https://github.com/ansible-collections/vmware/pull/20/commits/809d6e69fb385881b93d3e201954fbbf7bb60a31#r387436816
According to https://github.com/ansible-collections/vmware/pull/20/commits/809d6e69fb385881b93d3e201954fbbf7bb60a31#r387436816
vmware_guest_move
```paste below
```
> added two spaces in variable

- plugins/modules/vmware_guest_disk.py
- tests/integration/targets/vmware_guest_disk/tasks/main.yml
Not specify filename for new disk
if new disk filename is not specified, vmware esxi will set new disk
filename appending a not ever used number, so even recreate new disk with same controller number and same unit number, filename existence failure would not occur.
This change is to avoid of following issue.
```
msg:Failed to manage disks for virtual machine 'xxx' with exception : ('Cannot complete the operation because the file or folder /vmfs/volumes/yyy/xxx/xxx_1001_0.vmdk already exists'
```
lib/ansible/modules/cloud/vmware/vmware_guest_disk.py
Add function test for this commit and test PASS.
First remove one existing disk without destroy file from datastore, recreate it with same controller number and unit number, recreate would success with filename appending …
> Not specify new disk filename

- plugins/modules/vmware_vm_info.py
Create vmware_client only if user uses show_tag
plugins/modules/vmware_vm_info.py
> vmware_vm_info: Minor fix

- changelogs/fragments/66340-vmware_tag.yml
- plugins/modules/vmware_tag.py
Use category id in consideration if there are multiple tags with same
name.
Fixes: https://github.com/ansible/ansible/issues/66340
Original PR: https://github.com/ansible/ansible/pull/66459
> VMware: consider category id while handling multiple tag with same name

- changelogs/fragments/33-vmware_guest_info_list_fix.yml
- plugins/module_utils/vmware.py
- tests/integration/targets/vmware_guest_info/tasks/main.yml
Handle list items in vSphere schema while handling facts in vmware_guest_info
Fixes: https://github.com/ansible-collections/vmware/issues/33
changelogs/fragments/33-vmware_guest_info_list_fix.yml
tests/integration/targets/vmware_guest_info/tasks/main.yml
> vmware_guest_info: Handle list in guest facts

- changelogs/fragments/58-non-json-properties.yml
- plugins/inventory/vmware_vm_inventory.py
Inventory files of the following type did not work:
```yaml
plugin: community.vmware.vmware_vm_inventory
properties:
- summary  # the problems
- storage
- runtime
- network
- guest
- datastore
- config
- capability
```
That is a regression from the old vmware script in the ansible/ansible "contrib" folder.
This fixes that.
inventory
The error that above inventories would give look like:
```
$ ANSIBLE_COLLECTIONS_PATHS=../../awx/plugins/collections/ ansible-inventory -i vmware_vm_inventory.yml --list --export -vvv
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under
development. This is a rapidly changing source of code and can become unstable at …
```
> Serialize non-json type objects in hostvars

- tests/integration/targets/prepare_vmware_tests/tasks/setup_dvswitch.yml
vCenter 7.0.0 does not accept 6.0.0 anymore.
> setup_dvswitch: bump switch_version to 6.5.0

- tox.ini
No need to pull the army of dependencies of the VMware modules, if at
the end, we just need flake8.
> tox: linters env only install flake8

- tox.ini
`build-ansible-collection` uses `.tox/venv/bin/ansible-galaxy` to
prepare and push the release.
> tox: venv env should install Ansible

- galaxy.yml
Remove link to non-existing documentation from `galaxy.yml`.
galaxy.yml
Fixes #74
> Remove link to non-existing documentation

- changelogs/fragments/59_vmware_host_active_directory.yml
- plugins/modules/vmware_host_active_directory.py
Fail when there's a problem with the domain membership of a host instead of reporting a change that doesn't take place.
vmware_host_active_directory
Fixes #59
> vmware_host_active_directory: Fail for unrecoverable AD problems

- tests/integration/targets/vmware_host_service_manager/aliases
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/406
Temporarily disable `vmware_host_service_manager` tests. This until the
test-suite is fixed.
See: https://github.com/ansible-collections/vmware/issues/101
> vmware_host_service_manager: disable the test-suite

- plugins/modules/vmware_guest.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/406
Bounds for hardware version template did not include the latest versions released under the 6.7 train of vSphere. Update to include up to version 15 and update error message for versioning outside of bounds.
vmware_guest.py
> Update Hardware version to include 15 - 6.7U2

- tests/integration/targets/vmware_export_ovf/tasks/main.yml
- tests/integration/targets/vmware_guest/aliases
- tests/integration/targets/vmware_guest_disk_facts/aliases
- tests/integration/targets/vmware_guest_disk_info/aliases
- tests/integration/targets/vmware_guest_network/aliases
- tests/integration/targets/vmware_guest_powerstate/aliases
- tests/integration/targets/vmware_guest_screenshot/aliases
- tests/integration/targets/vmware_guest_sendkey/aliases
- tests/integration/targets/vmware_guest_tools_wait/aliases
This alias include all the test roles that start nested VM.
> define vcenter_1esxi_with_nested alias

- plugins/modules/vmware_dvswitch_info.py
- tests/integration/targets/vmware_dvswitch_info/aliases
- tests/integration/targets/vmware_dvswitch_info/tasks/main.yml
This PR adds a module that retrieves information about the dvswitch.
It can use this module to create reports from the jinja2 template or check the settings for dvswitch.
vmware_dvswitch_info
tested with vCenter 6.7 and 7.0
> VMware: add new vmware module vmware_dvswitch_info

- tests/integration/targets/prepare_vmware_tests/tasks/setup_attach_hosts.yml
- tests/integration/targets/prepare_vmware_tests/tasks/teardown_with_esxi.yml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/410
Our test VMs will produce some ARP traffic, if we keep the "VM Network" on vSwitch0, the VM MAC address will be visible by the external switch port.
Depending on the antispoofing policy in place, the switch may just decide to block the port.
> prepare_vmware_tests: isolate the 'VM Network'

- tests/integration/targets/vmware_guest_network/aliases
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/413
The new lighter ISO image speed up the test a lot, this should be
enough to avoid the timeout problem. For instance, here a run goes from
7.1m to 4.4m.
> re-enable vmware_guest_network test

- galaxy.yml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/401
The version is generated during the release pipeline by:
https://github.com/ansible-network/releases/tree/master/ansible_releases/cmd/generate_ansible_collection.py
> remove the version key from galaxy.yml

- tests/integration/targets/vmware_guest_tools_wait/aliases
Depends-On: https://github.com/ansible-collections/vmware/pull/90
The problem was probably caused by an L2 Antispoofing policy.
> vmware_guest_tools_wait: reenable the test

- tests/integration/targets/vmware_vm_inventory/aliases
The test creates and starts some VM. This is why it should use an ESXi
that support nested virt.
> vmware_vm_inventory: use vcenter_1esxi_with_nested alias

- changelogs/fragments/75-vmware_guest_tool_upgrade.yml
- plugins/modules/vmware_guest_tools_upgrade.py
Depends-On: https://github.com/ansible-collections/vmware/pull/108
Provide option to force upgrade VMware tools in the guest,
this useful when the VMware tools are too old and module is unable to
detect correct version of guestFamily like in the case of latest Windows.
Fixes: #75
changelogs/fragments/75-vmware_guest_tool_upgrade.yml
plugins/modules/vmware_guest_tools_upgrade.py
> Add a flag 'force_upgrade' in vmware_guest_tools_upgrade

- changelogs/fragments/113_vmware_content_deploy_ovf_template.yml
- plugins/modules/vmware_content_deploy_ovf_template.py
vmware_content_deploy_template doesn't support creating VM from OVF templates "Fixes #113" 
> vmware_content_deploy_ovf_template - create VMs from OVF templates

- requirements.txt
Ensure we don't use pyvmomi 7.0 yet since it breaks `vmware_host_capability_facts` and `vmware_host_capability_info`.
See: https://github.com/ansible-collections/vmware/issues/116
See: https://github.com/vmware/pyvmomi/issues/893
> req: pyvmomi < 7.0

- changelogs/fragments/fix-vim-legacy-version-error-vmware_host_capability_facts.yml
- plugins/modules/vmware_host_capability_facts.py
- tests/integration/targets/vmware_host_capability_facts/tasks/main.yml
Depends-On: https://github.com/ansible-collections/vmware/pull/122
When I run this module with the latest pyvmomi, I get the following error.
```
The full traceback is:
Traceback (most recent call last):
File "/root/.ansible/tmp/ansible-tmp-1586962923.432382-22973-240608536804152/AnsiballZ_vmware_host_capability_info.py", line 116, in <module>
_ansiballz_main()
File "/root/.ansible/tmp/ansible-tmp-1586962923.432382-22973-240608536804152/AnsiballZ_vmware_host_capability_info.py", line 108, in _ansiballz_main
invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
File "/root/.ansible/tmp/ansible-tmp-1586962923.432382-22973-240608536804152/AnsiballZ_vmware_host_capability_info.py", line 54, in invoke_module
runpy.run_module(mod_name='ansible_collections.community.vmware.plugins.modules.vmware …
```
> VMware: Fix errors caused by vSphere API legacy versions(vmware_host_capability_facts)

- changelogs/fragments/fix-vim-legacy-version-error-vmware_host_capability_info.yml
- plugins/modules/vmware_host_capability_info.py
- tests/integration/targets/vmware_host_capability_info/tasks/main.yml
When I run this module with the latest pyvmomi, I get the following error.
```
The full traceback is:
Traceback (most recent call last):
File "/root/.ansible/tmp/ansible-tmp-1586962923.432382-22973-240608536804152/AnsiballZ_vmware_host_capability_info.py", line 116, in <module>
_ansiballz_main()
File "/root/.ansible/tmp/ansible-tmp-1586962923.432382-22973-240608536804152/AnsiballZ_vmware_host_capability_info.py", line 108, in _ansiballz_main
invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
File "/root/.ansible/tmp/ansible-tmp-1586962923.432382-22973-240608536804152/AnsiballZ_vmware_host_capability_info.py", line 54, in invoke_module
runpy.run_module(mod_name='ansible_collections.community.vmware.plugins.modules.vmware_host_capability_info', init_globals=None, run_name='__main__', …
```
> VMware: Fix errors caused by vSphere API legacy versions

- tests/integration/targets/vmware_guest_network/aliases
When the test run on a LimeStone Cloud node, we've got a high rate
of failure. I need to investigate the problem.
Also remove the test from `zuul/vmware/govcsim`
> temporarily disable vmware_guest_network

- changelogs/fragments/vmware_vm_inventory_filter.yml
- plugins/inventory/vmware_vm_inventory.py
- tests/integration/targets/inventory_vmware_vm_inventory/playbook/test_options.yml
This PR is based upon the work of dacrystal
This PR adds functionality of filters. This will allow user to
filter down the hosts based upon jinja templating.
changelogs/fragments/vmware_vm_inventory_filter.yml
tests/integration/targets/inventory_vmware_vm_inventory/playbook/test_options.yml
> Add support for filters in inventory plugin

- changelogs/fragments/vmware_vm_inventory_compose.yml
- plugins/inventory/vmware_vm_inventory.py
- tests/integration/targets/inventory_vmware_vm_inventory/playbook/test_options.yml
This PR is based upon dacrystal work
This fix allows users to specify compose variables and groups
for the hosts in vmware_vm_inventory. Added tests and documentation.
changelogs/fragments/vmware_vm_inventory_compose.yml
tests/integration/targets/inventory_vmware_vm_inventory/playbook/test_options.yml
> Added 'compose' and 'groups' in vmware_vm_inventory

- changelogs/fragments/145-vmware_dvs_portgroup_find-integer-cast.yaml
- plugins/modules/vmware_dvs_portgroup_find.py
Attempts to fix #143. Casts `arr` as an integer in comparison.
`vmware_dvs_portgroup_find`
Solution suggested in #143.
Fixes: #141
> Cast as integer in vmware_dvs_portgroup_find

- tests/integration/targets/vmware_guest_network/aliases
This reverts commit 060cc998d7f532a5d39081b316f855d570be3304.
This should better now.
See: https://github.com/ansible-network/windmill-config/commit/6753f5fab7c0a2e3859bf43231f10fcfd6d8f77c
> Revert "temporarily disable vmware_guest_network (#131)"

- changelogs/fragments/153-vmware_guest.yml
- plugins/modules/vmware_guest.py
vmware_guest
Since vSphere 7.0 is released and new hardware 17 introduced, add this hardware version support in vmware_guest module for creating VM.
```paste below
Tested on vSphere 7.0 with hardware version 17, 15 and latest, VM created as expected.
```
> VMware: add hardware version 17 support in vmware_guest module

- changelogs/fragments/66922-vmware_guest_network.yml
- plugins/modules/vmware_guest_network.py
- tests/integration/targets/vmware_guest_network/tasks/main.yml
Depends-On: https://github.com/ansible-collections/vmware/pull/147
Current version of vmware_guest_network accepts a list with network adapters, including state, one of the states is "new" which breaks the idempotency of the module (mentioned in #63648). In my opinion it's better if the list of interfaces is handled outside the module; task with a plain loop. The networks parameter is still accepted and handled (probably) but a deprecation warning has been added. Hopefully this will keep the module from breaking for users relying on the current behavior.
Check mode and diff has been added.
The module still returns the network_data dictionary in it's current format, in addition it also returns network_info, a list of dictionaries containing the interfaces. I would also purpose to remove …
> Add check mode, diff and some new functionality to vmware_guest_network

- changelogs/fragments/110-vmware_host_logbundle_info.yml
- plugins/modules/vmware_host_logbundle_info.py
- tests/integration/targets/vmware_host_logbundle_info/aliases
- tests/integration/targets/vmware_host_logbundle_info/tasks/main.yml
Depends-On: https://github.com/ansible-collections/vmware/pull/122
This PR adds a module that fetches manifests for logbundle from ESXi.
In this module that can see the manifests available in the `vmware_host_logbundle` module.
* New Module Pull Request
vmware_host_logbundle_info
tested with vCenter6.7/ESXi6.7, vCenter7.0/ESXi7.0
> VMware: add new vmware module vmware_host_logbundle_info

- changelogs/fragments/141_Correct_doc_of_vmware_local_role_info
- plugins/modules/vmware_local_role_info.py
It seems there was a structure change of what is returned by the module. It's now a list of dict and what was the key become the value of `role_name`. I adapted the example with jinja2 filter to access the privileges list of 'Admin'.
I also adapted the type. PS: I'm not sure about that change. Maybe it should be only `type: list`…
```paste below
```
> Correct the set fact to fit the return structure

- requirements.txt
Depends-On: https://github.com/ansible-collections/vmware/pull/194
This reverts commit 5ca75cffaf8cf53fb3f99ea412bb7bfd1048360b.
Thanks to the two following changes, we can now use pyvmomi 7.0:
- 813f6c126ffd64207c5b7c8b4f8aa32f13e492f4
- 531b099bbbe57f1fbdb1868868be65e9304bb74f
> Revert "req: pyvmomi < 7.0 (#122)"

- tests/integration/targets/inventory_vmware_vm_inventory/runme.sh
Setting the exit code in a trap overrides the exit code that caused the trap to be called. If any code in the trap fails, the exit call at the end of the trap will never be reached.
`tests/integration/targets/inventory_vmware_vm_inventory/runme.sh`
> inventory_vmware_vm_inventory test - Remove exit code from trap

- plugins/modules/vmware_vc_infraprofile_info.py
Depends-On: https://github.com/ansible-collections/vmware/pull/194
The return docs for vmware_vc_infraprofile_info.py were slightly off.  This would cause them to not be displayed on the website and also to fail with the new docs schema that I'm writing.
* vmware_vc_infraprofile_info.py
```paste below
```
> Fix vmware docs

- changelogs/fragments/vmware_content_deploy_ovf_template_add_storage_provision_type.yml
- plugins/modules/vmware_content_deploy_ovf_template.py
It allows to customize storage provisioning type. Without that options server will decide to use thin, thick oreagerZeroedThick type of storage provisioning
vmware_content_deploy_ovf_template.py
http://vmware.github.io/vsphere-automation-sdk-rest/6.5/operations/com/vmware/vcenter/ovf/library_item.deploy-operation.html
http://vmware.github.io/vsphere-automation-sdk-rest/6.5/structures/com/vmware/vcenter/ovf/libraryitem/svc.resource_pool_deployment_spec-structure.html
> add storage_provisioning type into vmware_content_deploy_ovf_template.

- changelogs/fragments/183_vmware_host_facts.yml
- plugins/modules/vmware_host_facts.py
When ESXi hostsystem is poweredoff or in state which module
can not gather facts, it raises exception.
This fix handles exception and returns default values.
Fixes: #183
changelogs/fragments/183_vmware_host_facts.yml
plugins/modules/vmware_host_facts.py
> vmware_host_facts: Handle exception in fact gathering

- changelogs/fragments/166-vmware_deploy_ovf.yml
- plugins/modules/vmware_deploy_ovf.py
The vmware_deploy_ovf module does not check for the existence of a VM, so an error occurs if the VM already exists.
This PR adds vm existence check processing to the vmware_deploy_ovf module.
fixes: https://github.com/ansible-collections/vmware/issues/152
tested on vCenter/ESXi 6.7
> VMware: add vm existence check processing to vmware_deploy_ovf module

- changelogs/fragments/44957-vmware_guest.yml
- plugins/modules/vmware_guest.py
- tests/integration/targets/vmware_guest/tasks/multiple_disk_controllers_d1_c1_f0.yml
Fixes #44957
vmware_guest
In "disk" parameter part, add 3 attributes, "controller_type", "controller_number", "unit_number", used for creating a new VM or reconfigure existing VM with multiple types of disk controllers and disks.
```paste below
```
> vmware_guest: add support for SATA and NVME disk controller types

- changelogs/fragments/7052_awx_handle_binary.yml
- plugins/inventory/vmware_vm_inventory.py
- tests/integration/targets/inventory_vmware_vm_inventory/playbook/test_options.yml
VM property like 'vmxConfigChecksum' is Base64Binary. Parsing this
value directly using `to_text` raises `TemplateErrors`.
First encode such values to Base64 and then process further.
Partially fixes https://github.com/ansible/awx/issues/7052
changelogs/fragments/7052_awx_handle_binary.yml
tests/integration/targets/inventory_vmware_vm_inventory/playbook/test_options.yml
> vmware_vm_inventory: Handle binary data in VM properties

- tests/integration/targets/prepare_vmware_tests/tasks/init_real_lab.yml
- tests/integration/targets/prepare_vmware_tests/tasks/setup_category.yml
- tests/integration/targets/vmware_category/aliases
- tests/integration/targets/vmware_cluster_facts/tasks/main.yml
- tests/integration/targets/vmware_cluster_info/tasks/main.yml
- tests/integration/targets/vmware_tag/aliases
- tests/integration/targets/vmware_tag_info/aliases
- tests/integration/targets/vmware_tag_manager/aliases
This reverts commit ba89d6adb2b536c61fa03fef150f0c186feaa6c5.
We should not need this anymore.
> Revert "Temporarily disable Tag and Category tests"

- changelogs/fragments/197_vmware_category.yml
- plugins/modules/vmware_category.py
- tests/integration/targets/vmware_category/tasks/associable_obj_test.yml
- tests/integration/targets/vmware_category/tasks/associable_obj_types.yml
vCenter uses different resource types for VMware objects.
This fix corrects the resource types.
Fixes: #197
changelogs/fragments/197_vmware_category.yml
plugins/modules/vmware_category.py
> vmware_category: Fix associable datatypes

- tests/integration/targets/vmware_category/tasks/associable_obj_types.yml
`set_facts` become `set_fact`.
> vmware_category: fix a typo in test-suite

- tests/integration/cloud-config-vcenter.ini.sample
- tests/integration/targets/prepare_vmware_tests/defaults/main.yml
- tests/integration/targets/prepare_vmware_tests/tasks/init_vcsim_with_container.yml
- tests/integration/targets/prepare_vmware_tests/tasks/init_vcsim_with_systemd.yml
- tests/integration/targets/prepare_vmware_tests/tasks/main.yml
- tests/integration/targets/vmware_vmotion/aliases
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/524
Add the ability to run `govcsim` with `systemd-run`.
> test: add ability to run govcsim with systemd-run

- plugins/modules/vmware_category.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/524
Depends-On: https://github.com/ansible-collections/vmware/pull/231
`elements` key should be a `string` instance, not a `type` object. We face the problem since https://github.com/ansible/ansible/pull/57145.
Otherwise, we hit the following error:
```
The full traceback is:
File "/tmp/ansible_vmware_category_payload_w4g0m32x/ansible_vmware_category_payload.zip/ansible/module_utils/basic.py", line 1775, in _handle_elements
validated_params.append(type_checker(value, **kwargs))
fatal: [testhost]: FAILED! => {
"changed": false,
"associable_object_types": [
"Folder"
],
"category_cardinality": "multiple",
"category_description": "Folder",
"category_name": "Folder",
"hostname": "vcenter.test", …
```
> vmware_category: arguments_spec, elemetns as str

- changelogs/fragments/vmware_dvs_portgroup_info_key.yaml
- plugins/modules/vmware_dvs_portgroup_info.py
- tests/integration/targets/vmware_dvs_portgroup_info/tasks/main.yml
Depends-On: https://github.com/ansible-collections/vmware/pull/231
Include the value of the Portgroup `key` in the result.
> vmware_dvs_portgroup_info: show the key value

- changelogs/fragments/219-vmware_content_deploy_template_added_param_content_library.yml
- plugins/modules/vmware_content_deploy_template.py
Depends-On: https://github.com/ansible-collections/vmware/pull/231
Added the param content_library to the main function. The value of content library is not getting captured currently. This will fix it.
vmware_content_deploy_template.py
No change in the output
> VMware: Added param content library in definition main

- meta/runtime.yml
Depends-On: https://github.com/ansible-collections/vmware/pull/231
This field isn't being added for Ansible 2.10
> Remove action_groups_redirection from meta/runtime.yml

- changelogs/fragments/vmware_dvswitch_uuid.yaml
- plugins/modules/vmware_dvswitch.py
- plugins/modules/vmware_dvswitch_info.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/527
`vmware_dvswitch` and `vmware_dvswitch_info` now collect the `UUID` of the switch.
The switch UUID is an important information for those who use the vSphere REST API.
> dvswitch: collect the UUID

- plugins/modules/vmware_tag_manager.py
Fixes #217 Added Datastore to the list of choices and copied pre-existing logic to apply datastore tags.  Used find_data_store_by_name to locate the datastore in vCenter.
A working example using the library:
```yaml
TASK [tkg-platform-storage : apply storage class tags to datastores] *********************************************************
task path: /root/project-ivy/roles/tkg-platform-storage/tasks/vmware.yml:43
ok: [localhost] => (item=[{'name': 'bronze', 'datastores': ['vmw_nfs_q01lp', 'vmw_nfs_q02lp']}, 'vmw_nfs_q01lp']) => {"ansible_loop_var": "item", "changed": false, "item": [{"datastores": ["vmw_nfs_q01lp", "vmw_nfs_q02lp"], "name": "bronze"}, "vmw_nfs_q01lp"], "tag_status": {"current_tags": ["bronze", "Performance-Silver"], …
```
> Added datastore managed object in vmware tag manager

- changelogs/fragments/55653-vmware_guest_powerstate.yml
- plugins/modules/vmware_guest.py
- tests/integration/targets/vmware_guest/tasks/check_mode.yml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/539
Added 'powered-on', 'powered-off', 'shutdown-guest', 'reboot-guest' state
values in vmware_guest module in order to match vmware_guest_powerstate module.
Fixes: https://github.com/ansible/ansible/issues/55653
Original PR: https://github.com/ansible/ansible/pull/66706
> VMware: Match state param in vmware_guest and vmware_guest_powerstate

- tests/integration/targets/prepare_vmware_tests/tasks/init_vcsim_with_systemd.yml
Call `systemd-run` with the full path of the `vcsim` binary. Our CI uses
`/usr/local/bin` and the directory in now necessary in `$PATH` by
default.
> vcsim/systemd: use the full path to vcsim

- changelogs/fragments/225-vmware_vcenter_settings.yml
- plugins/modules/vmware_vcenter_settings.py
- tests/integration/targets/vmware_vcenter_settings/aliases
- tests/integration/targets/vmware_vcenter_settings/tasks/main.yml
Depends-On: https://github.com/ansible-collections/vmware/pull/226
When runtime_settings parameter not defined or some parameters not set in runtime_settings, fix to be set default parameters for runtime_settings to runtime_settings parameters.
fixes: https://github.com/ansible/ansible/issues/66713
Original PR: https://github.com/ansible/ansible/pull/67670
tested on vCenter 6.7
> VMware: Fix to be set default parameter for runtime_settings to runtime_settings

- plugins/modules/vmware_dvswitch_info.py
Fix the wronged module names in EXAMPLES block of the vmware_dvswitch_info module.
modules/vmware_dvswitch_info.py
> VMware: Fix the wronged module names in EXAMPLES block

- changelogs/fragments/253-inventory_hostnames_fail_message.yml
- plugins/inventory/vmware_vm_inventory.py
This gives more detail when parsing failed for debugging.
A null hostname is not accepted by Ansible.
So the decision for the inventory plugin is that it should either error when no template for hostname is successful, or omit those hosts. Omitting them would be bad, and wouldn't solve the problem of figuring out how to fix it.
Previously, these situations hit this error:
```
[WARNING]:  * Failed to parse /Users/alancoding/Documents/repos/ansible-inventory-file-examples/private/vmware/aka.vmware.yaml with auto plugin: Invalid empty host name provided:
None
File "/Users/alancoding/Documents/repos/ansible/lib/ansible/inventory/manager.py", line 289, in parse_source
plugin.parse(self._inventory, self._loader, source, cache=cache) …
```
> Fail early with more info when all templates failed

- plugins/modules/vmware_content_deploy_ovf_template.py
Import `vmware_rest_client` and `vmware` from within the collection,
not the one from ansible core.
No changelog because the problem was not part of any official release.
> vmware_content_deploy_ovf_template: fix import

- changelogs/fragments/269_vmware_vm_inventory.yml
- plugins/inventory/vmware_vm_inventory.py
ESXi does not have CustomFieldManager (available in vCenter),
handle such condition.
Fixes: #269
changelogs/fragments/269_vmware_vm_inventory.yml
> vmware_vm_inventory: Handle CustomFieldManger in ESXi

- meta/runtime.yml
- plugins/modules/vmware_host_sriov.py
- tests/integration/targets/vmware_host_sriov/aliases
- tests/integration/targets/vmware_host_sriov/tasks/main.yml
- tests/unit/modules/cloud/vmware/test_vmware_host_sriov.py
Add a new module for changing SR-IOV settings on host interface
* This module can be used to configure, enable/disable SR-IOV functions an ESXi host.
* module didn't reboot host after changes, but put in output "rebootRequired" key from vCenter status
* tested on VMware 6.0
plugins/modules/vmware_host_sriov.py
tests/integration/targets/vmware_host_sriov/aliases
tests/integration/targets/vmware_host_sriov/tasks/main.yml
tests/unit/modules/cloud/vmware/test_vmware_host_sriov.py
> VMware: New module vmware_host_sriov

- plugins/modules/vmware_object_rename.py
- tests/integration/targets/vmware_object_rename/aliases
- tests/integration/targets/vmware_object_rename/tasks/dc_rename.yml
- tests/integration/targets/vmware_object_rename/tasks/main.yml
This module allows user to rename various VMware objects using
name or moid.
Fixes: #62954 #47427
Original PR: https://github.com/ansible/ansible/pull/65902
lib/ansible/modules/cloud/vmware/vmware_object_rename.py
test/integration/targets/vmware_object_rename/aliases
test/integration/targets/vmware_object_rename/tasks/main.yml
test/integration/targets/vmware_object_rename/tasks/vm_rename.yml
> VMware: new module vmware_object_rename (Attempt II)

- plugins/modules/vcenter_license.py
I updated the code to allow an esxi licence key to be added in the vCenter inventory without being assigned to an esxi if the optional parameter esxi_hostname is not provided.
The previous code was assuming that if esxi_hostname was not provided then it must be a vCenter licence key. (not always true)
This will allow to pre-provision licence keys during vCSA build for example and later on to use them during esxi build/configuration.
The change is fully backward compatible.
Tested with vCSA 6.5 but should work fine with 6.7/7.0 as only the logic has changed - not the api request.
_This is my first public PR on github - so please let me know if I missed something_
> Refactor how esxi licence keys are added

- meta/runtime.yml
- plugins/modules/vmware_dns_config.py
- tests/sanity/ignore-2.10.txt
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/593
* vmware_dns_config
plugins/modules/vmware_dns_config.py
> sanity: Fixed docs

- README.md
This PR is to add requirement the pyvmomi version to README.  
The VMware modules occurs an error of the `templateOf` if using pyvmomi 6.7.1 or less.
see: https://github.com/ansible-collections/vmware/issues/288
So, I think it is better to add pyvmomi support version to README.
README.md
> Add the pyvmomi support version for VMware modules to README

- changelogs/fragments/pvlan-config-vmware-dvs-portgroup.yml
- plugins/modules/vmware_dvs_portgroup.py
- tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
Depends-On: https://github.com/ansible-collections/vmware/pull/250
Added support for creating a distributed port group with a private VLAN.
plugins/modules/vmware_dvs_portgroup.py
Tested on vSphere 6.7
> Added private vlan configuration in vmware_dvs_portgroup

- changelogs/fragments/124-vmware-migrate-vmk-to-std-switch.yaml
- plugins/modules/vmware_migrate_vmk.py
Edited the funtion state_migrate_vds_vss which returns the message "Currently Not Implemented" to allow migration from a VMware vSphere Distrubuted Switch to a ESXi Standard Switch
- Create a portgroup on the named destination standard vSwitch "migrate_switch_name"
- Update the ESXi host network settings
- Create a VirtualNic (vmk) in edit mode on the portgroup (above) to allow a migration to happen
- Update the ESXi host network settings - causing the migration to start
> Add feature migrate from Distributed Switch to Standard Switch

- changelogs/fragments/52-vmware_dvs_portgroup_find_fix.yml
Adjust the fragment of 5f13a14f7005633d2ad0f6988e501bf8951b6373 to
be sure it starts with the module name.
> prefix fragment with module name

- plugins/modules/vmware_vcenter_settings_info.py
This PR is to fix typo and add the example of the using vSphere API output schema to the vmware_vcenter_settings_info module.
plugins/modules/vmware_vcenter_settings_info.py
> Fix typo and add the example of the using vSphere API output schema

- .github/BOTMETA.yml
- .github/settings.yml
Add BOTMETA and .github folder, needed to be able to run ansibullbot against collection.
.github/BOTMETA.yml
.github/settings.yml
I've copied this over from what was in ansible/ansible, assuming nothing should have changed since then,
> Add BOTMETA and .github folder

- changelogs/fragments/cdrom_dict_removal.yml
- plugins/modules/vmware_guest.py
CDROM configuration by specifying dict is not recommended.
Since it does not supported options supported by list.
Fixes: #48
Fixes: #308
changelogs/fragments/cdrom_dict_removal.yml
> vmware_guest: Deprecate CDROM config as dict

- changelogs/fragments/260-vmware_cluster_vsan.yml
- plugins/modules/vmware_cluster_vsan.py
- tests/integration/targets/vmware_cluster_vsan/aliases
- tests/integration/targets/vmware_cluster_vsan/tasks/main.yml
Depends-On: https://github.com/ansible-collections/vmware/pull/250
While configuring vsan clusters, setting the advanced parameters for the vsan service (Object repair timer, Thin Swap, Large Cluster Support etc.) should be possible.
Fixes #260 
Unfortunately, this PR introduces a dependecy on the SAN Management vSDK for Python. On the other hand, using ReconfigureComputeResource_Task to configure VSAN [is deprecated](https://vdc-download.vmware.com/vmwb-repository/dcr-public/b525fb12-61bb-4ede-b9e3-c4a1f8171510/99ba073a-60e9-4933-8690-149860ce8754/doc/vim.cluster.VsanVcClusterConfigSystem.html#reconfigureEx) so we would need this SDK anyway sooner or later.
_edit:_ vmware/pyvmomi#909
> Add advanced options to vmware_cluster_vsan

- .github/BOTMETA.yml
Fix connection plugin macro in BOTMETA
I didn't actually define a connection macro, and also used a bad macro for one of the connection plugins.
.github/BOTMETA.yml
Today I figured out how to test BOTMETA changes locally, so now I know this one actually works instead of just looking mostly right!  Issue 272 will likely need a bot_skip, the bot breaks on that one (in dry-run) and I haven't dug into why yet (maybe needs template?).
> Fix connection plugin macro in BOTMETA

- changelogs/fragments/286-vmware_cluster_ha.yml
- plugins/module_utils/vmware.py
- plugins/modules/vmware_cluster_ha.py
- tests/integration/targets/vmware_cluster_ha/tasks/main.yml
- tests/integration/targets/vmware_host_config_manager/tasks/main.yml
At the moment, advanced HA options that are truthy like `true` or `off` are treated as booleans although the vSphere API expects strings.
Fixes #286 
> vmware_cluster_ha: Truthy strings as strings instead of booleans

- changelogs/fragments/364-vmware_vmkernel-replciation-fix.yml
- plugins/modules/vmware_vmkernel.py
Fixes #362 
Module: vmware_vmkernel
Logic to detect if Replication and Replication NFC are enabled on a VMK is not idempotent. The code checks for provisioning service instead of replication and replication NFC.
```paste below
```
> Fix Repl and Repl_NFC detection

- changelogs/fragments/163-vmware_content_deploy_ovf_template.py.yml
- plugins/modules/vmware_content_deploy_ovf_template.py
Fixes #163 vmware_content_deploy_ovf_template - requires the resource_pool param
vmware_content_deploy_ovf_template 
There is the issue https://github.com/ansible-collections/vmware/issues/163 that vmware_content_deploy_ovf_template  doesn't work without specified resource pool. However, According the vmware [documentation](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/1cd28284-3b72-4885-9e31-d1c6d9e26686/71ef7304-a6c9-43b3-a3cd-868b2c236c81/doc/operations/com/vmware/vcenter/ovf/library_item.deploy-operation.html) it has to be specified
```
identifier of the resource pool to which the virtual machine or virtual appliance should be attached.
When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: …
```
> vmware_content_deploy_ovf_template - requires the resource_pool param

- changelogs/fragments/363-vmware_content_deploy_ovf_template.yml
- plugins/module_utils/vmware_rest_client.py
- plugins/modules/vmware_content_deploy_ovf_template.py
Fixed issue where the wrong resource identifier was returned in environments where the same resource pool name exists across multiple clusters in a data center
vmware_rest_client
The get_resource_pool_by_name doesn't include cluster or host in the filter spec and as a result will always return the identifier of the first resource pool with the same name
> fixed issue where wrong resource pool identifier was returned

- plugins/inventory/vmware_vm_inventory.py
- scripts/inventory/vmware.py
- scripts/inventory/vmware_inventory.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/635
We ignore some `too-complex` errors. Most of them are in legacy inventory
scripts, so it's not really important.
One remains in scripts/inventory/vmware.py, but the code is rather clear
and complexity is not that high.
> pylint: ensure the check pass

- plugins/modules/vmware_cluster.py
Depends-On: https://github.com/ansible-collections/vmware/pull/374
vmware_cluster ignores an exception (vim.fault.DuplicateName) which is never a good idea:
https://github.com/ansible-collections/vmware/blob/aee551dc1d1f8a57f58f2da47bef7678b2461973/plugins/modules/vmware_cluster.py#L414-L416
vmware_cluster
Fixes #375
> vmware_cluster: Don't ignore vim.fault.DuplicateName exception

- changelogs/fragments/380-vmware-handle-special-characters.yml
- plugins/module_utils/vmware.py
- tests/integration/targets/vmware_cluster/tasks/main.yml
- tests/integration/targets/vmware_datacenter/tasks/main.yml
- tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
- tests/integration/targets/vmware_dvswitch/tasks/main.yml
- tests/integration/targets/vmware_guest/defaults/main.yml
- tests/integration/targets/vmware_guest/tasks/create_vm_using_special_characters.yml
- tests/integration/targets/vmware_portgroup/tasks/main.yml
- tests/integration/targets/vmware_vswitch/tasks/main.yml
This PR is to fix to support special characters(`/\%`) in an object name.  
The VMware module could create objects with special characters, but could not delete them because it did not perform URL decoding.  
This patch is to modify for comparing an object name with special characters, not URL encoded characters.
But regarding a folder object is not eligible for this patch because it is created with URL-encoded characters because of the specification of vSphere.
related comment: https://github.com/ansible-collections/vmware/pull/366#issuecomment-683956072
> Support special characters in an object name

- changelogs/fragments/vmware_vm_inventory_req.yml
- plugins/inventory/vmware_vm_inventory.py
vCloud Suite SDK dependency was
removed in https://github.com/ansible/ansible/pull/55804
Update documentation for this change.
changelogs/fragments/vmware_vm_inventory_req.yml
> vmware_vm_inventory: correct docs for requirements

- changelogs/fragments/335-vmware-strip-names-when-searching.yml
- plugins/module_utils/vmware.py
There is a problem when searching for vSphere objects when they have leading or trailing whitespace. For example, searching for 'Cluster-01 ' (with a trailing space) fails because vCenter will return 'Cluster-01' (without a trailing space) but module_utils.py compares the name literally. And 'Cluster-01 ' != 'Cluster-01'.
vmware
Fixes #335
> Ignore leading and trailing whitespace when searching for objects

- README.md
- tox.ini
Depends-On: https://github.com/ansible-collections/vmware/pull/374
Add a tox enviromment to run `add_docs.py`, this way we don't have
to manually create the virtualenv anymore.
> tox: add add_docs environment

- changelogs/fragments/403_fix_vmware_guest_info.yml
- plugins/modules/vmware_guest_info.py
- tests/integration/targets/vmware_tag/tasks/tag_manager_ops.yml
Fixes: #403
plugins/modules/vmware_guest_info.py
tests/integration/targets/vmware_tag/tasks/tag_manager_ops.yml
> vmware_guest_info: Fix get tags API call

- changelogs/fragments/402-vmware_host_iscsi_info.yml
- plugins/modules/vmware_host_iscsi_info.py
- tests/integration/targets/vmware_host_iscsi_info/aliases
- tests/integration/targets/vmware_host_iscsi_info/tasks/iscsi_info_module_test_tasks.yml
- tests/integration/targets/vmware_host_iscsi_info/tasks/main.yml
This PR adds a new module vmware_host_iscsi_info.
related comment: https://github.com/ansible-collections/community.vmware/pull/224#discussion_r440894859
plugins/modules/vmware_host_iscsi_info.py
tested on vSphere 6.7
> add a new module vmware_host_iscsi_info

- changelogs/fragments/401-vmware_guest_network.yml
- plugins/modules/vmware_guest_network.py
- tests/integration/targets/vmware_guest_network/tasks/main.yml
Fix to port group changes to work properly.  
The vmware_guest_network module has been an error that occurs or can't change the port group when changing the port group.  
The cause of the error is each object type didn't compare well, wronged object structure.  
This PR is to fix that bug.  
And NSX-T port group supported.
fixes: https://github.com/ansible-collections/community.vmware/issues/88 https://github.com/ansible-collections/community.vmware/issues/204 https://github.com/ansible-collections/community.vmware/issues/339 https://github.com/ansible-collections/community.vmware/issues/352
plugins/modules/vmware_guest_network.py
tested on vCenter/ESXi 7.0/6.7 and NSX-T 3.0
> vmware_guest_network: Fix to port group changes to work properly

- changelogs/fragments/412-vmware_guest_custom_attributes.yml
- plugins/modules/vmware_guest_custom_attributes.py
When running a task with `vmware_guest_custom_attributes`, if the name of any attribute already exists as a HostSystem attribute, the module will crash with an unhandled exception.
Fixes #412 
vmware_guest_custom_attributes
When there are two custom attributes named `foo`, one for VMs and one for ESXi hosts, the module might try to set the host custom attribute on the VM and crash.
> Fix issue with duplicate custom attribute names

- changelogs/fragments/408_video_facts.yml
- plugins/modules/vmware_guest_video.py
Facts about video devices can be gathered for poweredoff VM.
Fixes: #408
changelogs/fragments/408_video_facts.yml
plugins/modules/vmware_guest_video.py
> vmware_guest_video: Gather facts for poweredoff VM

- changelogs/fragments/404_vmware_guest_sendkey.yml
- plugins/modules/vmware_guest_sendkey.py
API is faster than the keys/strings send to VM.
Adding sleep in between will help.
Fixes: #404
changelogs/fragments/404_vmware_guest_sendkey.yml
plugins/modules/vmware_guest_sendkey.py
> vmware_guest_sendkey: Add sleep_time parameter

- plugins/modules/vca_fw.py
- plugins/modules/vca_nat.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/674
Don't use the Full Qualified fragment name, this way we can run
`add_docs` even if if the collection is not installed.
Otherwise backtrace starting in `ansible/utils/plugin_docs.py`will
be raised.
> vca_*: use relative doc fragment name

- changelogs/fragments/426_vmware_object_role_permission.yml
- plugins/modules/vmware_object_role_permission.py
Examples missing required fields of hostname, username, and password, while other module examples include these.
Fixes #426 
Follo-up to PR #422
> vmware_object_role_permission: Missing required parameters in examples

- changelogs/fragments/430_vmware_tag_manager.yml
- plugins/modules/vmware_folder_info.py
- plugins/modules/vmware_tag_manager.py
- plugins/modules/vmware_vm_info.py
- tests/integration/targets/vmware_folder_info/tasks/main.yml
- tests/integration/targets/vmware_tag_manager/tasks/main.yml
- tests/integration/targets/vmware_tag_manager/tasks/tag_manager_dict.yml
Users can now specify 'moid' of VMware object to identify
objects uniquely.
Fixes: #430
changelogs/fragments/430_vmware_tag_manager.yml
plugins/modules/vmware_folder_info.py
plugins/modules/vmware_tag_manager.py
plugins/modules/vmware_vm_info.py
tests/integration/targets/vmware_folder_info/tasks/main.yml
tests/integration/targets/vmware_tag_manager/tasks/main.yml
tests/integration/targets/vmware_tag_manager/tasks/tag_manager_dict.yml
> vmware_tag_manager: Add new parameter 'moid'

- changelogs/fragments/461_vmware_resource_pool.yml
- plugins/modules/vmware_resource_pool.py
- tests/integration/targets/vmware_resource_pool/tasks/main.yml
This PR is to add new allocation shares options for cpu and memory to the vmware_resource_pool module.
fixes: https://github.com/ansible-collections/community.vmware/issues/444
plugins/modules/vmware_resource_pool.py
tests/integration/targets/vmware_resource_pool/tasks/main.yml
> vmware_resource_pool: Add new allocation shares options for cpu and memory

- changelogs/fragments/vmware_guest_info.yml
- plugins/modules/vmware_guest_info.py
- tests/integration/targets/vmware_tag/tasks/tag_manager_ops.yml
vmware_guest_info returns tag information as a list of tag names.
With the new parameter 'tag_details', module returns detailed
information about tags and categories related to the given virtual machine.
This change is backward compatible and makes tag facts uniform across
all VMware modules.
changelogs/fragments/vmware_guest_info.yml
plugins/modules/vmware_guest_info.py
tests/integration/targets/vmware_tag/tasks/tag_manager_ops.yml
> vmware_guest_info: Add a new parameter to gather tag info

- changelogs/fragments/469_vmware_resource_pool.yml
- plugins/modules/vmware_resource_pool.py
- tests/integration/targets/vmware_resource_pool/aliases
- tests/integration/targets/vmware_resource_pool/tasks/main.yml
The vmware_resource_pool module hasn't had a config changing feature, so this PR adds it to the module.
The return key was written as `instance` in the RETURN block, but not defined in the module.  
So I changed the return key from `instance` to `resource_pool_config`.
The govcsim wasn't supported to change the expandableReservation, so I removed the govcsim from the alias file.  
The integration test for this module executes on vcenter_1esxi.
fixes: https://github.com/ansible-collections/community.vmware/issues/467
plugins/modules/vmware_resource_pool.py
tests/integration/targets/vmware_resource_pool/tasks/main.yml
tests/integration/targets/vmware_resource_pool/aliases
> vmware_resource_pool: add a config changing feature

- changelogs/fragments/460_module_utils_vmware.yml
- plugins/module_utils/vmware.py
- tests/integration/targets/vmware_guest/tasks/network_with_dvpg.yml
- tests/integration/targets/vmware_guest/tasks/network_with_portgroup.yml
This PR is to fix the find_obj method can URL decode of special characters.  
By this cause, the vmware_guest module hasn't available the special characters in a portgroup name
fixes: https://github.com/ansible-collections/community.vmware/issues/457
tests/integration/targets/vmware_guest/tasks/network_with_dvpg.yml
tests/integration/targets/vmware_guest/tasks/network_with_portgroup.yml
> Fix the special characters aren't decoded by the find_obj method

- changelogs/fragments/vmware_deploy_ovf.yml
- plugins/module_utils/vmware.py
- plugins/modules/vmware_deploy_ovf.py
Fixes an issue with vmware_deploy_ovf module throwing an error in cases when several datacenters have network(s) defined in mapping.
> vmware_deploy_ovf: support for networks with the same names in different datacenters

- changelogs/fragments/350_vmware_vm_inventory.yml
- plugins/inventory/vmware_vm_inventory.py
- tests/integration/targets/inventory_vmware_vm_inventory/playbook/test_options.yml
Now, vmware_vm_category can retrive categories and
related to tags.
Fixes: #350
changelogs/fragments/350_vmware_vm_inventory.yml
tests/integration/targets/inventory_vmware_vm_inventory/playbook/test_options.yml
> vmware_vm_inventory: Add support for category

- changelogs/fragments/454_vmware_category.yml
- plugins/modules/vmware_category.py
Following associable types
* Network - 'Network', 'HostNetwork', 'OpaqueNetwork'
* Distributed switch - 'VmwareDistributedVirtualSwitch', 'DistributedVirtualSwitch'
Fixes: #454
changelogs/fragments/454_vmware_category.yml
plugins/modules/vmware_category.py
> vmware_category: Add addition associable types

- changelogs/fragments/482_vmware_resource_pool.yml
- plugins/modules/vmware_resource_pool.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/703
The vmware_resource_pool module has a bug that always updates the resource pool config.  
The result of the module is to display not changed when using the same resource pool config, but change event occurs on vCenter.  
This PR is to fix the above bug.
plugins/modules/vmware_resource_pool.py
> vmware_resource_pool: fix a bug that always updates the resource pool config

- README.md
- docs/community.vmware.vmware_host_scsidisk_info_module.rst
- plugins/modules/vmware_host_scsidisk_info.py
- tests/integration/targets/vmware_host_scsidisk_info/aliases
- tests/integration/targets/vmware_host_scsidisk_info/tasks/main.yml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/703
Module to gather information about SCSI disks attached to
ESXi
README.md
docs/community.vmware.vmware_host_scsidisk_info_module.rst
plugins/modules/vmware_host_scsidisk_info.py
tests/integration/targets/vmware_host_scsidisk_info/aliases
tests/integration/targets/vmware_host_scsidisk_info/tasks/main.yml
> vmware_host_scsidisk_info: new module

- changelogs/fragments/489_vmware_vm_inventory_port_cast_integer.yaml
- plugins/inventory/vmware_vm_inventory.py
This patch ensure the `VMWARE_PORT` environment variable is an integer to avoid traceback mentioned on issue #448 
Fixes: #488
```diff
(awx) [root@rh-tower-latest inventory]# diff -ruN vmware_vm_inventory.py-latest-collection vmware_vm_inventory.py 
--- vmware_vm_inventory.py-latest-collection	2020-11-09 14:28:36.940432717 -0500
+++ vmware_vm_inventory.py	2020-11-09 16:46:32.978181736 -0500
@@ -343,7 +343,7 @@
self.hostname = hostname
self.username = username
self.password = password
-        self.port = port
+        self.port = int(port)
self.with_tags = with_tags
self.validate_certs = validate_certs
self.content = None
```
**Ansible Tower ENV**
```json
(ansible) [root@rh-tower-latest ~]# curl -u admin -k -L …
```
> vmware_vm_inventory: Ensure self.port is integer

- changelogs/fragments/499-vmware_deploy_ovf.yml
- plugins/modules/vmware_deploy_ovf.py
The vmware_deploy_ovf module occurs the name variable referenced error when the check mode.  
This PR is to fix the above issue.
fixes: https://github.com/ansible-collections/community.vmware/issues/497
> vmware_deploy_ovf: Fix the issue that the name variable referenced error occurs

- changelogs/fragments/inventory_fix.yml
- plugins/inventory/vmware_vm_inventory.py
Some VM configurations are in 'inaccessible' state, skip
over these kind of VMs.
changelogs/fragments/inventory_fix.yml
> vmware_vm_inventory: Skip inaccessible VM configuration

- changelogs/fragments/81_vmware_drs_group.yml
- plugins/modules/vmware_drs_group.py
code refactor
changelogs/fragments/81_vmware_drs_group.yml
plugins/modules/vmware_drs_group.py
> vmware_drs_group: code refactor

- changelogs/fragments/507-vmware_guest_fix-documentation.yml
- plugins/modules/vmware_guest.py
The `networks` parameter is missing two sub parameters in the document section.
Fixes #507
vmware_guest
> vmware_guest: Document networks connected and start_connected sub-options

- changelogs/fragments/492-vmware_resource_pool-esxi_host.yml
- plugins/modules/vmware_resource_pool.py
When creating a resource pool using module `vmware_resource_pool` it should not be required to specify cluster when instead an esxi-host is specified (e.g. `esxi_hostname: foobarhost`).
Fixes #492 
vmware_resource_pool
> vmware_resource_pool: Manage resource pools on ESXi hosts

- changelogs/fragments/514_vmware_content_deploy_ovf_template-add_content_library_parameter.yml
- plugins/modules/vmware_content_deploy_ovf_template.py
This PR adds a parameter `content_library` to `vmware_content_deploy_ovf_template` to specify the content library to deploy the OVF from. This is equivalent to the `content_library` parameter of `vmware_content_deploy_template`.
Fixes #514
> vmware_content_deploy_ovf_template: Add content_library parameter

- changelogs/fragments/436_vmware_object_role_permission.yml
- plugins/modules/vmware_object_role_permission.py
User can now specify role names from the web UI while using
vmware_object_role_permission module.
Fixes: #436
changelogs/fragments/436_vmware_object_role_permission.yml
plugins/modules/vmware_object_role_permission.py
> vmware_object_role_permission: allow role names from web UI

- CHANGELOG.rst
This minor release adjust the content of the CHANGELOG.rst. 1.5.0
mentions a breaking change that was actually a regular minor change.
This commit edit the content of the 1.5.0 changelog entry.
Closes: #540
> prepare 1.5.1 release

- CHANGELOG.rst
- changelogs/changelog.yaml
We actually need to modify the `changelogs/changelog.yaml` to
get the `CHANGELOG.rst` right.
I used `antsibull-changelog generate` to regenerate the final changelog
file.
> modify the changelog.yaml for 1.5.1 release

- tests/integration/targets/vmware_object_role_permission/alias
- tests/integration/targets/vmware_object_role_permission/tasks/main.yml
- tests/integration/targets/vmware_object_role_permission/tasks/user_friendly_role_name_tests.yml
- tests/integration/targets/vmware_object_role_permission/tasks/vmware_object_role_permission_tests.yml
This PR will add integration tests for the vmware_object_role_permission module.
tests/integration/targets/vmware_object_role_permission/alias  
tests/integration/targets/vmware_object_role_permission/tasks/main.yml  
tests/integration/targets/vmware_object_role_permission/tasks/user_friendly_role_name_tests.yml  
tests/integration/targets/vmware_object_role_permission/tasks/vmware_object_role_permission_tests.yml
> vmware_object_role_permission: add integration tests

- docs/community.vmware.vmware_object_role_permission_module.rst
- plugins/modules/vmware_object_role_permission.py
In principal parameter would permitted to use @ and \\ in a separator of a domain.  
I noticed that the vmware_object_role_permission hasn't idempotency when using @ at the principal parameter.  
Also, can't remove permission from an object when using @.  
This PR is to add a note about it to the module document.
plugins/modules/vmware_object_role_permission.py
docs/community.vmware.vmware_object_role_permission_module.rst
> vmware_object_role_permission: add note of separator of domain

- changelogs/fragments/pvlan_support.yml
- plugins/modules/vmware_guest_network.py
If a VM is in a Isolated Private VLAN, the _get_network_object() function fails because pvlanId property is used by VmwareDistributedVirtualSwitchPvlanSpec, rather than vlanId.
Step-by-step: Create a Private VLAN isolated port group. Put a VM in that port group. Attempt to modify the networks of that VM using the vmware_guest_network module. The following error will occur:
```
The full traceback is:
Traceback (most recent call last):
File "<stdin>", line 102, in <module>
File "<stdin>", line 94, in _ansiballz_main
File "<stdin>", line 40, in invoke_module
File "/usr/lib/python3.9/runpy.py", line 210, in run_module
return _run_module_code(code, init_globals, run_name, mod_spec)
File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code …
```
> vmware_guest_network: fix for VMs in a Isolated Private VLAN portgroup

- changelogs/fragments/527-vmware_host_facts.yml
- plugins/module_utils/vmware.py
- plugins/modules/vmware_host_facts.py
- tests/integration/targets/vmware_host_facts/tasks/main.yml
Depends-On: #553
Fixes #527 
Added info "host_current_time": "2020-11-30T08:43:56.472599+00:00",
```paste below
TASK [debug] ***********************************************************************************************************************************
ok: [localhost] => {
"esxi_host_results": {
"ansible_facts": {
"ansible_all_ipv4_addresses": [
"192.168.104.7"
], 
"ansible_bios_date": "2017-01-17T00:00:00+00:00", 
"ansible_bios_version": "2.4.3", 
"ansible_datastore": [
{
"free": "928.01 GB", 
"name": "test-ds", 
"total": "3.00 TB"
}, 
], 
"ansible_distribution": "VMware ESXi", 
"ansible_distribution_build": "14320388", 
"ansible_distribution_version": "6.7.0", 
"ansible_hostname": "test-esxi", 
"ansible_in_maintenance_mode": false, …
```
> vmware_host_facts: add ESXi host current time info in host facts

- changelogs/fragments/vmware_host_logbundle.yml
- plugins/modules/vmware_host_logbundle.py
When url timeouts fetch_url API returns None. Check status
before proceeding and using response from fetch_url
Fixes error message like
"Failed to fetch logbundle from ...: 'NoneType' object has no attribute 'read'"
changelogs/fragments/vmware_host_logbundle.yml
plugins/modules/vmware_host_logbundle.py
> vmware_host_logbundle - handle fetch_url status

- changelogs/fragments/545-vmware_guest.yml
- plugins/modules/vmware_guest.py
The behavior of the vSphere API changed considerably with 7.0U1 (probably already with 7.0, but I didn't have closer look).
The difference is: Although the key property of a virtual device is ignored, vCenter now checks if it is unique and fails if it isn't. The problem is that all virtual disks and NICs are created with a default key of 0, so are not unique.
Fixes #545 
vmware_guest
`vmware_guest_disk` has the same problem: #373
> vmware_guest: Fix an issue with vSphere 7 when adding several HDDs / NICs

- tests/integration/targets/vmware_migrate_vmk/aliases
tests/integration/targets/vmware_migrate_vmk/aliases
> temporarily disable vmware_migrate_vmk test

- changelogs/fragments/576-vmware_dvswitch.yml
- plugins/modules/vmware_dvswitch.py
When no `switch_version` is given, the module tries to guess the correct version. As far as I understand the code, the module even might upgrade the dvSwitch version when no version is given if you've upgraded your vCenter. But that's not how other modules work: If people don't specify something, we just ignore this... we don't silently change things.
Fixes #576 
> vmware_dvswitch: Fix idempotency prob with vSphere 7.0.1

- changelogs/fragments/568_teardown_with_esxi.yaml
- tests/integration/targets/prepare_vmware_tests/tasks/teardown_with_esxi.yml
Depends-On: https://github.com/ansible-collections/community.vmware/pull/577
In vCenter 7.0u1 and above when creating a vSphere cluster some vCenter managed VMs are created to help with DRS. When a shared a datastore is added to a cluster the VMs will be automatically moved there, which has broken the teardown_with_esxi play. After hosts are removed from the cluster the NFS datastore cannot be unmounted due to the existence of the vCLS VMs. This fix will forcefully remove the vCLS VMs before the hosts are removed from the cluster.
Also fixed the vSwitch0 removal to remove 'VM Network' port group from each host and fixed the remove hosts from cluster to use the parameterised cluster name.
teardown_with_esxi.yml 
```paste below
```
> update teardown to support vsphere 7.0u1

- changelogs/fragments/196_vmware_guest_disk.yml
- plugins/modules/vmware_guest_disk.py
- tests/integration/targets/vmware_guest_disk/tasks/main.yml
Fixes #196 
(1) There are parameters "scsi_type" and "scsi_controller" in this module, for back compatibility, add 2 new parameters "controller_type" and "controller_number" for setting SATA and NVMe controller type and bus number.
Also this "controller_type" can be used with managing SCSI type controller.
(2) Another thing is in commit 592db1ab13edb57b640de25e37e6af77bd372d6f:
```
disk_spec.device.backing.fileName = "[%s] %s/%s_%s_%s.vmdk" % (	
disk['datastore'].name,	
vm_name, vm_name,	
str(scsi_controller),	
str(disk['disk_unit_number']))
```
this part is removed to fix vmdk file duplicate issue, but if delete this, the datastore specified in parameter "datastore" will not take effect. So I added this back, and when datastore is not the same as …
> vmware_guest_disk: add SATA and NVMe disk support

- docs/community.vmware.vcenter_domain_user_group_info_module.rst
- plugins/modules/vcenter_domain_user_group_info.py
- tests/integration/targets/vcenter_domain_user_group_info/aliases
- tests/integration/targets/vcenter_domain_user_group_info/tasks/main.yml
This PR adds the new vcenter_domain_user_group_info module.  
By using the module, we can gather domain users or groups from the vCenter Server.
plugins/modules/vcenter_domain_user_group_info.py
tests/integration/targets/vcenter_domain_user_group_info/aliases
tests/integration/targets/vcenter_domain_user_group_info/tasks/main.yml
docs/community.vmware.vcenter_domain_user_group_info_module.rst
> vcenter_domain_user_group_info: add a new module

- tests/integration/targets/prepare_vmware_tests/tasks/init_real_lab.yml
- tests/integration/targets/prepare_vmware_tests/tasks/move_host_out_of_cluster.yml
- tests/integration/targets/vmware_resource_pool/aliases
- tests/integration/targets/vmware_resource_pool/tasks/main.yml
This PR adds tests for using the esxi_hostname parameter to the vmware_resource_pool integration test.  
Follow up: https://github.com/ansible-collections/community.vmware/pull/524
tests/integration/targets/vmware_resource_pool/tasks/main.yml
The integration test file did not existing the tests for using the esxi_hostname parameter, so I add it.
> vmware_resource_pool: add integration test for using esxi_hostname param

- changelogs/fragments/373-vmware_guest_disk.yml
- plugins/modules/vmware_guest_disk.py
The behavior of the vSphere API changed considerably with 7.0U1 (probably already with 7.0, but I didn't have closer look).
The difference is: Although the `key` property of a virtual device is ignored, vCenter now checks if it is unique and fails if it isn't. The problem is that all virtual disks are created with a default key of 0, so are not unique.
see issue #545 and PR #552 for more information
> vmware_guest_disk: Fix an issue with vSphere 7 when adding several HDDs

- changelogs/fragments/485_vmware_file_operation.yml
- plugins/modules/vmware_guest_file_operation.py
Return useful error message when exception occurs while file
operation.
Partially fixes: #485
changelogs/fragments/485_vmware_file_operation.yml
plugins/modules/vmware_guest_file_operation.py
> vmware_guest_file_operation: provide error message

- changelogs/fragments/539-vmware_host_ntp.yml
- plugins/modules/vmware_host_ntp.py
`vmware_host_ntp` failes (crashes) when trying to configure a host that is disconnected.
Fixes #539 
vmware_host_ntp
I've stolen this solution from `vmware_host_kernel_manager`.
> vmware_host_ntp: Fix issue with disconnected hosts

- changelogs/fragments/589_vmware_host.yml
- docs/community.vmware.vmware_host_module.rst
- plugins/modules/vmware_host.py
- tests/integration/targets/vmware_host/tasks/main.yml
This PR will add a new state option(disconnected) to the vmware_host module.  
By supporting the disconnected option, we can execute new integration tests for the disconnected state host.
docs/community.vmware.vmware_host_module.rst
plugins/modules/vmware_host.py
tests/integration/targets/vmware_host/tasks/main.yml
tested vCenter/ESXi 6.7
> vmware_host: add a new state option the disconnected

- tests/integration/targets/vmware_host_ntp/tasks/main.yml
This PR will add the integration tests of disconnected ESXi for the vmware_host_ntp module.  
Follow up: https://github.com/ansible-collections/community.vmware/pull/588
tests/integration/targets/vmware_host_ntp/tasks/main.yml
tested on vCenter/ESXi 6.7
> vmware_host_ntp: add the integration tests of disconnected ESXi 

- README.md
- docs/community.vmware.vmware_host_disk_info_module.rst
- plugins/modules/vmware_host_disk_info.py
- tests/integration/targets/vmware_host_disk_info/aliases
- tests/integration/targets/vmware_host_disk_info/tasks/main.yml
Added module to extract information about disks attached to a host. This can be used to link the naa number to the CTD number, which can be required for datastore creation, especially in home labs.
Added tests for both host and cluster extraction. The sim does not seem to expose the necessary endpoint, hence the need to test against actual objects.
vmware_host_disk_info.py
Below is an example of how the output can be used to build a mapping table of the CTD number to the naa number. This assumes results were registered as cluster_host_disks. If the CTD number is known, then this output can be used to enable datastore creation without knowing the naa number. I have found this necessary in my nested lab build and cannot automate local datastores without this …
> vmware_host_disk_info: new module

- tests/integration/targets/vmware_migrate_vmk/aliases
- tests/integration/targets/vmware_migrate_vmk/tasks/main.yml
`vmware_migrate_vmk` integration tests fail against vCenter 7
~~The integration test tries to create a vmkernel interface with IP `192.168.0.254/24`. But `192.168.0.254` is usually the broadcast address in network `192.168.0.0/24` and it's possible that vCenter 7 doesn't like this.~~
_edit:_
As @laidbackware pointed out correctly, the broadcast address is .255, **not** .254.
_update_:
I don't think we have a problem with creating the vmkernel interface or the IP `192.168.0.254/24`. It looks like `Add ESXi host to dvSwitch` fails and the CI pipeline tries again, but _then_ creating a vmk interface with `192.168.0.254/24` fails because this would result in a duplicate IP address.
> vmware_migrate_vmk: Fix integration test

- tests/integration/targets/vmware_host_iscsi/tasks/main.yml
Do not rely on the initial state of the host.
> vmware_host_iscsi/test: ignore pre-existing state

- changelogs/fragments/vmware_host_firewall_manager-prepare-all_ip-transition.yaml
- plugins/modules/vmware_host_firewall_manager.py
Depends-On: https://github.com/ansible-collections/community.vmware/pull/600
Starting with 2.0.0,  `all_ip` subkey of `allowed_hosts` will have to be defined.
See: https://github.com/ansible-collections/community.vmware/issues/178
> vmware_host_firewall_manager: prepare all_ip transition

- tests/integration/targets/vmware_host_iscsi_info/tasks/iscsi_info_module_test_tasks.yml
Ensure we don't depend on the state of the host. `iscsi` can actually
be already enabled.
> iscsi_info: don't depend on the initial state of the host

- tests/integration/targets/vmware_cluster_info/tasks/main.yml
- tests/integration/targets/vmware_guest/tasks/network_with_portgroup.yml
- tests/integration/targets/vmware_guest_network/tasks/main.yml
Address the following sanity errors:
```
Command exited with status 0 after 11.622503757476807 seconds.
ERROR: Found 6 yamllint issue(s) which need to be resolved:
ERROR: tests/integration/targets/vmware_cluster_info/tasks/main.yml:197:1: empty-lines: too many blank lines (1 > 0)
ERROR: tests/integration/targets/vmware_guest/tasks/network_with_portgroup.yml:107:9: key-duplicates: duplication of key "state" in mapping
ERROR: tests/integration/targets/vmware_guest_network/tasks/main.yml:457:11: key-duplicates: duplication of key "validate_certs" in mapping
ERROR: tests/integration/targets/vmware_guest_network/tasks/main.yml:475:11: key-duplicates: duplication of key "validate_certs" in mapping
ERROR: tests/integration/targets/vmware_guest_network/tasks/main.yml:493:11: key-duplicates: …
```
> ensure the sanity tests pass with 2.10.5

- changelogs/fragments/555-vmware_guest.yml
- changelogs/fragments/593_vmware_guest.yml
- plugins/modules/vmware_guest.py
Depends-On: #620 
Both `customization` and `hardware` are only defined as `type='dict', default={}` without any inner structure. I think it would be beneficial if the `argument_spec` would be more specific.
Fixes #555 
`vmware_guest`
~~There are some defaults that are checked within the code. We could declare them in `vmware_guest`, though, and let ansible do the heavy lifting.~~ 
_update:_
Unfortunately, we can't define defaults for the sub-options of `customization` because this would always trigger a customization.
> vmware_guest: Define sub-options of hardware and customization in argument_spec

- changelogs/fragments/617-vmware_host_iscsi.yml
- docs/community.vmware.vmware_host_iscsi_module.rst
- plugins/modules/vmware_host_iscsi.py
- tests/integration/targets/vmware_host_iscsi/tasks/iscsi_module_test_tasks.yml
Depends-On: https://github.com/ansible-collections/community.vmware/pull/620
This PR will add a new option for an iSCSI name changing.  
fixes: https://github.com/ansible-collections/community.vmware/issues/603
docs/community.vmware.vmware_host_iscsi_module.rst
plugins/modules/vmware_host_iscsi.py
tests/integration/targets/vmware_host_iscsi/tasks/iscsi_module_test_tasks.yml
> vmware_host_iscsi: Support an iSCSI name changing option

- README.md
- docs/community.vmware.vmware_first_class_disk_module.rst
- meta/runtime.yml
- plugins/module_utils/vmware.py
- plugins/modules/vmware_first_class_disk.py
- tests/integration/targets/vmware_first_class_disk/aliases
- tests/integration/targets/vmware_first_class_disk/tasks/main.yml
A new module to create, re-size and delete [first class disks](https://cormachogan.com/2018/11/21/a-primer-on-first-class-disks-improved-virtual-disks/).
vmware_first_class_disk
FCDs can be useful when you need to manage virtual disks independently from VMs. For example, if you have to re-build a VM but don't want to loose your data (for example because it's so much that recovering from backup would take too much time). FCDs allow you to
1. Create a FCD and attach it to a VM
2. Detach the FCD from the VM
3. Re-create the VM
4. Attach the FCD to the fresh VM
While this is possible with old-school VMDKs, this is quite painful. In the long run, vmware_guest_disk should also be FCD-aware but I wanted to start with a module to create them in the first place.
> vmware_first_class_disk: New module

- changelogs/fragments/623-vmware_datastore_cluster_manager.yml
- plugins/modules/vmware_datastore_cluster_manager.py
When running in check mode the module is always reporting changed even when it is not detecting any changes.
Fixes #623 
vmware_datastore_cluster_manager
> vmware_datastore_cluster_manager: Fix idempotency in check mode

- changelogs/fragments/626-vmware_guest_register_operation.yml
- plugins/modules/vmware_guest_register_operation.py
- tests/integration/targets/vmware_guest_register_operation/tasks/main.yml
The vmware_guest_register_operation hasn't supported the check mode.  
So, I want to add the check mode processing to the module by this PR.
plugins/modules/vmware_guest_register_operation.py
tests/integration/targets/vmware_guest_register_operation/tasks/main.yml
Tested on vCenter/ESXi 7.0
> vmware_guest_register_operation: Support the check mode

- README.md
- docs/community.vmware.vmware_drs_group_manager_module.rst
- meta/runtime.yml
- plugins/modules/vmware_drs_group_manager.py
- tests/integration/targets/vmware_drs_group_manager/aliases
- tests/integration/targets/vmware_drs_group_manager/tasks/main.yml
Depends-On: #620
Fixes: #81
README.md
docs/community.vmware.vmware_drs_group_manager_module.rst
plugins/modules/vmware_drs_group_manager.py
> vmware_drs_group_manager: new module

- changelogs/fragments/111-vmware_dvswitch_loop.yml
- plugins/modules/vmware_dvswitch_lacp.py
Fixes: #111
changelogs/fragments/111-vmware_dvswitch_loop.yml
plugins/modules/vmware_dvswitch_lacp.py
> vmware_dvswitch_lacp: Typecast uplink_number in lag_options

- README.md
- changelogs/fragments/397_vmware_content.yml
- docs/community.vmware.vmware_content_deploy_template_module.rst
- docs/community.vmware.vmware_drs_group_manager_module.rst
- plugins/module_utils/vmware.py
- plugins/modules/vmware_content_deploy_template.py
- plugins/modules/vmware_guest.py
- plugins/modules/vmware_guest_cross_vc_clone.py
* Marked Datastore, Hostname, Resource pool name, and cluster name as optional
* Added appropriate check, doc changes, and a warning message
* User should either has to specify cluster name or hostname with the resource pool name
* Added Datastore Cluster parameter
Fixes: #397 #550
changelogs/fragments/397_vmware_content.yml
docs/community.vmware.vmware_content_deploy_template_module.rst
plugins/modules/vmware_content_deploy_template.py
plugins/modules/vmware_guest_cross_vc_clone.py
> vmware_content_deploy_template: Make parameter optional

- tests/integration/targets/vmware_host_service_manager/aliases
Enable `vmware_host_service_manager` tests again.
Fixes #101 
vmware_host_service_manager
The jobs referenced in #101 are inaccessible, I guess they've been log-rotated away. I want to enable the tests again to see what happens.
_edit:_ [build succeeded](https://dashboard.zuul.ansible.com/t/ansible/buildset/e5e7558fcb974eb8b5c8cb3c96a98a0c)
> vmware_host_service_manager: enable the test-suite

- changelogs/fragments/636_vmware_guest.yml
- plugins/modules/vmware_guest.py
Checking the virtual HW version to be in the `range(3, 18)` is quite unnecessary.
Fixes #636 
vmware_guest
We need to change the range of valid versions for every new release. And anyway, it doesn't prevent anyone from using a theoretically(!) valid version with a vCenter or ESXi that doesn't support it; like version 18 with vCenter / ESXi 6.5.
> vmware_guest: Remove unnecessary hardware version check

- changelogs/fragments/638-vmware_dvs_portgroup.yml
- plugins/modules/vmware_dvs_portgroup.py
- tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
The vmware_dvs_portgroup hasn't the idempotency when configuring the multiple VLAN.  
This PR will fix that issue.
fixes: https://github.com/ansible-collections/community.vmware/issues/637
plugins/modules/vmware_dvs_portgroup.py
tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
changelogs/fragments/638-vmware_dvs_portgroup.yml
> vmware_dvs_portgroup: Fix the issues that the module hasn’t the idempotency when it is configured the multiple VLAN

- changelogs/fragments/643-vcenter_license.yml
- plugins/modules/vcenter_license.py
The module has the bug that the new or existing license doesn't assign in vCenter Server 7.0u1c.  
The cause of the bug is key.name changed the following like.
* 7.0u1 or less
```
VMware vCenter Server 7 Standard
```
* 7.0u1c
```
vCenter Server 7 Standard
```
This way, the VMware string seems to be removed in VCSA 7.0u1c.  
This PR will fix to assign correctly the license.
fixes: https://github.com/ansible-collections/community.vmware/issues/616
changelogs/fragments/643-vcenter_license.yml
plugins/modules/vcenter_license.py
tested on vCenter 7.0u1c/7.0u1/6.7
> vcenter_license: Fix the bug that the license doesn't assign in vCenter Server 7.0u1c

- changelogs/fragments/640-vmware_guest-disk_suboptions.yml
- plugins/modules/vmware_guest.py
As a follow-up to #595 I'd also like to define the inner structure of `disk` in `argument_spec`.
vmware_guest
I think that a correct `argument_spec` helps us a lot. For example, we don't have to check manually for a valid `controller_type` if we define `choices=['buslogic', 'lsilogic', 'paravirtual', 'lsilogicsas', 'sata', 'nvme']`.
> vmware_guest: Define sub-options of disk in argument_spec

- changelogs/fragments/579_vmware_category.yml
- plugins/modules/vmware_category.py
In vCenter 7.0.1, namespace is required in associable types.
Fixes: #579
changelogs/fragments/579_vmware_category.yml
> vmware_category: Add namespace to associable types

- changelogs/fragments/676_vmware_cluster_ha.yml
- plugins/modules/vmware_cluster_ha.py
There is a bug configuring APD or PDL response on the cluster level.
Fixes #676 
> Enable vmComponentProtecting for APD/PDL response

- changelogs/fragments/648-vmware_dvs_portgroup_find_info.yml
- plugins/modules/vmware_dvs_portgroup_find.py
- plugins/modules/vmware_dvs_portgroup_info.py
- tests/integration/targets/vmware_dvs_portgroup_find/tasks/main.yml
- tests/integration/targets/vmware_dvs_portgroup_info/tasks/main.yml
Depends-On: #668
In the following modules hadn't been decoded URL encoded dvs port group name.
* vmware_dvs_portgroup_find
* vmware_dvs_portgroup_info
This PR will fix to decode it.
plugins/modules/vmware_dvs_portgroup_find.py  
plugins/modules/vmware_dvs_portgroup_info.py
> Fix to decode URL encoded dvs port group name

- changelogs/fragments/673-vmware_cluster_info.yml
- plugins/modules/vmware_cluster_info.py
vmware_cluster_info doesn't return VSAN status correctly.
Fixes #673
> Correctly return VSAN status

- changelogs/fragments/682-vmware_vm_storage_policy.yml
- plugins/modules/vmware_vm_storage_policy.py
- tests/integration/targets/vmware_vm_storage_policy/tasks/main.yml
The vmware_vm_storage_policy module has been displaying pyvmomi error when a tag or category doesn't exist.  
This PR will fix to be displayed a suitable error message, not pyvmomi error.
fixes: https://github.com/ansible-collections/community.vmware/issues/677
changelogs/fragments/682-vmware_vm_storage_policy.yml
plugins/modules/vmware_vm_storage_policy.py
tests/integration/targets/vmware_vm_storage_policy/tasks/main.yml
> vmware_vm_storage_policy: Fix an issue that a pyvmomi SOAP error message displayed

- changelogs/fragments/693-vmware_guest_register_operation.yml
- plugins/modules/vmware_guest_register_operation.py
The vmware_guest_register_operation module has been occurring an error when not specifying a datacenter name.  
This PR will fix the issue.
fixes: https://github.com/ansible-collections/community.vmware/issues/692
changelogs/fragments/693-vmware_guest_register_operation.yml
plugins/modules/vmware_guest_register_operation.py
> vmware_guest_register_operation: An error has been occurring when not specify a datacenter name

- changelogs/fragments/670-vmware_deploy_ovf_and_vmware.yml
- plugins/module_utils/vmware.py
- plugins/modules/vmware_deploy_ovf.py
Fixes #670
If more than one ESXi hosts in the same datacenter as standalone host, need to specify the target ESXi host to deploy the template, or it will fail with datastore not supported error.
```paste below
tasks:
- name: Deploy VM from ovf template
vmware_deploy_ovf:
hostname: "192.18.228.10"
username: "Administrator@vsphere.local"
password: "Admin!23"
validate_certs: "{{ valid_cert | default(False) }}"
datacenter: "DC"
esxi_hostname: test-server.test.com
datastore: "datastore2"
networks: "{{ ovf_networks | default({'VM Network': 'VM Network'}) }}"
ovf: "./test.ova"
name: test_ovf_deploy
allow_duplicates: False
disk_provisioning: "thin"
power_on: False
wait_for_ip_address: False
register: ovf_deploy
- debug: var=ovf_deploy
```
> Add esxi_hostname support in vmware_deploy_ovf module

- meta/runtime.yml
- plugins/modules/vmware_guest_instant_clone.py
- tests/integration/targets/inventory_vmware_vm_inventory/_test/hosts/tmp.vmware.yml
- tests/integration/targets/vmware_guest_instant_clone/aliases
- tests/integration/targets/vmware_guest_instant_clone/tasks/main.yml
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.9.txt
Implementation for instant clone module
Vmware Guest Instant Clone Module
- The Instant Clone technology is used to create powered-on virtual machines from the running state of another powered-on virtual machine. 
- The result of an Instant Clone operation is a new virtual machine that is identical to the source virtual machine.
-  With Instant Clone you can create new virtual machines from a controlled point in time. 
- Instant cloning is very convenient for large-scale application deployments because it ensures memory efficiency and allows for creating numerous virtual machines on a single host.
- This module can be used for Creating a powered-on Instant Clone of a virtual machine.
- All variables and VMware object names are case sensitive.
> New module: vmware_guest_instant_clone

- changelogs/fragments/703-vmware_guest.yml
- plugins/modules/vmware_guest.py
- tests/integration/targets/vmware_guest/defaults/main.yml
- tests/integration/targets/vmware_guest/tasks/multiple_disk_controllers_d1_c1_f0.yml
The module fails when `disk.controller_number` or `disk.unit_number` are 0.
Fixes #703 
vmware_guest
https://github.com/ansible-collections/community.vmware/blob/f913056612c776b6527aa3c373fe7cb7358d2762/plugins/modules/vmware_guest.py#L2480
When `disk.controller_number` or `disk.unit_number` are 0, the module fails because `not 0` is `True`. 0 is a valid value, the module should only fail if these parameters are not defined at all.
> vmware_guest: Fix disk parameter validation

- changelogs/fragments/698-vmware_deploy_ovf.yml
- plugins/modules/vmware_deploy_ovf.py
vmware_deploy_ovf module has a bug that a return value hasn't the instance key when the power_on parameter is False.  
This PR will fix the issue.
fixes: https://github.com/ansible-collections/community.vmware/issues/691
changelogs/fragments/698-vmware_deploy_ovf.yml
> vmware_deploy_ovf: Fix an issue that a return value hasn’t the instance key when the power_on parameter is False

- changelogs/fragments/724-vmware_local_user_manager.yml
- docs/community.vmware.vmware_local_user_manager_module.rst
- plugins/modules/vmware_local_user_manager.py
A password error has been occurring in executing the module if the local_user_password doesn't set when the state is present.
**error**
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "A specified parameter was not correct: password"}
```
So, this PR will fix to require local_user_password when the state is present.
changelogs/fragments/724-vmware_local_user_manager.yml
docs/community.vmware.vmware_local_user_manager_module.rst
plugins/modules/vmware_local_user_manager.py
tested on ESXi 7.0
> vmware_local_user_manager: Fix to require local_user_password

- changelogs/fragments/vmware_inventory_example.yml
- docs/community.vmware.vmware_vm_inventory_inventory.rst
- plugins/inventory/vmware_vm_inventory.py
relates to the issue
https://github.com/ansible-collections/community.vmware/issues/678
How to customize hostname in inventory file to use FQDN
community.vmware
inventory plugin
> vmware_vm_inventory: get hostname's FQDN

- changelogs/fragments/disconnect_inventory.yml
- plugins/inventory/vmware_vm_inventory.py
VMs which are in disconnected state will not return any information
leading to failure of inventory plugin.
We skip such VMs altogether.
changelogs/fragments/disconnect_inventory.yml
> vmware_vm_inventory: Skip VMs in disconnected state

- changelogs/fragments/717-vmware_resource_pool.yml
- plugins/modules/vmware_resource_pool.py
- tests/integration/targets/vmware_resource_pool/tasks/main.yml
Add `parent_resource_pool` parameter which is mutually exclusive with `cluster`
and `esxi_hostname` #717
`plugins/modules/vmware_resource_pool`
Tested on a vCenter 6.7
```paste below
```
> vmware_resource_pool: Add parent_resource_pool parameter

- changelogs/fragments/681_vmware_inventory.yml
- plugins/inventory/vmware_vm_inventory.py
Skip over the ghost tags attached to VMs instead of failing.
Fixes: #681
changelogs/fragments/681_vmware_inventory.yml
> vmware_vm_inventory: skip over ghost tags attached to VMs

- README.md
- docs/community.vmware.vmware_guest_storage_policy_module.rst
- meta/runtime.yml
- plugins/modules/vmware_guest_storage_policy.py
- tests/integration/targets/vmware_guest_storage_policy/aliases
- tests/integration/targets/vmware_guest_storage_policy/tasks/main.yml
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.9.txt
Depends-On: https://github.com/ansible-collections/community.vmware/pull/668
New module submission
vmware_guest_storage_policy: Set VM Home and disk(s) storage policy profiles.
vmware_guest_storage_policy: Set VM Home and disk(s) storage policy profiles.
```paste below
- name: Enforce storepol1 policy for disk 0 and 1 using UUID
vmware_guest_storage_policy:
validate_certs: no
uuid: cefd316c-fc19-45f3-a539-2cd03427a78d
disk:
- unit_number: 0
policy: storepol1
- unit_number: 1
policy: storepol1
register: policy_status
- name: Enforce storepol1 policy for VM Home using name
vmware_guest_storage_policy: …
```
> New module: vmware_guest_storage_policy

- plugins/modules/vmware_vmkernel_ip_config.py
This is a follow-up to #667. I forgot to update `module.deprecate`. Sorry for this :-/
vmware_vmkernel_ip_config
> vmware_vmkernel_ip_config: Fix module.deprecate

- changelogs/fragments/745-vmware_guest_instant_clone.yml
- docs/community.vmware.vmware_guest_instant_clone_module.rst
- plugins/modules/vmware_guest_instant_clone.py
This PR will add esxi_hostname alias to the module.  
Also, remove the hostname parameter because covering by the parameter of vmware_argument_spec(module_utils/vmware)
changelogs/fragments/745-vmware_guest_instant_clone.yml
docs/community.vmware.vmware_guest_instant_clone_module.rst
plugins/modules/vmware_guest_instant_clone.py
> vmware_guest_instant_clone: Tweak the module adding esxi_hostname alias and removing duplicated hostname paramete

- changelogs/fragments/728-vmware_cluster_vsan.yml
- plugins/modules/vmware_cluster_vsan.py
The module breaks if `advanced_options` is not set.
Fixes #728 
`self.vsanClusterConfigSystem` is needed to configure VSAN but isn't set when no `advanced_options` are given.
> vmware_cluster_vsan: Fix a bug when advanced_options is not set

- tests/integration/targets/vmware_dvs_portgroup_info/tasks/main.yml
Address a regression introduced by #648.
Close: #750
> vmware_dvs_portgroup_info: ensure functional tests pass

- README.md
If using vSAN modules, the vSAN Management SDK for Python is necessary, but the README isn't written about it.  
So this PR will add it to README.
README.md
> README: Add the vSAN Management SDK for Python to README

- tests/integration/targets/vmware_guest_instant_clone/aliases
Ensure the CI uses an ESXi host that can actually start VM.
> vmware_guest_instant_clone: CI test starts VM

- tests/integration/targets/vmware_guest/aliases
These tests start VM, so we need an ESXi able to do that.
> CI: ensure vmware_guest tests only run on nested capable host

- tests/integration/targets/vmware_guest_instant_clone/tasks/main.yml
Ensure `vmware_guest_powerstate` looks for the VM at the default
location.
Closes: #761
> vmware_guest_instance_clone: tests: Unable to set power state

- tests/integration/targets/vmware_guest_storage_policy/tasks/main.yml
The tests need a datastore to host the VM.
> vmware_guest_storage_policy: test need datastore

- tests/integration/targets/vmware_guest_storage_policy/tasks/main.yml
The test VM will be removed later anyway. By doing this, we avoid the
following error:
"msg": "Unable to find the datastore with given parameters. This could mean, DC0_H0_VM1 is a non-existent virtual machine and module tried to deploy it as new virtual machine with no disk. Please specify disks parameter or specify template to clone from."
> vmware_guest_storage_policy: test: don't clean up the test VM

- tests/integration/targets/vmware_guest_instant_clone/tasks/main.yml
The tests require a host and a datastore.
> vmware_guest_instant_clone: properly initialize the env before the tests

- changelogs/fragments/764-vmware_evc_mode.yml
- docs/community.vmware.vmware_evc_mode_module.rst
- plugins/modules/vmware_evc_mode.py
Depends-On: https://github.com/ansible-collections/community.vmware/pull/770
According to the module documentation, evc_mode is unnecessary when the state set to absent.  
But actually, the option is required in executing the module.  
This PR will fix the bug and add the aliases for the datacenter and cluster.
fixes: https://github.com/ansible-collections/community.vmware/issues/702
changelogs/fragments/764-vmware_evc_mode.yml
docs/community.vmware.vmware_evc_mode_module.rst
plugins/modules/vmware_evc_mode.py
> vmware_evc_mode: Fix an issue that evc_mode is required when the state parameter set to absent

- tests/integration/targets/vmware_host_sriov/tasks/main.yml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/869
The integration tests of `vmware_host_sriov` require the test environment to support SR-IOV. I suggest to use `vmware_host_vmnic_info` to find out if `vmnic0` supports SR-IOV and run the tests only if it does.
Fixes #779 
vmware_host_sriov
See [this comment ff](https://github.com/ansible-collections/community.vmware/pull/773#issuecomment-814264707)
> vmware_host_sriov: Only run tests when SR-IOV is supported by NIC

- changelogs/fragments/729-vmware_host_iscsi_info.yml
- docs/community.vmware.vmware_host_iscsi_info_module.rst
- plugins/modules/vmware_host_iscsi_info.py
- tests/integration/targets/vmware_host_iscsi_info/tasks/iscsi_info_module_test_tasks.yml
I wanted to know a canonical name related to a static iscsi name, but the module hasn't returned it.  
It is useful when mounting a datastore if a canonical name is known.  
So this PR will add it to the return value.
And fix the following issue.
fixes: https://github.com/ansible-collections/community.vmware/issues/736
changelogs/fragments/729-vmware_host_iscsi_info.yml
docs/community.vmware.vmware_host_iscsi_info_module.rst
plugins/modules/vmware_host_iscsi_info.py
tests/integration/targets/vmware_host_iscsi_info/tasks/iscsi_info_module_test_tasks.yml
> vmware_host_iscsi_info: Add detected_iscsi_drives value to return and fix the issue736

- changelogs/fragments/644-vmware_dvs_portgroup.yml
- plugins/modules/vmware_dvs_portgroup.py
- plugins/modules/vmware_dvs_portgroup_info.py
- tests/integration/targets/prepare_vmware_tests/tasks/setup_dvswitch.yml
- tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
Depends-On: ansible/ansible-zuul-jobs#869
Implement MAC learning, elastic PGs and active / standby uplink configuration.
Fixes #644
Fixes #410
Fixes #709 
vmware_dvs_portgroup_info
While working on this I've seen that `securityPolicy` is [deprecated](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/fe08899f-1eec-4d8d-b3bc-a6664c168c2c/7fdf97a1-4c0d-4be0-9d43-2ceebbc174d9/doc/vim.dvs.VmwareDistributedVirtualSwitch.VmwarePortConfigPolicy.html#field_detail) and macManagementPolicy ([DVSMacManagementPolicy](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/fe08899f-1eec-4d8d-b3bc-a6664c168c2c/7fdf97a1-4c0d-4be0-9d43-2ceebbc174d9/doc/vim.dvs.VmwareDistributedVirtualSwitch.MacManagementPolicy.html))  should be used to configure …
> vmware_dvs_portgroup: MAC learning, elastic PGs and uplink configuration

- changelogs/fragments/805-vmware_cluster_info.yml
- plugins/modules/vmware_cluster_info.py
`vmware_cluster_info` returns `enabled_vsan` and `vsan_auto_claim_storage` as a list instead of just `true` or `false`.
Fixes #805 
> Do not return enabled_vsan and vsan_auto_claim_storage as a list

- changelogs/fragments/803-vmware_vmotion-better-error-msg.yml
- plugins/modules/vmware_vmotion.py
This is a proposition of fix for #803.
I also added a missing «find» in another error message.
Fixes #803 by adding an explicit error message.
- `vmware_vmotion` module
Please, review this PR twice, as I'm testing only one use case:
- `destination_host` defined (correctly and wrongly) and `destination_datastore` defined
According to the code other cases could be valid but not tested (only  `destination_host` or only `destination_datastore` defined, or combined with `destination_resourcepool`…)
> vmware_vmotion: Fail when required ESXi host is not found

- changelogs/fragments/777_vapp_info.yml
- plugins/module_utils/vmware.py
vmware_vm_info uses get_parent_datacenter API, which fails for
vApp.
Fixes: #777
> vmware_vm_info: Handle vApp parent logic

- changelogs/fragments/788-vmware_vm_storage_policy_info.yml
- plugins/modules/vmware_vm_storage_policy_info.py
Depends-On: ansible/ansible-zuul-jobs#869
The module has a bug that it can't get storage policy info when the policy has the tag base rules.  
This PR will fix the bug.
fixes: https://github.com/ansible-collections/community.vmware/issues/742
plugins/modules/vmware_vm_storage_policy_info.py
> vmware_vm_storage_policy_info: Fix an issue that the module can't get the info when the policy has the tag base rules

- changelogs/fragments/721_vmware_guest.yml
- plugins/modules/vmware_guest.py
CustomValues are supported by vCenter and not by standalone
ESXi. While deploying VM on a standalone ESXi, skip customvalues.
Fixes: #721
changelogs/fragments/721_vmware_guest.yml
> Skip customvalues while deploying VM on a standalone ESXi

- changelogs/fragments/732_vmware_vm_shell.yml
- plugins/modules/vmware_vm_shell.py
Exception is raised when some vms have been deleted from the Esix
#732 
vmware_vm_shell
```paste below
```
> catch exception raised for deleted resources

- changelogs/fragments/712_vmware_vm_inventory.yml
- plugins/inventory/vmware_vm_inventory.py
For AWX/Tower, setting the default value for `with_nested_properties`
as True
Fixes: #712
changelogs/fragments/712_vmware_vm_inventory.yml
> vmware_vm_inventory - set with_nested_properties as True

- README.md
- docs/community.vmware.vmware_host_tcpip_stacks_module.rst
- meta/runtime.yml
- plugins/modules/vmware_host_tcpip_stacks.py
- tests/integration/targets/vmware_host_tcpip_stacks/aliases
- tests/integration/targets/vmware_host_tcpip_stacks/tasks/destroy.yml
- tests/integration/targets/vmware_host_tcpip_stacks/tasks/main.yml
- tests/integration/targets/vmware_host_tcpip_stacks/tasks/pre.yml
- tests/integration/targets/vmware_host_tcpip_stacks/tasks/vmware_host_tcpip_stacks_tests.yml
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.12.txt
- tests/sanity/ignore-2.9.txt
This PR will add a new module to update the tcpip stack configuration.
fixes: https://github.com/ansible-collections/community.vmware/issues/107
fixes: https://github.com/ansible-collections/community.vmware/issues/654
README.md
docs/community.vmware.vmware_host_tcpip_stacks_module.rst
plugins/modules/vmware_host_tcpip_stacks.py
tests/integration/targets/vmware_host_tcpip_stacks/aliases
tests/integration/targets/vmware_host_tcpip_stacks/tasks/destroy.yml
tests/integration/targets/vmware_host_tcpip_stacks/tasks/main.yml
tests/integration/targets/vmware_host_tcpip_stacks/tasks/pre.yml
tests/integration/targets/vmware_host_tcpip_stacks/tasks/vmware_host_tcpip_stacks_tests.yml …
> vmware_host_tcpip_stacks: Add a new module to update the tcpip stack configuration

- changelogs/fragments/791_vmware.yml
- plugins/module_utils/vmware.py
Example: a host is removed during the execution of get_all_objs as you are getting all hosts.
When vmhosts are being deleted/removed from inventory and you run get_all_objs, the following failure message appears
"The object 'vim.HostSystem:host-3406' has already been deleted or has not been completely created".
vmware.py
> ignore objects that are removed during get_all_objs execution

- changelogs/fragments/739-vmware_cluster_drs.yml
- plugins/modules/vmware_cluster_drs.py
- plugins/modules/vmware_cluster_ha.py
- plugins/modules/vmware_cluster_vsan.py
- tests/integration/targets/prepare_vmware_tests/tasks/setup_cluster.yml
- tests/integration/targets/vmware_cluster_drs/tasks/main.yml
- tests/integration/targets/vmware_cluster_ha/tasks/main.yml
- tests/integration/targets/vmware_cluster_vsan/tasks/main.yml
Depends-On: ansible/ansible-zuul-jobs#869
If the user does not specify this parameter explicitly by setting it to Yes (True), then the consequences for the cluster can be destructive, because disabling DRS destroys the entire Resourse Pools tree. For some environments (eg VCD, VRA) the consequences will be disastrous.
~~I don't want to just change the default from `false` to `true` because this will lead to playbooks behaving differently after updating the collection; making this a required parameter might make playbooks fail but I think this is still better than changing the default behavior.~~
Since this is a breaking change, I'll only announce that the default will change in the future.
vmware_cluster_drs
See issue #739 
I'm …
> vmware_cluster_drs/ha/vsan: Announce change of enable parameter default for the future

- changelogs/fragments/833-vmware_dvswitch-network_policy.yml
- docs/community.vmware.vmware_dvswitch_module.rst
- plugins/module_utils/vmware.py
- plugins/modules/vmware_dvs_portgroup.py
- plugins/modules/vmware_dvs_portgroup_info.py
- plugins/modules/vmware_dvswitch.py
- tests/integration/targets/vmware_dvswitch/tasks/main.yml
This PR implements `promiscuous`, `forged_transmits` and `mac_changes` on the distributed switch. This allows people to to use port groups that inherit a default set on the DVS.
Fixes #833 
Fixes #839 
I've moved the function checking if the distributed virtual switch supports MAC learning to `module_utils/vmware.py` because DRY.
> vmware_dvswitch: Add Network Policy

- changelogs/fragments/816-vmware_guest.yml
- docs/community.vmware.vmware_guest_module.rst
- plugins/modules/vmware_guest.py
When enabling visualization based security, `vmware_guest` silently configures some stuff like secure boot. I think we should make this explicit.
vmware_guest
#351 made me think about how we handle visualization based security and I don't like it. I really don't think it's a good idea if modules silently configure something, I think it should always be explicit. Or, at least, they should issue a warning that they are doing some things implicitly.
> vmware_guest: Improve virtualization based security

- changelogs/fragments/834-vmware_host_tcpip_stacks.yml
- docs/community.vmware.vmware_host_tcpip_stacks_module.rst
- plugins/modules/vmware_host_tcpip_stacks.py
This PR will add ipv6_gateway parameter and nsx_overlay as an alias of vxlan.  
The features have been requested by the below comment.
fixes: https://github.com/ansible-collections/community.vmware/issues/654#issuecomment-832385007
In the comment, the cluster_name parameter also has been requesting, but first of all, I implemented easy No1 and 3.  
The module is designed to handle one ESXi, so it may be difficult to implement the cluster_name.  
But, I'll try to continue considering implementing the cluster_name parameter.
docs/community.vmware.vmware_host_tcpip_stacks_module.rst
plugins/modules/vmware_host_tcpip_stacks.py
> vmware_host_tcpip_stacks: Add ipv6_gateway option and nsx_overlay as an alias of vxlan

- README.md
- changelogs/fragments/851-vmware_object_custom_attributes_info.yml
- docs/community.vmware.vmware_object_custom_attributes_info_module.rst
- meta/runtime.yml
- plugins/modules/vmware_object_custom_attributes_info.py
- tests/integration/targets/vmware_object_custom_attributes_info/aliases
- tests/integration/targets/vmware_object_custom_attributes_info/tasks/main.yml
- tests/integration/targets/vmware_object_custom_attributes_info/tasks/pre.yml
- tests/integration/targets/vmware_object_custom_attributes_info/tasks/vmware_object_custom_attributes_info_tests.yml
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.12.txt
- tests/sanity/ignore-2.9.txt
This PR will add a new module to gather custom attributes of an object.
README.md
changelogs/fragments/851-vmware_object_custom_attributes_info.yml
docs/community.vmware.vmware_object_custom_attributes_info_module.rst
plugins/modules/vmware_object_custom_attributes_info.py
tests/integration/targets/vmware_object_custom_attributes_info/aliases
tests/integration/targets/vmware_object_custom_attributes_info/tasks/main.yml
tests/integration/targets/vmware_object_custom_attributes_info/tasks/pre.yml
tests/integration/targets/vmware_object_custom_attributes_info/tasks/vmware_object_custom_attributes_info_tests.yml
tests/sanity/ignore-2.9.txt
tests/sanity/ignore-2.12.txt
> vmware_object_custom_attributes_info: Add a new module to gather custom attributes of an object

- changelogs/fragments/855_vmware_host_inventory.yml
- changelogs/fragments/855_vmware_vm_inventory.yml
- plugins/inventory/vmware_host_inventory.py
- plugins/inventory/vmware_vm_inventory.py
Our environment uses a service account for the dynamic inventory, and prefers to leave the rest of the file unencrypted for easier editing. The password was already supported for vaulting, this just adds username as well.
Fixes #854 
```paste below
```
> Allow the username to be a vault encrypted variable.

- README.md
- docs/community.vmware.vmware_recommended_datastore_module.rst
- meta/runtime.yml
- plugins/modules/vmware_recommended_datastore.py
- tests/integration/targets/vmware_recommended_datastore/aliases
- tests/integration/targets/vmware_recommended_datastore/tasks/main.yml
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.12.txt
- tests/sanity/ignore-2.9.txt
vmware_recommended_datastore: Returns the recommended datastore from a SDRS-enabled datastore cluster
- This module provides the recommended datastores from a datastore cluster only if the SDRS is enabled for the specified datastore cluster
vmware_recommended_datastore
> vmware_recommended_datastore new module

- tests/integration/targets/vmware_content_library_manager/aliases
Temporarily disable `vmware_content_library_manager` tests until the test-suite is fixed.
See: #875
> vmware_content_library_manager: disable the test-suite

- changelogs/fragments/867-vmware.yml
- plugins/module_utils/vmware.py
Depends-On: #877
The get_vm method in vmware.py has a bug that isn’t returned None if moId doesn't exist.  
This PR will fix the issue.
fixes: https://github.com/ansible-collections/community.vmware/issues/866
In this patch will become that will be returned None if ManagedObjectNotFound occurred when accessing to any attribute.
Tested on VCSA/ESXi 7.0
> vmware: fix that the return value should be returned None if moId doesn't exist

- changelogs/fragments/879-vmware_object_custom_attributes_info.yml
- docs/community.vmware.vmware_object_custom_attributes_info_module.rst
- plugins/module_utils/vmware.py
- plugins/modules/vmware_object_custom_attributes_info.py
- tests/integration/targets/vmware_object_custom_attributes_info/tasks/pre.yml
- tests/integration/targets/vmware_object_custom_attributes_info/tasks/vmware_object_custom_attributes_info_tests.yml
This PR will add a new parameter to support moid to the module and a new method to get Managed Object based on moid and object type to vmware.py.  
We can quickly search Managed Object based on moid and object type by using the find_obj_by_moid method.  
Also, the method will be standardized to search by moid.  
The method can be also searched a virtual machine but already implemented get_vm that dedicated to a virtual machine, so I've added a comment about recommended searching method when a virtual machine.
changelogs/fragments/879-vmware_object_custom_attributes_info.yml
docs/community.vmware.vmware_object_custom_attributes_info_module.rst  
plugins/module_utils/vmware.py  
plugins/modules/vmware_object_custom_attributes_info.py …
> vmware_object_custom_attributes_info: add a new parameter to support moid

- README.md
- changelogs/fragments/872-vmware_host_passthrough.yml
- docs/community.vmware.vmware_host_passthrough_module.rst
- meta/runtime.yml
- plugins/modules/vmware_host_passthrough.py
- tests/integration/targets/vmware_host_passthrough/aliases
- tests/integration/targets/vmware_host_passthrough/tasks/main.yml
- tests/integration/targets/vmware_host_passthrough/tasks/pre.yml
- tests/integration/targets/vmware_host_passthrough/tasks/vmware_host_passthrough.yml
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.12.txt
- tests/sanity/ignore-2.9.txt
Depends-On: #877
This PR will add a new module to enable or disable the passthrough of PCI devices with ESXi has.
README.md
changelogs/fragments/872-vmware_host_passthrough.yml
docs/community.vmware.vmware_host_passthrough_module.rst
plugins/modules/vmware_host_passthrough.py
tests/integration/targets/vmware_host_passthrough/aliases
tests/integration/targets/vmware_host_passthrough/tasks/main.yml
tests/integration/targets/vmware_host_passthrough/tasks/pre.yml
tests/integration/targets/vmware_host_passthrough/tasks/vmware_host_passthrough.yml
tests/sanity/ignore-2.9.txt
tests/sanity/ignore-2.12.txt
> vmware_host_passthrough: Add a new module to enable or disable passthrough of PCI devices

- changelogs/fragments/796-vmware_guest_instant_clone.yml
- plugins/modules/vmware_guest_instant_clone.py
- tests/integration/targets/vmware_guest_instant_clone/tasks/main.yml
Adding GuestOS Customization feature for Instant Cloned VM
vmware_guest_instant_clone module
- Provides GuestOS Customization functionality in instant cloned VM.
- A list of key-value pairs will be passed to the destination VM.
- These pairs should be used to provide user-defined customization to differentiate the destination VM from the source VM.
> Adding GuestOs Customization for Instant Clone feature

- plugins/inventory/vmware_host_inventory.py
- plugins/inventory/vmware_vm_inventory.py
Add an example for compose in the inventory plugin to populate a string value for host variables.
> Add a string composed variable example for vmware_vm_inventory plugin

- changelogs/fragments/878_vmware_guest_controller.yml
- plugins/modules/vmware_guest_controller.py
Depends-On: #877
bus_sharing property have been missing from the module and was added.
Tested on vcenter 7.0 and 6.7.
> vmware_guest_controller: Added bus_sharing property to scsi controllers.

- tests/integration/targets/vmware_content_library_manager/aliases
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/957
This reverts commit b44ec019efec3018b52e5c66681933316ebf1f3f.
> Revert "vmware_content_library_manager: disable the test-suite (#877)"

- tests/integration/targets/vmware_vswitch/tasks/main.yml
With ESXi 7.0.2, we cannot add a network if the name comes with a '/'.
ESXi 7.0.2 and vSphere 7.0.2:
$ govc host.vswitch.add -host.dns=esxi1.test -dc=my-dc foobar
$ govc host.vswitch.add -host.dns=esxi1.test -dc=my-dc 'foo\\bar'
$ govc host.vswitch.add -host.dns=esxi1.test -dc=my-dc 'foo/bar'
govc: ServerFaultCode: An error occurred during host configuration.
$ govc host.vswitch.add -host.dns=esxi1.test -dc=my-dc 'foo//bar'
govc: ServerFaultCode: An error occurred during host configuration.
$ govc host.vswitch.add -host.dns=esxi1.test -dc=my-dc 'foo\\bar2'
$ govc host.vswitch.add -host.dns=esxi1.test -dc=my-dc 'foo\%'
> vmware_vswitch: remove / from special char tests

- changelogs/fragments/831-vmware_guest-hostname.yml
- plugins/modules/vmware_guest.py
Only use hostname from customization dictionary if value is not None. 
Fixes #655
vmware_guest.py
The "customization" dictionary seems to be filled with None values when parameters like hostname aren't set in playbook. default_name is not used here because hostname already exists in the dictionary.
> vmware_guest: Fix hostname is None when not used in playbook.

- changelogs/fragments/821-vmware_guest_powerstate.yml
- docs/community.vmware.vmware_guest_powerstate_module.rst
- plugins/module_utils/vmware.py
- plugins/modules/vmware_guest_powerstate.py
The answer is required in starting the vm if the vm is blocked after you copied or moved the vm.  
FYI, The following image is shown at that time on Web Client.
This PR will add the option to answer to the module and vmware.
changelogs/fragments/821-vmware_guest_powerstate.yml
docs/community.vmware.vmware_guest_powerstate_module.rst
plugins/modules/vmware_guest_powerstate.py
tested on ESXi 7.0
> vmware_guest_powerstate: Add the answer option to require in starting the vm

- changelogs/fragments/904-vmware_guest_instant_clone.yml
- docs/community.vmware.vmware_guest_instant_clone_module.rst
- plugins/modules/vmware_guest_instant_clone.py
This PR will add the following points.
* Reboot an instant clone after making it.
* Should require rebooting to reflect the customization parameters to the instant clone vm
* add a new option that is wait_vm_tools for checking reboot process complete
* add a new option that is wait_vm_tools_timeout
* Must require vm_username, vm_password, and guestinfo_vars if you are executed the customization, so I add required_together
* add instance_uuid to the return value
docs/community.vmware.vmware_guest_instant_clone_module.rst
plugins/modules/vmware_guest_instant_clone.py
> vmware_guest_instant_clone: Improve some features

- changelogs/fragments/829_vmware_rest_client_add_support_for_proxy.yml
- changelogs/fragments/848_vmware_rest_client_add_support_for_proxy.yml
- docs/community.vmware.vmware_category_facts_module.rst
- docs/community.vmware.vmware_category_info_module.rst
- docs/community.vmware.vmware_category_module.rst
- docs/community.vmware.vmware_content_deploy_ovf_template_module.rst
- docs/community.vmware.vmware_content_deploy_template_module.rst
- docs/community.vmware.vmware_content_library_info_module.rst
- docs/community.vmware.vmware_content_library_manager_module.rst
- docs/community.vmware.vmware_object_rename_module.rst
- docs/community.vmware.vmware_tag_info_module.rst
- docs/community.vmware.vmware_tag_manager_module.rst
- docs/community.vmware.vmware_tag_module.rst
- docs/community.vmware.vmware_vc_infraprofile_info_module.rst
- plugins/doc_fragments/vmware_rest_client.py
- plugins/module_utils/vmware_rest_client.py
module using ``vmware_rest_client`` can now connect to vsphere client using proxy feature.
#843
vmware_category_facts
vmware_category_info
vmware_content_library_info
vmware_datacenter_info
vmware_guest_info
vmware_object_rename
vmware_tag_info
vmware_tag
vmware_vc_infraprofile_info
vmware_vm_info
vmware_vm_storage_policy
> vmware_rest_client support proxy

- changelogs/fragments/112-vmware_dvs_host.yml
- docs/community.vmware.vmware_dvs_host_module.rst
- plugins/modules/vmware_dvs_host.py
- tests/integration/targets/vmware_dvs_host/tasks/main.yml
This change allows users to add pNICs to LAGs.
Fixes #112
vmware_dvs_host
```
vmnic:
- vmnic0
- vmnic1
lag_uplinks:
- lag: foo
vmnic:
- vmnic2
- vmnic3
- lag: bar
vmnic:
- vmnic4
- vmnic5
```
I didn't find a way to directly add vmnics to LAGs when adding a host so I had to change the logic a bit: First add the host to the switch, then add the vmnics to the (LAG) uplink ports.
> vmware_dvs_host: Implement adding pNICs to LAGs

- changelogs/fragments/817-vmware_vm_inventory-support-proxy.yml
- plugins/inventory/vmware_host_inventory.py
- plugins/inventory/vmware_vm_inventory.py
- plugins/module_utils/vmware.py
add new parameters ``proxy_host``, ``proxy_port`` and ``ssl_proxy_path`` in order to allow api access behind proxy.
#775 
```paste below
---
plugin: community.vmware.vmware_vm_inventory
proxy_host: 192.168.123.5
proxy_port: 3128
```
> vmware_vm_inventory support api access behind proxy

- plugins/module_utils/vm_device_helper.py
- plugins/modules/vmware_guest_disk.py
Remove duplicate code from `vmware_guest_disk` by using the functions from `module_utils.vm_device_helper. PyVmomiDeviceHelper`.
Follow-up to PR #909
> vmware_guest_disk: Use functions from module_utils

- tests/integration/targets/vmware_host_iscsi/tasks/iscsi_module_test_tasks.yml
- tests/integration/targets/vmware_host_iscsi/tasks/main.yml
- tests/integration/targets/vmware_host_ntp/aliases
- tests/integration/targets/vmware_host_ntp/tasks/main.yml
- tests/integration/targets/vmware_host_tcpip_stacks/aliases
- tests/integration/targets/vmware_object_custom_attributes_info/tasks/main.yml
- tests/integration/targets/vmware_tag_manager/aliases
- tests/integration/targets/vmware_vcenter_settings_info/aliases
This PR will fix an issue that vm_hba doesn't find during testing CI.  
I’ll try to fix the issue by using vmware_host_iscsi_info module.
fixes: https://github.com/ansible-collections/community.vmware/issues/927
tests/integration/targets/vmware_host_iscsi/tasks/iscsi_module_test_tasks.yml
tests/integration/targets/vmware_host_iscsi/tasks/main.yml
tests/integration/targets/vmware_host_ntp/tasks/main.yml
vmware_host_iscsi: fixed
vmware_object_custom_attributes_info: fixed
vmware_host_ntp: disabled
vmware_host_tcpip_stacks: disabled
vmware_tag_manager: disabled
vmware_vcenter_settings_info: disabled
> Organize the failed tests as a list in CI

- README.md
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/982
We actual only test with the last pyvmomi release and we only provide
best effort support of the older versions. Overall, it's pretty
easy to upgrade pyvmomi.
> readme: clarify we support the last pyvmomi release

- tests/integration/targets/vmware_vcenter_settings_info/aliases
- tests/integration/targets/vmware_vcenter_settings_info/tasks/main.yml
Depends-on https://github.com/ansible-collections/community.vmware/pull/945
This PR will fix an issue that the vmware_vcenter_settings_info test has been occurring the error.
tests/integration/targets/vmware_vcenter_settings_info/tasks/main.yml
tested on vCenter 7.0.2
> vmware_vcenter_settings_info: Fix the integration test error

- tests/integration/targets/vmware_portgroup/tasks/main.yml
Depends-On: https://github.com/ansible-collections/community.vmware/pull/949
We cannot use the / character in switch name with ESXi7.
See: https://github.com/ansible-collections/community.vmware/pull/889
> vmware_portgroup/test: no / in switch name

- tests/integration/targets/inventory_vmware_host_inventory/aliases
- tests/integration/targets/inventory_vmware_vm_inventory/aliases
Depends-On: https://github.com/ansible-collections/community.vmware/pull/950
I've just disabled the integration tests for inventory_vmware_host_inventory and inventory_vmware_vm_inventory in 945 because they kept failing. But I'd like to enable them again ASAP.
inventory_vmware_host_inventory
inventory_vmware_vm_inventory
> Re-enable inventory tests

- tests/integration/targets/vmware_tag_manager/aliases
- tests/integration/targets/vmware_tag_manager/tasks/cleanup.yml
- tests/integration/targets/vmware_tag_manager/tasks/main.yml
- tests/integration/targets/vmware_tag_manager/tasks/tag_manager_dict.yml
Depends-on https://github.com/ansible-collections/community.vmware/pull/945
We've disabled the integration tests for `vmware_tag_manager` in PR #930 to get the CI pipeline working again. This PR enables them again.
see [here](https://github.com/ansible-collections/community.vmware/pull/930#issuecomment-875569564)
> vmware_tag_manager: Fix and re-enable integration tests

- changelogs/fragments/924-vmware_guest_powerstate.yml
- docs/community.vmware.vmware_guest_powerstate_module.rst
- plugins/modules/vmware_guest_powerstate.py
- tests/integration/targets/vmware_guest_powerstate/tasks/main.yml
Depends-on https://github.com/ansible-collections/community.vmware/pull/945
vmware_guest_powerstate module has a bug that datacenter key error has been occurring if the same VM name is detected in VCSA.  
The datacenter parameter should be required in the get_vm method if the same VM name is detected.  
https://github.com/ansible-collections/community.vmware/blob/main/plugins/module_utils/vmware.py#L1208-L1221
So, this PR will add the datacenter parameter to the module to fix the bug.
fixes: https://github.com/ansible-collections/community.vmware/issues/921
changelogs/fragments/924-vmware_guest_powerstate.yml
docs/community.vmware.vmware_guest_powerstate_module.rst
plugins/modules/vmware_guest_powerstate.py
tests/integration/targets/vmware_guest_powerstate/tasks/main. …
> vmware_guest_powerstate: Fix an error that the datacenter key error has been occurring

- tests/integration/targets/vmware_guest_instant_clone/aliases
```
TASK [vmware_guest_instant_clone : Instant Clone a VM with parent VM] **********
task path: /home/zuul/.ansible/collections/ansible_collections/community/vmware/tests/integration/targets/vmware_guest_instant_clone/tasks/main.yml:37
(...)
fatal: [testhost]: FAILED! => {
"changed": false,
"datacenter": "DC0",
"datastore": "rw_datastore",
"folder": "F0",
"guestinfo_vars": [],
"host": "esxi1.test",
"hostname": "vcenter.test",
"moid": null,
"name": "cloned_vm_from_vm",
"parent_vm": "test_vm1",
"password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
"port": 443,
"proxy_host": null,
"proxy_port": null,
"resource_pool": "DC0_C0_RP1",
"use_instance_uuid": false,
"username": "administrator@vsphere.local",
"uuid": null,
"validate_certs": false,
"vm_password": null, …
```
> tests: disable vmware_guest_instant_clone for now

- tests/integration/targets/vmware_first_class_disk/aliases
- tests/integration/targets/vmware_guest/aliases
- tests/integration/targets/vmware_guest_disk_info/aliases
- tests/integration/targets/vmware_guest_instant_clone/aliases
- tests/integration/targets/vmware_guest_network/aliases
- tests/integration/targets/vmware_guest_powerstate/aliases
- tests/integration/targets/vmware_guest_screenshot/aliases
- tests/integration/targets/vmware_guest_tools_wait/aliases
- tests/integration/targets/vmware_vm_inventory/aliases
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/987
Depends-On: https://github.com/ansible-collections/community.vmware/pull/958
We don't make the difference between nested/regular target anymore.
> tests: remove zuul/vmware/vcenter_1esxi_with_nested

- changelogs/fragments/915-vmware_host_datastore.yml
- docs/community.vmware.vmware_host_datastore_module.rst
- plugins/modules/vmware_host_datastore.py
This PR will add a new option to expand a datastore capacity.  
For example, I think it is a useful parameter in expanding a datastore capacity after increasing LUN capacity with a new enclosure and so on.  
Alternative PR from: https://github.com/ansible-collections/community.vmware/pull/913
changelogs/fragments/915-vmware_host_datastore.yml
docs/community.vmware.vmware_host_datastore_module.rst
plugins/modules/vmware_host_datastore.py
tested on vCenter/ESXi 7.0.2
> vmware_host_datastore: Add a new parameter to expand a datastore capacity

- plugins/module_utils/vm_device_helper.py
- plugins/modules/vmware_guest_controller.py
- plugins/modules/vmware_guest_disk.py
Depends-On: https://github.com/ansible-collections/community.vmware/pull/967
Remove duplicate code from `vmware_guest_controller` by using functions from `module_utils.vm_device_helper.PyVmomiDeviceHelper`. Also, move some definitions from `vmware_guest_controller` and `vmware_guest_disk` to `module_utils.vm_device_helper.PyVmomiDeviceHelper`.
Follow-up to PR #914
> Refactor vmware guest controller

- README.md
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/989
We are now running the integration tests on Ansible 2.11.
> functional tests run on Ansible 2.11 now

- tests/integration/targets/prepare_vmware_tests/tasks/setup_attach_hosts.yml
- tests/integration/targets/prepare_vmware_tests/tasks/teardown_with_esxi.yml
- tests/integration/targets/vmware_cluster_info/aliases
Depends-On: https://github.com/ansible-collections/community.vmware/pull/961
Depends-On: https://github.com/ansible-collections/community.vmware/pull/967
When we start our tests, VM Network is on vSwitch0. This is
configuration is conflicting when we want to create the same portgroup
on the `isolate_vSwitch0`.
So far, we avoided the conflict because the teardown_with_esxi.yml
playbook was called at the end of the first target and cleaning up the
portgroup.
This is not the case anymore because:
- we randomize¹ the target execution order
- the vmware_cluster_info target does not attach the ESXi host and so
the teardown was not working as expected.
This commit introduces the following changes:
- alway clean up VM Network from vSwitch0 before we try to recreate
it on the `isolated_vSwitch0`. …
> tests: ensure we can create 'VM Network'

- plugins/inventory/vmware_host_inventory.py
- plugins/inventory/vmware_vm_inventory.py
- plugins/plugin_utils/inventory.py
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.12.txt
- tests/sanity/ignore-2.9.txt
Depends-On: https://github.com/ansible-collections/community.vmware/pull/966
Depends-On: https://github.com/ansible-collections/community.vmware/pull/967
- move module_utils/inventory.py to plugin_utils/inventory
- vmware_vm_inventory.py: reuse to_nested_dict and to_flatten_dict from
the plugin_utils file.
- drop pylint:ansible-bad-module-import from the ignore files
See: https://github.com/ansible/ansible/pull/75254#issuecomment-880099069
inventory
> improve code sharing of the inventory plugins

- tests/integration/targets/prepare_vmware_tests/tasks/move_host_out_of_cluster.yml
- tests/integration/targets/prepare_vmware_tests/tasks/teardown_with_esxi.yml
- tests/integration/targets/vmware_resource_pool/tasks/main.yml
Depends-on https://github.com/ansible/ansible-zuul-jobs/pull/989
This might cause problems:
https://github.com/ansible-collections/community.vmware/blob/418b090f528aed924c685ce963e5de17e2082328/tests/integration/targets/prepare_vmware_tests/tasks/teardown_with_esxi.yml#L90-L110
If removing the ESXi host succeeds, exiting maintenance mode fails because the host isn't known to vCenter any more.
Fixes https://github.com/ansible-collections/community.vmware/issues/952
tests/integration/targets/prepare_vmware_tests/tasks/teardown_with_esxi.yml
Removing all ESXi hosts from the cluster befor removing them from vCenter avoids problems with vCLS VMs. Unfortunatelly, this change broke the `vmware_resource_pool` integration tests so I had to fix this, too.
> Improve prepare_vmware_tests

- tests/integration/targets/vmware_content_library_manager/aliases
The integration tests for vmware_content_library_manager fail. I think we should disable them for now.
> Disable vmware_content_library_manager tests

- tests/integration/targets/vmware_first_class_disk/aliases
- tests/integration/targets/vmware_guest/aliases
- tests/integration/targets/vmware_guest_disk_info/aliases
- tests/integration/targets/vmware_guest_instant_clone/aliases
- tests/integration/targets/vmware_guest_network/aliases
- tests/integration/targets/vmware_guest_powerstate/aliases
- tests/integration/targets/vmware_guest_screenshot/aliases
- tests/integration/targets/vmware_guest_tools_wait/aliases
- tests/integration/targets/vmware_vm_inventory/aliases
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1001
Depends-on https://github.com/ansible-collections/community.vmware/pull/971
Re-enable the jobs depending on nested virt.
See: https://github.com/ansible/ansible-zuul-jobs/pull/1001
This reverts commit ddcee83f76ccfadd751a5e3be5723d44c472aed1.
> Revert "Revert PR 957 (#967)"

- tests/integration/targets/vmware_vmkernel_ip_config/tasks/main.yml
The vmware_vmkernel_ip_config integration tests fail:
```
2021-07-21 19:28:19.449213 | fedora-34 | TASK [vmware_vmkernel_ip_config : Create a new vSwitch] ************************
2021-07-21 19:28:19.449386 | fedora-34 | task path: /home/zuul/.ansible/collections/ansible_collections/community/vmware/tests/integration/targets/vmware_vmkernel_ip_config/tasks/main.yml:45
2021-07-21 19:28:19.455846 | fedora-34 | [WARNING]: conditional statements should not include jinja2 templating
2021-07-21 19:28:19.455894 | fedora-34 | delimiters such as {{ }} or {% %}. Found: not '{{ switch1 }}' in
2021-07-21 19:28:19.455899 | fedora-34 | gather_vswitch_info_result.hosts_vswitch_info[esxi1]
2021-07-21 19:28:19.463763 | fedora-34 | fatal: [testhost]: FAILED! => {
2021-07-21 19:28:19.463791 | fedora-34 | …
```
> Fix vmware_vmkernel_ip_config integration tests

- changelogs/fragments/962-vmware_guest_instant_clone.yml
- docs/community.vmware.vmware_guest_instant_clone_module.rst
- plugins/modules/vmware_guest_instant_clone.py
- tests/integration/targets/vmware_guest_instant_clone/aliases
The cause of the following error occurred is that the default of the guestinfo_vars parameter hadn't been removed.
https://github.com/ansible-collections/community.vmware/pull/958
This PR will fix the issue and re-enable the integration test.
changelogs/fragments/962-vmware_guest_instant_clone.yml
docs/community.vmware.vmware_guest_instant_clone_module.rst
plugins/modules/vmware_guest_instant_clone.py
tests/integration/targets/vmware_guest_instant_clone/aliases
tested on vCenter/ESXi 7.0.2
> vmware_guest_instant_clone: Remove the default of the guestinfo_vars and enable the test

- changelogs/fragments/976-vmware_host_datastore.yml
- plugins/modules/vmware_host_datastore.py
The following error occurs in executing the module when datastore_type parameter doesn't specify and state is present.  
In the following error, the users can't understand the cause of the error.
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "New-style module did not handle its own exit"}
```
The error message isn't the right error expression.  
So, this PR will fix to be displayed the right error message.
Also, I removed unused the following processing in the module because it can be covered required_if.
The following codes will be covered by required_if.
```python
if module.params['state'] == 'present':
if module.params['datastore_type'] == 'nfs' and not module.params['nfs_server']:
msg = "Missing nfs_server with datastore_type = nfs"
module.fail_json(msg=msg)
if …
```
> vmware_host_datastore: The right error message doesn't be displayed

- tests/integration/targets/vmware_host_tcpip_stacks/aliases
- tests/integration/targets/vmware_host_tcpip_stacks/tasks/destroy.yml
- tests/integration/targets/vmware_host_tcpip_stacks/tasks/main.yml
Depends-On: https://github.com/ansible-collections/community.vmware/pull/972
We've disabled the integration tests for `vmware_host_tcpip_stacks` in PR #930 to get the CI pipeline working again. This PR enables them again.
vmware_host_tcpip_stacks
see [here](https://github.com/ansible-collections/community.vmware/pull/930#issuecomment-875579233)
I think these tests don't always fail. It looks like the main problem is that `destroy.yml` isn't always run. If the tests fail for a temporary problem and are run again, `pre.yml` fails because `vmk1` already exists. So I think the best solution is to always run `destroy.yml`.
> vmware_host_tcpip_stacks: Fix and re-enable integration tests

- changelogs/fragments/978-vmware_guest_snapshot_info.yml
- plugins/module_utils/vmware.py
- plugins/modules/vmware_guest_snapshot_info.py
Besides below snapshot info, add `quiesced`, e.g.,
```
"guest_snapshots": {
"current_snapshot": {
"creation_time": "2021-07-20T09:41:48.870077+00:00",
"description": "",
"id": 5,
"name": "quiesce_snapshot_1626774041",
"state": "poweredOff",
"quiesced": true
},
...
```
vmware_guest_snapshot_info
```paste below
```
> Add quiesced status in snapshot info

- changelogs/fragments/112-vmware_dvs_host.yml
- changelogs/fragments/738-vmware_content_deploy_xxx.yml
- changelogs/fragments/796-vmware_guest_instant_clone.yml
- changelogs/fragments/816-vmware_guest.yml
- changelogs/fragments/817-vmware_vm_inventory-support-proxy.yml
- changelogs/fragments/819-vmware_vcenter_settings-advanced_setting.yml
- changelogs/fragments/821-vmware_guest_powerstate.yml
- changelogs/fragments/828_vmware_host_vmnic_info.yml
- changelogs/fragments/831-vmware_guest-hostname.yml
- changelogs/fragments/833-vmware_dvswitch-network_policy.yml
- changelogs/fragments/834-vmware_host_tcpip_stacks.yml
- changelogs/fragments/838_vmware_host_custom_attributes.yml
- changelogs/fragments/848_vmware_rest_client_add_support_for_proxy.yml
- changelogs/fragments/851-vmware_object_custom_attributes_info.yml
- changelogs/fragments/855_vmware_host_inventory.yml
- changelogs/fragments/855_vmware_vm_inventory.yml
- changelogs/fragments/858_vmware_vmotion_add_destination_datacenter_parameter.yml
- changelogs/fragments/867-vmware.yml
- changelogs/fragments/872-vmware_host_passthrough.yml
- changelogs/fragments/874-vmware_object_role_permission_info-principal_permissions.yml
- changelogs/fragments/878_vmware_guest_controller.yml
- changelogs/fragments/879-vmware_object_custom_attributes_info.yml
- changelogs/fragments/904-vmware_guest_instant_clone.yml
@Akasurde @goneri It looks like there are a lot of old changelog fragments from before the 1.12 release. Shouldn't we delete them?
> Delete old changelog fragments

- plugins/module_utils/vca.py
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.12.txt
Module validation for `vca_fw`  and `vca_nat` fails.
vca
See [this](https://github.com/ansible-collections/community.vmware/pull/983#issuecomment-890352071l) and the following comments.
> vca: fix validation

- changelogs/fragments/955-vmware_portgroup.yml
- plugins/modules/vmware_portgroup.py
- tests/integration/targets/vmware_portgroup/tasks/main.yml
It doesn't really make sense that vmware_portgroup requires `traffic_shaping.average_bandwidth`, `traffic_shaping.peak_bandwidth` and `traffic_shaping.burst_size` if people want to _disable_ traffic shaping.
Fixes #955
vmware_portgroup
See #955 for more information.
> vmware_portgroup: Improve parameter sanity

- changelogs/fragments/983-vmware.yml
- plugins/module_utils/vmware.py
- tests/unit/module_utils/test_vmware.py
Depends-on https://github.com/ansible-collections/community.vmware/pull/991
Depends-on https://github.com/ansible-collections/community.vmware/pull/977
I think that the isinstance shouldn't use in the evaluation formula for bool because it occurs mistaking evaluation.  
For example:
```python
if isinstance(True, int): # <= is judged as a True
pass
```
The cause of mistaking evaluation is that bool type is implemented as an integer sub-class.  
Please see the following:
* https://docs.python.org/3/library/functions.html#isinstance
* https://docs.python.org/3/c-api/bool.html
When using the isinstance, the vmware_vcenter_settings module doesn't work well.  
Because bool will be converted to an integer by the following processing.  
https://github.com/ansible-collections/community.vmware/blob/ …
> vmware: Change to use from isinstance to type in if condition

- changelogs/fragments/933-vmware_guest_add_msg_customization_failed.yml
- plugins/modules/vmware_guest.py
Fix result message of PyVmomiHelper.wait_for_customization when it returns failed:True.
Added 'msg' to return value when 'wait_for_customization' failed in `deploy_vm()`
Changed 'msg' when 'wait_for_customization' failed in `customize_exist_vm()`
For every result with `result['failed']==True` we must have a 'msg' or we get an error while attempting to get it from result dict at end of main() function. Other cases in this module provide 'failed':True with 'msg'. 
Moreover, current 'msg' for customization existing vm was not correct because `wait_for_customization()` can return False not only due to timeout but also due to `"Customization failed with error {%s}:{%s}"`. Because of backward compatibility we cannot change its return type …
> vmware_guest: Provide a meaningful message when customization failed

- changelogs/fragments/449-vmware_guest_disk_rdm.yml
- docs/community.vmware.vmware_guest_disk_module.rst
- plugins/modules/vmware_guest_disk.py
Raw Device Mapping is not a currently available. This change allows RDM disks (physical and virtual) to be added/deleted.
- name: Add physical raw device mapping to virtual machine using name
vmware_guest_disk:
datacenter: "{{ datacenter_name }}"
validate_certs: no
name: "Test_VM-RDM"
disk:
- type: rdm
state: present
scsi_controller: 1
unit_number: 5
rdm_path: /vmfs/devices/disks/naa.06000980ab1234efg453
compatibility_mode: 'physicalMode'
- name: Add virtual raw device mapping to virtual machine using name
vmware_guest_disk:
datacenter: "{{ …
> vmware_guest_disk: Feature addition RDM Disks

- changelogs/fragments/916-vmware_host_service_manager.yml
- plugins/modules/vmware_host_service_manager.py
When setting the service startup policy using the vmware_host_service_manager module, you have to specify the service state if you don't want to start the service, which is the default behavior. Changing the default for `state` would be a breaking change so this PR introduces a new state `unchanged` that will not change the service state.
Fixes #916
vmware_host_service_manager
Please see the issue this PR is trying to fix, I don't think I have any additional information apart from this.
> vmware_host_service_manager: Change startup policy without defining state

- changelogs/fragments/990-vmware_category.yml
- plugins/modules/vmware_category.py
- tests/integration/targets/vmware_category/tasks/associable_obj_types.yml
Depends-on https://github.com/ansible-collections/community.vmware/pull/991
The vmware_category module has a bug that the version doesn't compare and obj_types_set doesn't be flattened.  
This PR will be fixed the following issues.
* Fixed the issue that VCSA version doesn't compare(added connect_to_api method to generate the content object)
* The associable_data instance hasn't Datacenter, so added it.
* The error has occurred in set processing, so added flatten processing to fix it.
fixes: https://github.com/ansible-collections/community.vmware/issues/989
changelogs/fragments/990-vmware_category.yml
plugins/modules/vmware_category.py
tests/integration/targets/vmware_category/tasks/associable_obj_types.yml
tested on vCenter/ESXi 7.0.2
> vmware_category: Fix the issue that the error has been occurred when 'All objects' set to associable_object_types

- changelogs/fragments/892-vmware_vmkernel.yml
- plugins/modules/vmware_vmkernel.py
- List all vNICs with from the current vSAN config
- Check intent before adding/removing
- Implement proper addition/removal, instead of previous config squashing (which only enabled one vNIC)
- Return a result message instead of a None value
Fixes #891 
This implementation allows to set more than one vmk NIC with the vSAN service, it will look up current configuration and modify it instead of crafting a new configuration that handles the last vmk NIC added.
cloud/vmware/vmware_vmkernel.py
```paste below
$ ansible-playbook -i development ./provision.yml -v -t esxi_vmk_interfaces -l esxi_host
PLAY [vsan]
TASK [esxi_vmk_intrefaces : Configure vmkernel port vmk0]
changed: [esxi_host -> localhost] => {"changed": true, "device": "vmk0", "ipv4": "static", "ipv4_gw": "No …
```
> Improve behavior for setting vSAN service on a vmk

- changelogs/fragments/993-vmware_vm_config_option.yml
- plugins/module_utils/vm_device_helper.py
- plugins/modules/vmware_guest.py
- plugins/modules/vmware_vm_config_option.py
- tests/integration/targets/vmware_vm_config_option/aliases
- tests/integration/targets/vmware_vm_config_option/tasks/main.yml
This module can be used to:
1. get the config options keys list (support for creation hardware versions and default hardware version),
2. get the list of supported guest IDs for specified hardware version or default version,
3. get the basic recommended VM config options for specified guest ID with specified hardware version or default version. 
Fixes #993 
```paste below
TASK [debug] *****************************************************************************************************************************
ok: [localhost] => {
"vm_default_config": {
"changed": false,
"failed": false,
"instance": {
"Default hardware version": "vmx-14",
"Recommended config options": {
"Default CDROM controller": …
```
> Add a new module vmware_vm_config_option

- changelogs/fragments/powerstate.yml
- plugins/module_utils/vmware.py
set_vm_powerstate does not consider 'present' state.
This fix updates 'present' state to 'poweredon' state for
`vmware_guest_powerstate`.
changelogs/fragments/powerstate.yml
> vmware_guest_powerstate: handle 'present' state

- docs/community.vmware.vmware_guest_module.rst
- plugins/modules/vmware_guest.py
Document the vmware default resource pool name "Resources" in case this module is used in a loop and must be specified
Adds vmware default catch-all resource pool name 'Resources'
vmware_guest
Simplify how vmware handles this variable when undefined (or defined in a loop and operator needs to use the proper default)
> vmware_guest: Update documentation about "Resources" example

- changelogs/fragments/975_vmware_vm_inventory.yml
- plugins/inventory/vmware_vm_inventory.py
Inventory failed erroneously if ansible_host is not
present. This is not true for all conditions (VM poweredoff,
Bad VM configuration etc.)
Fix removes this erroneous condition.
Fixes: #975
changelogs/fragments/975_vmware_vm_inventory.yml
> vmware_vm_inventory: Remove erroneous condition

- docs/docsite/rst/vmware_scenarios/vmware_requirements.rst
- plugins/doc_fragments/vmware.py
- plugins/modules/vmware_target_canonical_facts.py
- plugins/modules/vmware_target_canonical_info.py
All modules require API write access, which is not provided
in a free ESXi license. Added a note in all the modules so
that users will find it easily.
docs/docsite/rst/vmware_scenarios/vmware_requirements.rst
plugins/doc_fragments/vmware.py
plugins/modules/vmware_target_canonical_facts.py
plugins/modules/vmware_target_canonical_info.py
> doc: Add a note about free ESXi license

- plugins/modules/vsphere_file.py
There is module called **community.vmware.vsphere_file** . There is one task _Query a file on a datastore_  to get information of already existing file on vsphere. But In Documentation there mentioned **state : touch** . But state:touch is used to create new blank file on vsphere,not to get existing file information. In order to Query a file the state attribute value should `file` not touch.   
**state :  file**
Correct code :
- name: Query a file on a datastore
community.vmware.vsphere_file:
host: '{{ vhost }}'
username: '{{ vuser }}'
password: '{{ vpass }}'
datacenter: DC1 Someplace
datastore: datastore1
path: some/remote/file
**state: file**
ignore_errors: true
Fixes #1029 
community.vmware.vsphere_file
> vsphere_file: Update `file` example

- changelogs/fragments/1050-vmware_vcenter_settings_info.yml
- plugins/modules/vmware_vcenter_settings_info.py
- tests/integration/targets/vmware_vcenter_settings_info/tasks/main.yml
This PR will fix to return all VCSA settings when setting vsphere to the schema and not specifying the properties.
fixes: https://github.com/ansible-collections/community.vmware/issues/1049
changelogs/fragments/1050-vmware_vcenter_settings_info.yml
plugins/modules/vmware_vcenter_settings_info.py
tests/integration/targets/vmware_vcenter_settings_info/tasks/main.yml
tested on VCSA/ESXi 7.0
> vmware_vcenter_settings_info: Fix an issue that Python error has occurred when the schema is vsphere

- changelogs/fragments/deprecate-vmware_guest_vnc.yml
- meta/runtime.yml
- plugins/modules/vmware_guest_vnc.py
- tests/sanity/ignore-2.9.txt
vSphere 7.0 removed the built-in VNC server (see the [release notes](https://docs.vmware.com/en/VMware-vSphere/7.0/rn/vsphere-esxi-vcenter-server-70-release-notes.html#productsupport)) so I don't see the need to have a module for this anymore.
vmware_guest_vnc
#28
> Deprecate vmware_guest_vnc

- changelogs/fragments/870_vmware_guest_tools_wait.yml
- plugins/modules/vmware_guest_tools_wait.py
Depends-On: #877 
Add datacenter option to vmware_guest_tools_wait module.
Resolves  #869 
vmware_guest_tools_wait
> Add datacenter option to vmware_guest_tools_wait

- changelogs/fragments/1065-vmware_deploy_ovf.yml
- plugins/modules/vmware_deploy_ovf.py
This PR will fix to display suitable the error when not exist an ovf file path.
fixes: https://github.com/ansible-collections/community.vmware/issues/1064
tested on VCSA/ESXi 7.0
> vmware_deploy_ovf: Fix to display suitable the error

- docs/community.vmware.vca_fw_module.rst
- plugins/modules/vca_fw.py
The example in the files vca_fw.py and vmware.vca_fw_module.rst is for adding firewall rules. However, the state is set to absent. So, removed the state variable.
vca_fw.py
vmware.vca_fw_module.rst
```paste below
```
> vca_fw: Removed state set to absent from the example

- tests/integration/targets/vmware_dvs_portgroup_find/tasks/main.yml
Ensure the functional test results don't depend on the portgroup order.
> vmware_dvs_portgroup_find/test: ignore the result order

- tests/integration/targets/vmware_host_tcpip_stacks/aliases
With vcenter 7.0.3, the vmware_host_tcpip_stacks tests break the
IPv4 configuration of the node. We must preserve the original
gateway or the node become unreachable.
See: https://github.com/ansible-collections/community.vmware/issues/1120
See: https://9f6249684dbca3f269bd-b5dfc8e1a8b1871b232cb0142d3e37c5.ssl.cf5.rackcdn.com/1101/a22fda4f98f6cc0277579dddcfd2f6bf4338e6ca/check/ansible-test-cloud-integration-vcenter7_1esxi-python36-stable211_2_of_2/b220e11/job-output.txt
> disable vmware_host_tcpip_stacks/tests for now

- tests/integration/targets/vmware_vcenter_settings/tasks/main.yml
Restore the original advanced_settings configuration to be able to run
the test two times in a row.
> vmware_vcenter_settings/tests: restore advanced_settings config

- changelogs/fragments/1117_add_additional_usb_scan_codes.yml
- docs/community.vmware.vmware_guest_sendkey_module.rst
- plugins/modules/vmware_guest_sendkey.py
Add additional USB scan codes for HOME and END.
- vmware_guest_sendkey
See the following document for HID usage tables: https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf. The codes for `HOME` and `END` can be found on page 55.
> vmware_guest_sendkey: add additional USB scan codes for `HOME` and `END`

- tests/integration/targets/vmware_vm_host_drs_rule/tasks/main.yml
Remove the DRS rule and DRS groups at the end of the tests.
> vmware_vm_host_drs_rule/tests: clean up resources

- tests/integration/targets/vmware_guest/tasks/reconfig_vm_to_latest_version.yml
We don't really need to go above the 1 CPU limit. Our test ESXis come
with only 4 CPUS.
> test VM should not use more than 1 CPU

- tests/integration/targets/vmware_vm_inventory/prepare_environment.yml
- tests/integration/targets/vmware_vm_inventory/test_inventory.yml
Fedora cannot boot properly with just 128MB of memory. This was not a
problem with ESXi 6.7.0U3 but with 7.0.3, the ESXi can figure out that
the VM has crashed because it's run out of for memory.
So, now we start one single VM and we ensure it's got enough memory.
> vmware_vm_inventory/tests: only spawn 1 VM with 1GB of RAM

- tests/integration/targets/vmware_guest/tasks/clone_resize_disks.yml
- tests/integration/targets/vmware_guest/tasks/create_vm_using_special_characters.yml
- tests/integration/targets/vmware_guest/tasks/network_with_device.yml
- tests/integration/targets/vmware_guest/tasks/network_with_dvpg.yml
- tests/integration/targets/vmware_guest/tasks/network_with_portgroup.yml
- tests/integration/targets/vmware_guest/tasks/reconfig_vm_to_latest_version.yml
- tests/integration/targets/vmware_guest_network/tasks/main.yml
- tests/integration/targets/vmware_guest_tools_wait/tasks/main.yml
- tests/integration/targets/vmware_host_auto_start/tasks/main.yml
- tests/integration/targets/vmware_vmotion/tasks/main.yml
The use of the rhel7_64Guest guest_id unlocks some CPU features that we
cannot use yet with our CI envionment. The virtualized ESXi won't be able
to spawn the nested VM properly.
A consequence is the `Disconnected from virtual machine.` error message.
> always use debian8_64Guest in our functinal tests

- tests/integration/targets/vmware_vmkernel_ip_config/tasks/main.yml
Our hosts come with a 192.168.0.0/24 private network, by using a /24
subnetwork of 172.16/16, we reduce the risk of clash.
The commit also simplify the logic used to build the device name.
> vmware_vmkernel_ip_config/tests: avoid IPv4 conflict

- tests/integration/targets/prepare_vmware_tests/tasks/setup_virtualmachines.yml
- tests/integration/targets/vmware_guest/tasks/create_rp_d1_c1_f0.yml
- tests/integration/targets/vmware_guest/tasks/network_with_device.yml
- tests/integration/targets/vmware_guest_instant_clone/tasks/main.yml
- tests/integration/targets/vmware_guest_network/tasks/main.yml
- tests/integration/targets/vmware_guest_tools_wait/tasks/main.yml
- tests/integration/targets/vmware_host_auto_start/tasks/main.yml
- tests/integration/targets/vmware_vmotion/tasks/main.yml
The ESXis of our CI come with an heterogeneous collection of CPU. The
goal is to avoid any dependency with recent CPU features.
> tests: use hw version 11

- tests/integration/targets/vmware_content_library_manager/aliases
- tests/integration/targets/vmware_content_library_manager/tasks/main.yml
The test now dynamically retrieves the fingerprint of
wp-content.vmware.com. This way we don't need to hardcode the key.
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1217
> vmware_content_library_manager: reenable the tests

- test-requirements.txt
- tests/integration/targets/prepare_vmware_tests/tasks/setup_virtualmachines.yml
- tests/integration/targets/prepare_vmware_tests/tasks/teardown.yml
- tests/integration/targets/prepare_vmware_tests/tasks/teardown_with_esxi.yml
- tests/integration/targets/vmware_guest/tasks/check_mode.yml
- tests/integration/targets/vmware_guest/tasks/clone_customize_guest_test.yml
- tests/integration/targets/vmware_guest/tasks/clone_with_convert.yml
- tests/integration/targets/vmware_guest/tasks/main.yml
- tests/integration/targets/vmware_guest/tasks/run_test_playbook.yml
- tests/integration/targets/vmware_guest_disk_info/tasks/main.yml
- tests/integration/targets/vmware_host_datastore/tasks/main.yml
- tests/integration/targets/vmware_host_firewall_manager/tasks/main.yml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1215
vmware.vmware_rest allow uses to simplify the clean up of the resources
and avoid any leaked VM.
Also:
- test VMs use lighter disk size.
- do not umount the datastore during the teardown.
> tests: use vmware.vmware_rest to clean up the resources

- changelogs/fragments/1044_add_syscontact_syslocation_vmware_host_snmp.yml
- docs/community.vmware.vmware_host_snmp_module.rst
- plugins/modules/vmware_host_snmp.py
- tests/integration/targets/vmware_host_snmp/tasks/main.yml
Depends-On: https://github.com/ansible-collections/community.vmware/pull/1102
Added code to support setting SNMP syscontact and syslocation.
Fixes #1044
vmware_host_snmp.py
community.vmware.vmware_host_snmp_module.rst
```paste below
```
> vmware_host_snmp: Add code to support SNMP values

- changelogs/fragments/rescan_VMFS_feature.yml
- plugins/modules/vmware_host_scanhba.py
Allow for only scaning new VMFS. Also allow to not rescan HBAs as this might be very slow. At the same time keep backwards compatibility. 
vmware_host_scanhba.py
See  #479 for details.
```paste below
```
> vmware_host_scanhba: rescan VMFS feature

- changelogs/fragments/1013-vmware_rdm_updates.yml
- plugins/modules/vmware_guest_disk.py
Depends-On: #1046
RDM feature has some missing pieces to allow it to work in shared disk server environments. These changes enable automation
of those types of environments
- vmware_guest_disk
- You can now add up to 64 disks into a ParaVirtual SCSI Adapter if you are adding to a machine with hardware version 14 or higher (Vsphere 6.7)
- Added bus_sharing as an option to enable setting the SCSI bus sharing to physicalSharing or virtualSharing
- Added new key "cluster_disk" for shared disk environments. This ensures that when you are adding the secondary machine Vsphere doesnt try to copy the file which causes file lock issues with the RDM. 
```
- name: Add raw device mapping to virtual machine with Physical bus sharing 
community.vmware.vmware_guest_disk:
hostname: …
```
> RDM and Disk Improvements

- changelogs/fragments/1017-vmware_guest-fix_administrator_password.yml
- plugins/modules/vmware_guest.py
When using Windows VM customization and not specifying a password, the Administrator password is reset to string 'None'. ~~This PR is making the parameter mandatory.~~ This PR is fixing that - when password is not defined, it is cleared (https://vdc-download.vmware.com/vmwb-repository/dcr-public/b50dcbbf-051d-4204-a3e7-e1b618c1e384/538cf2ec-b34f-4bae-a332-3820ef9e7773/vim.vm.customization.GuiUnattended.html).
Fixes: #1017 
vmware_guest
```paste below
```
> vmware_guest: fix the Windows Administrator password being set to string 'None'

- changelogs/fragments/vmware_cluster_drs-ha-vsan-enable_default.yml
- plugins/modules/vmware_cluster_drs.py
- plugins/modules/vmware_cluster_ha.py
- plugins/modules/vmware_cluster_vsan.py
- tests/integration/targets/vmware_cluster_drs/tasks/main.yml
- tests/integration/targets/vmware_cluster_ha/tasks/main.yml
- tests/integration/targets/vmware_cluster_vsan/tasks/main.yml
The default for `enable` in vmware_cluster_drs/ha/vsan should be `true` instead of `false`. This is more consistent with other modules and might avoid serious issues.
Fixes #739
vmware_cluster_drs
I've also removed the aliases for `enable`. `enable_drs` is a bit redundant in a module dealing with DRS, it should be obvious what `enable` is about.
> vmware_cluster_drs/ha/vsan remove alias and change default for enable

- plugins/modules/vmware_guest.py
The docs for `vmware_guest`  incorrectly state that the [advanced_settings](https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html#parameter-advanced_settings) parameter was added in 1.7.0.
This PR sets the release date to the correct version 1.8.0.
vmware_guest
The feature was added in #179 as d5d00e3a2c9fcae82858c9d31d4cc7791560573b.
It did not make it into 1.7.0 but was released as part of 1.8.0, see the [release notes](https://github.com/ansible-collections/community.vmware/blob/main/CHANGELOG.rst#v1-8-0).
> Fix version_added of vmware_guest.advanced_settings

- plugins/modules/vmware_guest.py
Backport of #1156:
The docs for `vmware_guest`  incorrectly state that the [advanced_settings](https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html#parameter-advanced_settings) parameter was added in 1.7.0.
This PR sets the release date to the correct version 1.8.0.
vmware_guest
The feature was added in #179 as d5d00e3a2c9fcae82858c9d31d4cc7791560573b.
It did not make it into 1.7.0 but was released as part of 1.8.0, see the [release notes](https://github.com/ansible-collections/community.vmware/blob/main/CHANGELOG.rst#v1-8-0).
> [backport] vmware_guest: Fix version_added of advanced_settings

- plugins/modules/vmware_cluster_info.py
- plugins/modules/vmware_datastore_info.py
- plugins/modules/vmware_guest_info.py
- plugins/modules/vmware_guest_snapshot_info.py
- plugins/modules/vmware_tag_info.py
- plugins/modules/vmware_vm_info.py
Remove the references to the old `_facts` from the `_info` modules.
vmware_datastore_info
vmware_guest_info
vmware_guest_snapshot_info
vmware_tag_info
vmware_vm_info
Follow-up to #1141
> Prune references to old facts from new info modules

- changelogs/fragments/vmware_cluster-remove-deprecated-features.yml
- plugins/modules/vmware_cluster.py
DRS, HA and VSAN configuration have been deprecated in ``vmware_cluster``  in favour of ``vmware_cluster_drs``, ``vmware_cluster_ha`` and ``vmware_cluster_vsan`` (see ansible/ansible#58468, #47 and ansible/ansible#68175). I think it's time to remove them.
vmware_cluster
> vmware_cluster: Remove deprecated features

- changelogs/fragments/vmware_dvs_portgroup-portgroup_type.yml
- plugins/modules/vmware_dvs_portgroup.py
- tests/integration/targets/prepare_vmware_tests/tasks/setup_dvs_portgroup.yml
- tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
- tests/integration/targets/vmware_dvs_portgroup_find/tasks/main.yml
- tests/integration/targets/vmware_dvs_portgroup_info/tasks/main.yml
- tests/integration/targets/vmware_guest/tasks/network_with_dvpg.yml
- tests/integration/targets/vmware_guest/tasks/network_with_portgroup.yml
- tests/integration/targets/vmware_guest_network/tasks/main.yml
- tests/integration/targets/vmware_migrate_vmk/tasks/main.yml
- tests/integration/targets/vmware_vspan_session/tasks/main.yml
Remove the deprecated parameter ``portgroup_type``.
#743
#1071
#1136
> vmware_dvs_portgroup: Remove portgroup_type

- changelogs/fragments/vmware_export_ovf.yml
- plugins/modules/vmware_export_ovf.py
There is known issue of if there is no extra config in ovf, then when template imported to Fusion, it may encounter GOS can not boot up issue.
So add a new parameter `export_with_extraconfig` in this module to contain VM extra config options in ovf file when exporting to template.
vmware_export_ovf
```paste below
```
> vmware_export_ovf: add export with extra config support

- changelogs/fragments/disutils.version.yml
- plugins/module_utils/version.py
- plugins/modules/vmware_category.py
- plugins/modules/vmware_vc_infraprofile_info.py
distutils has been deprecafed and will be removed from
Python's stdlib in Python 3.12 (see https://python.org/dev/peps/pep-0632).
This PR replaces the use of distutils.version.LooseVersion and distutils.version.StrictVersion
with LooseVersion from the vendored copy of distutils.version
included with ansible-core 2.12 (ansible/ansible#74644) if available,
and falls back to distutils.version for ansible-core 2.11 and before.
Since ansible-core 2.11 and earlier do not support Python 3.12 (since
they use LooseVersion itself in various places), this incomplete fix
should be OK for now. Also, the way this PR works (by adding a new
module_utils version that abstracts away where LooseVersion comes from),
it is easy to also fix this for ansible-core 2.11 and earlier later on.
Signed-off-by: …
> Prepare for distutils.version being removed in Python 3.12

- docs/docsite/rst/vmware_scenarios/scenario_clone_template.rst
I was directed to this repository from the main Ansible repository after creating my original [PR #76633](https://github.com/ansible/ansible/pull/76633)
Minor documentation fixes:
- Added a colon before introducing a list.
- Added periods for full sentences in a list.
`docs/docsite/rst/scenario_guides/vmware_scenarios/scenario_clone_template.rst`
N/A
> Fixed minor typos in scenario_clone_template.rst

- changelogs/fragments/25-vmware_guest_network-catch_taskerror.yml
- plugins/modules/vmware_guest_network.py
In rare cases, `wait_for_task` throws a `TaskError`. But since vmware_guest_network only catches `vim.fault.InvalidDeviceSpec` and `vim.fault.RestrictedVersion` the module will crash instead of just fail.
Fixes #25
This happens when people try to manually set a MAC address from the [reserved](https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.troubleshooting.doc/GUID-7F723748-E7B8-48B9-A773-3822C514684B.html) range `00:50:56:40:YY:ZZ` - `00:50:56:7F:YY:ZZ` but there might be other scenarios crashing the module because of the uncaught exception.
> vmware_guest_network: Fix uncaught exception

- changelogs/fragments/1080-add-sr-iov-advanced-options.yml
- plugins/module_utils/vm_device_helper.py
A very basic patch to add support for configuring the device backing of a SR-IOV device.
vmware_guest: Add the following options to a network interface definition, which are to be used for a sriov device : 
- allow_gest_os_mtu_change
- physical_function_backing
- virtual_function_backing
Initial module behavior would be to assign the first physical hardware available from the network port group. However, I have a scenario where I need to connect one VM to two different physical network interfaces for redundancy purposes, as they are connected to different network equipments.
Therefore, I want to be able to request that SR-IOV NIC 1 is connected to 0000:5d:00.0 and NIC 2 is connected to 0000:5d:00.1, for instance.
I eventually plan on implementing a lookup feature to …
> Add support for configuring SR-IOV advanced options on a network interface in a VM

- tests/integration/targets/vmware_content_library_manager/aliases
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1278
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1279
The test is not super stable and this impact the CI.
> tests: disable vmware_content_library_manager for now

- tests/integration/targets/vmware_content_library_manager/aliases
We increased the memory of the VCSA instance to 32GB and the stability
is much better.
This reverts commit ec583c02f55ec25a131cc9c25461c4924eab9dbf.
> Revert "tests: disable vmware_content_library_manager for now (#1172)"

- README.md
- changelogs/fragments/1182_ansible_version.yml
- meta/runtime.yml
I'd like to change the supported ansible version in order to avoid #1177. Anyway, I think it's time to get rid of ansible 2.9 and 2.10.
See #1182 for more information. But since this PR looks somehow broken, I'm trying to open a new one.
> Change required ansible version to 2.11.0

- docs/community.vmware.vmware_resource_pool_module.rst
- plugins/modules/vmware_resource_pool.py
Make it clear that "cluster", "esxi_hostname" and "parent_resource_pool" are mutually exclusive parameters.
Given the current documentation it's not clear that one cannot use more than one of these parameters at a time.
community.vmware.vmware_resource_pool
> Specify mutual exclusion of parameters

- docs/community.vmware.vmware_host_user_manager_module.rst
- plugins/modules/vmware_host_user_manager.py
- tests/integration/targets/vmware_host_user_manager/aliases
- tests/integration/targets/vmware_host_user_manager/tasks/main.yml
- tests/integration/targets/vmware_host_user_manager/tasks/operate_user_via_ESXi.yml
- tests/integration/targets/vmware_host_user_manager/tasks/operate_user_via_vcenter.yml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1282
This module can be added or updated or deleted the local user of ESXi via vCenter.
issues: https://github.com/ansible-collections/community.vmware/issues/1066
docs/community.vmware.vmware_host_user_manager_module.rst
plugins/modules/vmware_host_user_manager.py
tests/integration/targets/vmware_host_user_manager/aliases
tests/integration/targets/vmware_host_user_manager/tasks/main.yml
tests/integration/targets/vmware_host_user_manager/tasks/operate_user_via_ESXi.yml
tests/integration/targets/vmware_host_user_manager/tasks/operate_user_via_vcenter.yml
tested on vCenter/ESXi 7.0.1
> Add vmware_host_user_manager to manage the local user in ESXi

- changelogs/fragements/datastore_url-added-to-vm_info.yaml
- plugins/modules/vmware_vm_info.py
Build a list out of the datastore object inside of vm object and output with the other infos. This is useful for getting some data for building and managing drs groups for all vms inside one or multiple clusters.
datastore_url support for vmware_vm_info
The following example snippet will be inside of every vm output.
```paste below
"datastore_url": [
{
"name": "t880-o2g",
"url": "/vmfs/volumes/e074264a-e5c82a58"
}
],
```
> add datastore_url to vm output from vm_info module

- changelogs/fragments/vmware_vm_config_option.yml
- plugins/modules/vmware_vm_config_option.py
When connecting to ESXi host directly instead of vCenter, there is issue returned when specify `hardware_version` parameter:
```
"msg": "A specified parameter was not correct: "
```
```paste below
```
> vmware_vm_config_option: fix parameter not correct issue when connecting to ESXi host

- changelogs/fragments/1203-vmware_guest_storage_policy-controller_number-param.yml
- docs/community.vmware.vmware_guest_storage_policy_module.rst
- plugins/modules/vmware_guest_storage_policy.py
- tests/integration/targets/vmware_guest_storage_policy/tasks/main.yml
Fixes [#1203](https://github.com/ansible-collections/community.vmware/issues/1203) - vmware_guest_storage_policy missing SCSI controller parameter
community.vmware.vmware_guest_storage_policy
```paste below
```
> Added support for multiple SCSI controllers

- changelogs/fragments/remove_pre-collection_version_added.yml
- plugins/doc_fragments/vmware.py
- plugins/inventory/vmware_vm_inventory.py
`plugins/inventory/vmware_vm_inventory.py`and `plugins/doc_fragments/vmware.py` have a `version_added` of 2.something. This refers to the Ansible version. Now that the collection is version 2, I think this will create misunderstandings in the future. So I'd like to remove them.
> Remove pre-collection version_added documentation

- plugins/module_utils/vmware.py
- plugins/modules/vcenter_standard_key_provider.py
Add a new module `vcenter_standard_key_provider` for adding, reconfiguring, removing standard key provider on vCenter server.
```paste below
```
> Add new module vcenter_standard_key_provider

- changelogs/fragments/1176-vmware_dv_portgroup.yml
- plugins/modules/vmware_object_role_permission.py
Fixes https://github.com/ansible-collections/community.vmware/issues/1175 - Include DistributedVirtualPortgroup to community.vmware.vmware_object_role_permission object_type
community.vmware.vmware_object_role_permission
```paste below
```
> added DistributedVirtualPortgroup object_type

- tests/integration/targets/inventory_vmware_host_inventory/runme.sh
- tests/integration/targets/inventory_vmware_vm_inventory/aliases
- tests/integration/targets/inventory_vmware_vm_inventory/runme.sh
- tests/integration/targets/vmware_vm_inventory/ansible.cfg
`jsonfile` moved back into core: https://github.com/ansible/ansible/pull/69337
I found another problem here:
https://github.com/ansible-collections/community.vmware/blob/3cdff25220e132b62418db4b78a977bd3a399cd1/tests/integration/targets/inventory_vmware_vm_inventory/runme.sh#L47-L49
You see, `tomli` is installed as a requirement. But that makes `pip list | grep toml` evaluate to true and execute ansible-inventory with the `--toml` parameter. Which fails because ansible-inventory requirement `toml` is missing.
Fixes #1219 
tests/integration/targets/inventory_vmware_host_inventory/runme.sh
tests/integration/targets/inventory_vmware_vm_inventory/runme.sh
tests/integration/targets/vmware_vm_inventory/ansible.cfg
Hopefully fixes some CI failures like #1226.
> Remove FQCN from jsonfile plugin in tests

- tools/prepare_release.yml
I think we have a bug creating the new version running `tools/prepare_release.yml`. At the moment, we use the _last_ tag as the basis for the new version:
https://github.com/ansible-collections/community.vmware/blob/89695ca1fff52435f385223e4fd024b0acb16e90/tools/prepare_release.yml#L3-L7
Now that the latest tag is 1.17.1, this gives 1.18.0 when used in the main branch instead of 2.1.0.
I think we can fix this by using the `--merged` parameter. As far as I understand, the `1.17.1` tag wouldn't turn up then because the tagged commit isn't part of the main branch.
tools/prepare_release.yml
I think the bug would work the other way, too. If we release 2.1.0 and then want to release 1.18.0 in the `stable-1.x` branch, we would generate 2.2.0.
> Fix getting the next release

- changelogs/fragments/fix_shutdownguest_state_idempotency.yml
- plugins/module_utils/vmware.py
The `shutdownguest` power state is not idempotent.\
Running a play twice results in `"Virtual machine XXX must be in poweredon state for guest shutdown/reboot"` error message while the second run shouldn't do anything as the VM is already powered  off.
vmware_guest_powerstate
> vmware_guest_powerstate - fix `shutdownguest` is not idempotent

- plugins/inventory/vmware_host_inventory.py
- plugins/inventory/vmware_vm_inventory.py
- tests/sanity/ignore-2.13.txt
- tests/sanity/ignore-2.14.txt
With ansible-core 2.13, there are some new sanity tests that fail (https://github.com/ansible/ansible/pull/77268?).
vca_fw
vca_nat
As an example, see [this CI run](https://github.com/ansible-collections/community.vmware/pull/1192#issuecomment-1079617226).
_edit:_ Now that the ansible-core `stable-2.13` branch exists and the `devel` branch has been updated to `2.14.0.dev0`, I've also added `tests/sanity/ignore-2.14.txt`. ansible-collections/news-for-maintainers#13
> Fix sanity tests

- changelogs/fragments/1236-vmware_vmotion-svmotion_without_resourcepool.yml
- plugins/modules/vmware_vmotion.py
The Example Below didn't work:
- name: Perform storage vMotion of virtual machine
community.vmware.vmware_vmotion:
hostname: '{{ vcenter_hostname }}'
username: '{{ vcenter_username }}'
password: '{{ vcenter_password }}'
vm_name: 'vm_name_as_per_vcenter'
destination_datastore: 'destination_datastore_as_per_vcenter'
With removing this from the code it works:
if self.resourcepool_object is None:
self.module.fail_json(msg="Unable to find destination resource pool object which is required")
wmware_vmotion.py
```paste below
```
> Bugfix vmware_vmotion: Only Storage vmotion

- plugins/modules/vmware_guest_powerstate.py
The examples in `vmware_guest_powerstate` should use the FQCN.
Fixes #1253
vmware_guest_powerstate
> vmware_guest_powerstate: Use FQCN in examples

- changelogs/fragments/1238-vmware_guest_powerstate-ignore_trailing_slash_in_folder.yml
- plugins/modules/vmware_guest_powerstate.py
- tests/integration/targets/vmware_guest_powerstate/tasks/main.yml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1478
Other `vmware_guest` modules ignore a trailing `/` in the folder parameter, but `vmware_guest_powerstate ` doesn't. For a consistent user experience, it should do this also.
Fixes #1238
vmware_guest_powerstate
As an example, see `vmware_guest_snapshot`:
https://github.com/ansible-collections/community.vmware/blob/fd46931c7f38effa7d0a28844a1e94ea395374ff/plugins/modules/vmware_guest_snapshot.py#L437-L440
> vmware_guest_powerstate: Ignore trailing slash in folder parameter

- changelogs/fragments/1286-vmware_dvs_portgroup-fix_idempotency.yml
- plugins/modules/vmware_dvs_portgroup.py
The parameter `num_ports` in `vmware_dvs_portgroup` is not required, but always used to test if a change is needed. This code will always trigger a change since `None` is different from the current number of ports, which is an integer:
https://github.com/ansible-collections/community.vmware/blob/5c15e5504d76ae36e35ccf79bef0d586f72f5c33/plugins/modules/vmware_dvs_portgroup.py#L711-L713
> vmware_dvs_portgroup: Fix idempotency

- changelogs/fragments/1299-vnware_host_powerstate-fix_check_mode.yml
- plugins/modules/vmware_host_powerstate.py
In `check_mode`the module  `vmware_host_powerstate` triggers the reboot, etc.
It just does not wait for the task to be done.
vmware_host_powerstate
> vmware_host_powerstate: Do not execute the tasks in check mode

- changelogs/fragments/1297-vmware_migrate_vmk-add_vlan.yml
- plugins/modules/vmware_migrate_vmk.py
Add `migrate_vlan_id` parameter to use for the VMK interface when migrating from VSS to VDS.
Fixes #1297
> vmware_migrate_vmk: Add VLAN parameter

- changelogs/fragments/1298-vmware_vswitch-add_network_policy_support.yml
- plugins/modules/vmware_vswitch.py
- tests/integration/targets/vmware_vswitch/tasks/main.yml
Add support to manage `security`, `teaming` and `traffic shaping` policies on vSwitches.
- Fixes #1035 
- Fixes #1034 
- Fixes #203 
vmware_vswitch
> Update vmware_vswitch to support policies

- changelogs/fragments/1309-vmware_vswitch_info-add_network_policy_support.yml
- changelogs/fragments/1310-vmware_vswitch_info-add_network_policy_support.yml
- plugins/modules/vmware_vswitch_info.py
- tests/integration/targets/vmware_vswitch_info/tasks/main.yml
Adds a `policies` parameter, like `vmware_portgroup_info` to return additional information about the network policies.
vmware_vswitch_info
> vmware_vswitch_info: Add support to return information about policies

- plugins/inventory/vmware_vm_inventory.py
Add a documentation example for selecting a specific NIC when multiple NICs are attached to a VM
Fixes #1008
> Add a documentation example for selecting a specific NIC

- changelogs/fragments/1283-vmware_vm_info-allocaded_storag_cpu_memory_output.yaml
- plugins/modules/vmware_vm_info.py
Add allocated Storage, CPU and Memory to output
Feature Pull Request
vmware_vm_info.py
> vmware_vm_info: Add allocated Storage, CPU and Memory to output

- README.md
- galaxy.yml
- tools/prepare_release.yml
Some people want to install this collection directly from GitHub, but this fails because `version` is missing in `galaxy.yml`.
This PR tries to fix this by:
- adding `version: null` to `galaxy.yml` (I would have preferred `version: devel` but got an error about semantic versioning)
- set the correct version in the `prepare_release.yml` playbook
- document that after releasing the version should be reverted back to `null`
Unfortunately, the last is an additional manual step. But I think it important to distinguish between "real" releases and soomething that's been created directly from the main branch and might include additional commits.
galaxy.yml
- #666 
- #758 
- #1232
> Add version to galaxy.yml

- README.md
- tools/unset_version.yml
This is a follow-up to #1320 adding a playbook to unset the version in `galaxy.yml` after a new release.
galaxy.yml
README.md
tools/unset_version.yml
> Add playbook to revert version to null

- galaxy.yml
This is a follow-up tp #1320 moving `version` to a better place in `galaxy.yml`.
galaxy.yml
I've just added `version: null` somewhere to make it work, but it's probably better placed _after_ this comment:
```
```
> galaxy.yml: Mover version below comment

- changelogs/fragments/1240-vmware_vmotion-add_cluster_storage_cluster.yaml
- plugins/modules/vmware_vmotion.py
Add the possibility to use cluster and datastore cluster (storage pods).
So DRS will tell the best host to move the vm and a ds will selected form the  datastore cluster. 
Build on the Bugfix #1236.
vmware_vmotion
The return also chaned. 
Storage and Host will be returnd.
> vmware_vmotion: Add cluster and datastore cluster

- changelogs/fragments/1337_vmware_host_vmnic_info-fix_disconnected.yml
- plugins/modules/vmware_host_vmnic_info.py
- tests/integration/targets/vmware_host_vmnic_info/tasks/main.yml
`vmware_host_vmnic_info` breaks if a host is offline / disconnected / shut down.
vmware_host_vmnic_info
[this](https://github.com/ansible-collections/community.vmware/pull/318#issuecomment-1143769236) comment
> vmware_host_vmnic_info: Fix issue with offline / disconnected / shut down hosts

- changelogs/fragments/1270-vmware_cfg_backup-failed_to_write_backup_file.yaml
- plugins/modules/vmware_cfg_backup.py
It seems like the URL returned from `self.host.configManager.firmwareSystem.BackupFirmwareConfiguration()` returns the url with `http://` instead of `https://` and does not take the port into consideration. I tested it with the `save_configuration()` method and the fix works for my environment. Because of time I did not test the other methods, but the fix could be applied as well probably. Maybe this only solves the symptoms and not the cause, I do not know the **pyvmomi** and the rest of the dependencies that well...
Fixes #1270
`vmware_cfg_backup`
```paste below
diff --git a/plugins/modules/vmware_cfg_backup.py b/plugins/modules/vmware_cfg_backup.py
index f347c37..04388a5 100644
--- a/plugins/modules/vmware_cfg_backup.py
+++ b/plugins/modules/vmware_cfg_backup.py …
```
> fix replace http with https when using port 443

- changelogs/fragments/184_vmware_host_facts.yml
I think PR #1329 should be better classified as a bugfix, not a minor change.
> PR 1329: Bugfix instead of minor change

- changelogs/fragments/184_vmware_host_facts.yml
- plugins/modules/vmware_host_facts.py
- tests/integration/targets/vmware_host_facts/aliases
- tests/integration/targets/vmware_host_facts/tasks/main.yml
Backport PR #1329 to `stable-1`.
> Backport PR #1329 to stable-1

- README.md
I think we should extend the support for version 2 of `community.vmware` to November 2023.
README.md
I'd like to release version 3 in time for Ansible (community package) 7.0.0. I'd also like to drop support for ansible-core below 2.14 then.
At the moment, we have a gap here. If `community.vmware` version 2 goes EOL in May and people have to, for whatever reason, stay on ansible-core 2.12or 2.13, they could only use version 2 of this collection. Which would be EOL after May 2023.
In the long run, I'd like to release a new major version of this collection for every major ansible-core / Ansible community package release dropping support for older ansible-core versions.
I think this PR makes it easier to synchronize with ansible-core / Ansible community package.
> Set version 2 EOL to Nov 2023

- changelogs/fragments/1321-vmware_vm_info-allocaded_storag_cpu_memory_output.yaml
- plugins/modules/vmware_guest_disk.py
The get_recommended_datastore from the vmware_guest_disk filters out
datastores using the one with the greater amount of free space.
However, it doesn't check the datastore status (eg. inMaintenance).
When running the task on an SDRS cluster, which have a datastore in
maintenance, and that datastore is the one with the greater amount of
free space, the module fails with a pyvmomi error like:
"This operation is not allowed in the current state of the datastore".
This commit ensure to skip the selection of in-maintenance datastores by
not even checking their size, and exclude them immediately.
Avoid recommending in-maintenance datastores when trying to create
a disk with vmware_guest_disk.
(Not able to find issues reported for this error, but IIRC I've seen at least one
in the previous …
> vmware_guest_disk: Avoid using in maintenance DS

- changelogs/fragments/1321-vmware_vm_info-allocaded_storag_cpu_memory_output.yaml
- plugins/modules/vmware_guest_disk.py
Backport #1321
Avoid recommending in-maintenance datastores when trying to create a disk with vmware_guest_disk.
> Backport vmware_guest_disk: Avoid using in maintenance DS

- plugins/modules/vmware_content_deploy_ovf_template.py
- plugins/modules/vmware_content_deploy_template.py
Fixes #1290
The two template deployment modules both require cluster and host when attempting to identify a resource pool. I have removed that constraint, as the lookup function defaults cluster and host to None if not provided.
> ISSUE-1290 Remove cluster host fm Pools

- plugins/modules/vmware_guest_network.py
replaced one occurrence of allowGuesOSMtuChange with allowGuestOSMtuChange
Typo in code causes error when creating SRIOV NIC
plugins/modules/vmware_guest_network.py
> fixed typo related to guest MTU

- README.md
Now that Ansible 6.0.0 is released, the [original link](https://docs.ansible.com/ansible/latest/dev_guide/platforms/vmware_guidelines.html) just redirects people to the [new location](https://docs.ansible.com/ansible/latest/collections/community/vmware/docsite/dev_guide.html). I think we should spare people the extra click.
README.md
ansible/ansible#77723
> Update link to dev guide

- plugins/modules/vmware_guest_network.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1580
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1582
Received an error when trying to set up SRIOV: 
`AttributeError: type object 'vim.vm.device.VirtualPCIPassthrough' has no attribute 'DeviceBacking'`
According to the docs as well, there is no attribute on VirtualPCIPassthrough named DeviceBacking https://vdc-repo.vmware.com/vmwb-repository/dcr-public/3325c370-b58c-4799-99ff-58ae3baac1bd/45789cc5-aba1-48bc-a320-5e35142b50af/doc/vim.vm.device.VirtualDevice.html#backing 
I believe the intent was to compare the nic backing to the VirtualPCIPassthrough device itself. After making this change, the module seems to work correctly for me
plugins/modules/vmware_guest_network.py
> fix type issue with VirtualPCIPassthrough

- changelogs/fragments/1354-vmware_guest_instant_clone.yml
- plugins/modules/vmware_guest_instant_clone.py
This PR will support FQPN in the folder parameter the vmware_guest_instant_clone module has.
fixes: https://github.com/ansible-collections/community.vmware/issues/1353
plugins/modules/vmware_guest_instant_clone.py
I tested the below 3 patterns of folder path based on the base-playbook.  
I confirmed the patterns worked well.
```
1. folder: "/{{ datacenter }}/vm/"
2. folder: vm
3. folder: vm/sample
```
**base-playbook**
```yaml
---
connection: local
tasks:
- name: Instant Clone a VM
community.vmware.vmware_guest_instant_clone:
folder: "/{{ datacenter }}/vm/"
datastore: "{{ rw_datastore }}"
datacenter: "{{ …
```
> vmware_guest_instant_clone: Support FQPN of folder path

- changelogs/fragments/1382-vmware_guest_disk.yml
- plugins/modules/vmware_guest_disk.py
Add a new disk type for supporting add, reconfigure, remove vPMem disk like this:
```
- name: Add a new vPMem disk to virtual machine to SATA controller
community.vmware.vmware_guest_disk:
datacenter: "{{ datacenter_name }}"
validate_certs: no
name: VM_226
disk:
- type: vpmemdisk
size_gb: 1
state: present
controller_type: sata
controller_number: 1
unit_number: 2
register: disk_facts
```
```paste below
ok: [localhost] => {
"results": {
"changed": true,
"disk_changes": {
"0": "Disk created."
},
"disk_data": {
"0": {
"backing_datastore": "datastore4",
"backing_disk_mode": …
```
> Add support vPMem disk config in vmware_guest_disk module

- changelogs/fragments/1376-vmware_guest_sendkey-add-ctrl_x-support.yaml
- plugins/modules/vmware_guest_sendkey.py
When using sendkey module, an error message is raised.
This commit adds support for the CTRL_X binding.
Adds support for the CTRL_X key binding.
vmware_guest_sendkey
When using the module sendkey with CTRL_X binding, an error is raised.
You can reproduce it with the example below: 
```yaml
- name: Handle boot parameter interactively
vmware_guest_sendkey:
hostname: "{{ vcenter_host }}"
datacenter: "{{ vcenter_datacenter }}"
username: "{{ vcenter_user }}"
name: "{{ vm_hostname  }}"
keys_send:
- CTRL_X
```
```json
{ 
[...] 
"msg": "keys_send parameter: 'CTRL_x' in ['CTRL_x'] not supported."
}
```
> vmware_guest_sendkey: Add CTRL_X support

- tests/integration/targets/vmware_cfg_backup/aliases
- tests/integration/targets/vmware_cfg_backup/tasks/main.yml
We don't have any integration tests for `vmware_cfg_backup` yet.
vmware_cfg_backup
#28
> vmware_cfg_backup: Add integration tests

- tests/integration/targets/vmware_cfg_backup/tasks/main.yml
Add an integration test to backup configuration directly without going through vCenter.
vmware_cfg_backup
#1389
> vmware_cfg_backup: Add integration test without vCenter

- changelogs/fragments/1407-vmware_vm_info-inaccessible_vm.yml
- plugins/modules/vmware_vm_info.py
The module fails on inaccessible VMs with `'NoneType' object has no attribute 'datastoreUrl'`.
Fixes #1407
vmware_vm_info
> vmware_vm_info: Fix NoneType object has no attribute datastoreUrl for inaccessible VMs

- tests/integration/targets/vmware_host_logbundle/tasks/main.yml
It's rather comment to get a downlowd error. e.g:
```
Connection failure: The read operation timed out
```
> vmware_host_logbundle: retry on download error

- changelogs/fragments/1431-vmware_vswitch-fix_failback.yml
- plugins/modules/vmware_vswitch.py
When using `vmware_vswitch` module to set a vSwitch teaming failback mode, the actual operation is opposite of what's [documented](https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_vswitch_module.html#parameters).
`failback: no` actually sets vSwitch Failback=yes and vice versa.
Fixes #1431
vmware_vswitch
According to the [documentation](https://vdc-download.vmware.com/vmwb-repository/dcr-public/bf660c0a-f060-46e8-a94d-4b5e6ffc77ad/208bc706-e281-49b6-a0ce-b402ec19ef82/SDK/vsphere-ws/docs/ReferenceGuide/vim.host.NetworkPolicy.NicTeamingPolicy.html) rollingOrder works directly opposed to how people understand failback:
> For example, assume the explicit link order is (vmnic9, vmnic0), therefore vmnic9 goes down, vmnic0 comes up. However, when …
> vmware_vswitch: Fix the broken logic of the failback parameter

- changelogs/fragments/1440-vmware_cfg_backup-fails-to-restore-port-80-blocked.yaml
- plugins/modules/vmware_cfg_backup.py
It seems like the URL returned from `self.host.configManager.firmwareSystem.QueryFirmwareConfigUploadURL()` returns the url with `http://` instead of `https://` and does not take the port into consideration. I tested it with the load_configuration() method and the fix works for my environment. Similar to #1335 which was for save_configuration()
Fixes #1440 
`vmware_cfg_backup`
```paste below
diff --git a/plugins/modules/vmware_cfg_backup.py b/plugins/modules/vmware_cfg_backup.py
index bb9c863..1007a6b 100644
--- a/plugins/modules/vmware_cfg_backup.py
+++ b/plugins/modules/vmware_cfg_backup.py
@@ -135,6 +135,8 @@ class VMwareConfigurationBackup(PyVmomi):
url = self.host.configManager.firmwareSystem.QueryFirmwareConfigUploadURL()
url = url.replace('*', self.cfg_hurl)
+ …
```
> fix replace http with https for port 443 on cfg restore

- tests/integration/targets/vmware_guest_boot_manager/aliases
- tests/integration/targets/vmware_guest_boot_manager/tasks/main.yml
There are no integration tests for `vmware_guest_boot_manager` yet. This PR adds one, although it's still very simple.
vmware_guest_boot_manager
#28
I'll try to add another one when fixing #1257
> vmware_guest_boot_manager: Add initial integration test

- changelogs/fragments/1448-vmware_drs_group_manager-error_msg.yml
- plugins/modules/vmware_drs_group_manager.py
`vmware_drs_group_manager` raises exceptions instead of calling  `fail_json()`.
Additionally, if the DRS group doesn't exist the module fails with `'NoneType' object has no attribute 'vm'` or `'NoneType' object has no attribute 'host'` which isn't really helpful.
vmware_drs_group_manager
#1415
> vmware_drs_group_manager: Improve error handling

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
2.9.0 wasn't released correctly, some changes are missing from the package. Releasing 2.9.1 to fix this.
> prepare 2.9.1 release

- changelogs/fragments/1196-vsphere_copy-remove_deprecated_parameters.yml
- plugins/modules/vsphere_copy.py
Fixes #1196
The parameters `host` and `login` are deprecated and should be removed in version 3.
vsphere_copy
#1194
> vsphere_copy: Remove deprecated parameters

- changelogs/fragments/1268-vmware_vm_config_option-change_result.yml
- plugins/modules/vmware_vm_config_option.py
- tests/integration/targets/vmware_vm_config_option/tasks/main.yml
Change item names in result from strings joined with spaces to strings joined with underlines, e.g. `Guest fullname` will be changed to `guest_fullname`.
Fixes #1268
#1202
> vmware_vm_config_option: Change item names in result

- changelogs/fragments/1257-vmware_guest_boot_manager-remove_secure_boot_default.yml
- plugins/modules/vmware_guest_boot_manager.py
- tests/integration/targets/vmware_guest_boot_manager/tasks/main.yml
Fixes #1257
When using this module to enable `enter_bios_setup` on a VM with UEFI and Secure Boot enabled, it will disable Secure Boot. I think the best way to fix this is to _not_ have a default for `secure_boot_enabled `.
vmware_guest_boot_manager
See #1257 for more information.
> vmware_guest_boot_manager: Remove secure_boot_enabled default

- changelogs/fragments/1195-vmware_guest_network-remove_networks.yml
- plugins/modules/vmware_guest_network.py
- tests/integration/targets/vmware_guest_network/tasks/main.yml
Fixes #1195
The `networks` parameter is deprecated and should be removed.
https://github.com/ansible-collections/community.vmware/blob/67b9506a306da2caec9a2eda60003fd54a9df71e/plugins/modules/vmware_guest_network.py#L865-L871
> vmware_guest_network: Remove deprecated parameter networks

- changelogs/fragments/1196-vmware_host_firewall_manager-remove_deprecated_stuff.yml
- plugins/modules/vmware_host_firewall_manager.py
- tests/integration/targets/vmware_host_firewall_manager/tasks/main.yml
Fixes #1197
vmware_host_firewall_manager
https://github.com/ansible-collections/community.vmware/blob/ce764aaa1317960deeca086517e5f9d7e62f9cdd/plugins/modules/vmware_host_firewall_manager.py#L387-L395
and
https://github.com/ansible-collections/community.vmware/blob/ce764aaa1317960deeca086517e5f9d7e62f9cdd/plugins/modules/vmware_host_firewall_manager.py#L398-L406
> vmware_host_firewall_manager: Remove deprecated functionality

- changelogs/fragments/1265-vmware_tag_manager-set_idempotency.yml
- plugins/modules/vmware_tag_manager.py
- tests/integration/targets/vmware_tag_manager/tasks/cleanup.yml
- tests/integration/targets/vmware_tag_manager/tasks/main.yml
- tests/integration/targets/vmware_tag_manager/tasks/tag_manager_dict.yml
`vmware_tag_manager` isn't idempotent when using `state: set`.
Fixes #1265
https://github.com/ansible-collections/community.vmware/blob/fac9919fc3af36996173413c0c25bb816459f12a/plugins/modules/vmware_tag_manager.py#L339-L349
> vmware_tag_manager: Fix idempotency for state set

- plugins/modules/vcenter_domain_user_group_info.py
- plugins/modules/vmware_cluster_ha.py
- plugins/modules/vmware_content_deploy_ovf_template.py
- plugins/modules/vmware_content_deploy_template.py
- plugins/modules/vmware_content_library_manager.py
- plugins/modules/vmware_datastore_info.py
- plugins/modules/vmware_deploy_ovf.py
- plugins/modules/vmware_drs_group_manager.py
- plugins/modules/vmware_dvs_host.py
- plugins/modules/vmware_dvs_portgroup.py
- plugins/modules/vmware_dvs_portgroup_info.py
- plugins/modules/vmware_dvswitch.py
- plugins/modules/vmware_first_class_disk.py
- plugins/modules/vmware_guest.py
- plugins/modules/vmware_guest_controller.py
- plugins/modules/vmware_guest_cross_vc_clone.py
- plugins/modules/vmware_guest_disk.py
- plugins/modules/vmware_guest_info.py
- plugins/modules/vmware_guest_instant_clone.py
- plugins/modules/vmware_guest_network.py
- plugins/modules/vmware_guest_powerstate.py
- plugins/modules/vmware_guest_sendkey.py
Now that version 1 is nearly EOL, I don't think that it's important if something has been added in 1.2, 1.4, 1.7 or wherever.
vmware_guest_storage_policy
vmware_guest_tools_wait
vmware_guest_tpm
vmware_host_custom_attributes
vmware_host_datastore
vmware_host_iscsi
vmware_host_passthrough
vmware_host_scanhba
vmware_host_sriov
vmware_host_tcpip_stacks
vmware_object_custom_attributes_info
vmware_object_role_permission_info
vmware_recommended_datastore
vmware_resource_pool
vmware_vc_infraprofile_info
vmware_vmotion
vmware_vm_storage_policy
> Remove version_added: 1.x part 1

- plugins/modules/vmware_cluster_info.py
- plugins/modules/vmware_cluster_vsan.py
- plugins/modules/vmware_guest_storage_policy.py
- plugins/modules/vmware_guest_tools_wait.py
- plugins/modules/vmware_guest_tpm.py
- plugins/modules/vmware_host_custom_attributes.py
- plugins/modules/vmware_host_datastore.py
- plugins/modules/vmware_host_iscsi.py
- plugins/modules/vmware_host_passthrough.py
- plugins/modules/vmware_host_scanhba.py
- plugins/modules/vmware_host_snmp.py
- plugins/modules/vmware_host_sriov.py
- plugins/modules/vmware_host_tcpip_stacks.py
- plugins/modules/vmware_object_custom_attributes_info.py
- plugins/modules/vmware_object_role_permission_info.py
- plugins/modules/vmware_recommended_datastore.py
- plugins/modules/vmware_resource_pool.py
- plugins/modules/vmware_tag_manager.py
- plugins/modules/vmware_vc_infraprofile_info.py
- plugins/modules/vmware_vcenter_settings.py
- plugins/modules/vmware_vm_config_option.py
- plugins/modules/vmware_vm_storage_policy.py
- plugins/modules/vmware_vmotion.py
- plugins/modules/vmware_vsan_health_info.py
Now that version 1 is nearly EOL, I don't think that it's important if something has been added in 1.2, 1.4, 1.7 or wherever.
vmware_guest_storage_policy
vmware_guest_tools_wait
vmware_guest_tpm
vmware_host_custom_attributes
vmware_host_datastore
vmware_host_iscsi
vmware_host_passthrough
vmware_host_scanhba
vmware_host_sriov
vmware_host_tcpip_stacks
vmware_object_custom_attributes_info
vmware_object_role_permission_info
vmware_recommended_datastore
vmware_resource_pool
vmware_vc_infraprofile_info
vmware_vmotion
vmware_vm_storage_policy
> Remove version_added: 1.x part 2

- changelogs/fragments/1466-vmware_guest_disk-change_iolimit_without_size.yml
- plugins/modules/vmware_guest_disk.py
This commit adds `iolimit` modifications on an existing disk without changing size.
Backport of #1466
> vmware_guest_disk: Backport #1466

- changelogs/fragments/vmware_dvs_portgroup-securityPolicy.yml
- changelogs/fragments/vmware_dvs_portgroup_info-securityPolicy.yml
- changelogs/fragments/vmware_dvswitch-securityPolicy.yml
- changelogs/fragments/vmware_dvswitch_uplink_pg-securityPolicyOverrideAllowed.yml
- changelogs/fragments/vmware_vspan_session-securityPolicy.yml
- plugins/module_utils/vmware.py
- plugins/modules/vmware_dvs_portgroup.py
- plugins/modules/vmware_dvs_portgroup_info.py
- plugins/modules/vmware_dvswitch.py
- plugins/modules/vmware_dvswitch_uplink_pg.py
- plugins/modules/vmware_vspan_session.py
As of vSphere API 6.7, `securityPolicy` in [VMwareDVSPortSetting (vim.dvs.VmwareDistributedVirtualSwitch.VmwarePortConfigPolicy)](https://vdc-download.vmware.com/vmwb-repository/dcr-public/bf660c0a-f060-46e8-a94d-4b5e6ffc77ad/208bc706-e281-49b6-a0ce-b402ec19ef82/SDK/vsphere-ws/docs/ReferenceGuide/vim.dvs.VmwareDistributedVirtualSwitch.VmwarePortConfigPolicy.html) and `securityPolicyOverrideAllowed` in [VMwareDVSPortgroupPolicy (vim.dvs.VmwareDistributedVirtualSwitch.VMwarePortgroupPolicy)](https://vdc-download.vmware.com/vmwb-repository/dcr-public/bf660c0a-f060-46e8-a94d-4b5e6ffc77ad/208bc706-e281-49b6-a0ce-b402ec19ef82/SDK/vsphere-ws/docs/ReferenceGuide/vim.dvs.VmwareDistributedVirtualSwitch.VMwarePortgroupPolicy.html) are deprecated. Instead, `macManagementPolicy` and …
> [WIP] securityPolicy: Deprecated as of vSphere API 6.7

- changelogs/fragments/3.0.0-required_ansible_version.yml
- meta/runtime.yml
- tests/sanity/ignore-2.12.txt
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1647
3.0.0 won't support ansible-core < 2.13.0.
> 3.0.0: Removing support for ansible-core version < 2.13.0

- changelogs/fragments/1483-vmware_dvs_portgroup.yml
- plugins/modules/vmware_dvs_portgroup.py
- tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
- tests/integration/targets/vmware_vspan_session/tasks/main.yml
Apart from the things that are specific to a portgroup (like, for example, its name) there are a lot of settings that could either be inherited from the switch or defined at the PG level.
Most, if not all, parameters of the module don't allow this: They have defaults which means the settings from the switch are always overwritten. Or they implicitly set something to inherited if the parameter is unset. This is a problem because people can't use the module in a way of "I don't care about this setting, just leave it as it is" manner or explicitly state that this setting should be inherited.
#1316
> vmware_dvs_portgroup : Remove defaults and add explicit inheritance from switch defaults

- changelogs/fragments/1195-vmware_guest_network-remove_networks.yml
- changelogs/fragments/1196-vmware_host_firewall_manager-remove_deprecated_stuff.yml
- changelogs/fragments/1196-vsphere_copy-remove_deprecated_parameters.yml
- changelogs/fragments/1257-vmware_guest_boot_manager-remove_secure_boot_default.yml
- changelogs/fragments/1483-vmware_dvs_portgroup.yml
- changelogs/fragments/remove_deprecated_dns_config_module.yml
- changelogs/fragments/remove_deprecated_vmware_guest_vnc_module.yml
Update changelog fragments for a better porting guide
vsphere_copy
vmware_dns_config
vmware_guest_boot_manager
vmware_guest_vnc
vmware_host_firewall_manager
#1456 
#1455 
#1483 
#1461 
#1459 
#1454 
#1463
> Update changelog fragments for a better porting guide

- changelogs/fragments/1503-vmware_tag_manager-fix_performance_issue_during_tag_processing.yml
- plugins/module_utils/vmware_rest_client.py
- plugins/modules/vmware_tag_manager.py
Fixes #1503
This fix solves the performance issue during tag processing.
Signed-off-by: Christoph Fiehe <c.fiehe@eurodata.de>
Instead of iterating over the full set of available tags, it is possible to limit the requested set, so that only tags are returned that belong to the specified Category Id.
The performance issue is caused by this loop:
```
for tag_object in self.api_client.tagging.Tag.list():
[...]
```
It can be replaced by:
```
for tag_object in self.api_client.tagging.Tag.list_tags_for_category(category_id):
[...]
```
> Fixes #1503: vmware_tag_manager: Tag processing is very slow

- changelogs/fragments/1501-vmware_tag_manager-Fix_failure_when_changing_single_cardinal_tag_category.yml
- plugins/modules/vmware_tag_manager.py
This pull request fixes #1501 and ensures that the value of a single cardinal tag category can be modified without any issue.
Signed-off-by: Christoph Fiehe <c.fiehe@eurodata.de>
The correct behavior can be easily ensured by changing the order of tag addition and tag removal. At first, you have to remove the tags that are not longer part of the target state and add the new tags afterwards. The issue arises because the tags got added first, resulting in a cardinality violation for single cardinal tag categories.
> Fixes #1501: vmware_tag_manager: Changing the value of a single cardinal tag category fails with 'Tagging cardinality violation'

- changelogs/fragments/1514-vmware_host_lockdown-remove-deprecated-api-calls.yml
- plugins/modules/vmware_host_lockdown.py
- tests/integration/targets/vmware_host_lockdown/tasks/main.yml
As @Kloppi313 [pointed out](https://github.com/ansible-collections/community.vmware/issues/529#issuecomment-735776791), `vmware_host_lockdown` uses API functions that have been deprecated since vSphere 6.0.
Additionally, I'm implementing the ability to enable strict lockdown mode.
vmware_host_lockdown
I've also added two new choices for `state`, `disabled` and `normal`, to replace `absent` and `present` which I plan to remove in the next major release.
> vmware_host_lockdown: Use current API

- changelogs/fragments/1323-vmware_guest_file_operation.yml
- plugins/modules/vmware_guest_file_operation.py
If a timeout occurs during to fetch or copy of a file, the error is displayed with vmware_guest_file_operation module.
```
TASK [test] **********************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "problem during file transfer, http message:{'url': 'https://esxi-05.homelab:443/guestFile?id=266&token=52a2c34f-349f-a6fe-9b71-ce9ac9066ee2266', 'status': -1, 'msg': 'Request failed: <urlopen error The write operation timed out>'}", "uuid": "421a224e-f587-a9ff-0354-42b2d9949297"}
```
This PR adds the timeout parameter to resolve the above error.
fixes: …
> vmware_guest_file_operation: add a new parameter for timeout

- docs/community.vmware.vmware_category_info_module.rst
- docs/community.vmware.vmware_category_module.rst
- docs/community.vmware.vmware_content_deploy_ovf_template_module.rst
- docs/community.vmware.vmware_content_deploy_template_module.rst
- docs/community.vmware.vmware_content_library_info_module.rst
- docs/community.vmware.vmware_content_library_manager_module.rst
- docs/community.vmware.vmware_host_inventory_inventory.rst
- docs/community.vmware.vmware_object_rename_module.rst
- docs/community.vmware.vmware_tag_info_module.rst
- docs/community.vmware.vmware_tag_manager_module.rst
- docs/community.vmware.vmware_tag_module.rst
- docs/community.vmware.vmware_vc_infraprofile_info_module.rst
- docs/community.vmware.vmware_vm_inventory_inventory.rst
- plugins/doc_fragments/vmware_rest_client.py
- plugins/inventory/vmware_host_inventory.py
- plugins/inventory/vmware_vm_inventory.py
Now that version 1 is nearly EOL, I don't think that it's important if something has been added in 1.2, 1.4, 1.7 or wherever.
plugins/doc_fragments/vmware_rest_client.py
#1473
#1474
> Remove version_added 1.x from doc_fragments in inventory

- changelogs/fragments/1522-vmware_dvs_portgroup.yml
- plugins/modules/vmware_dvs_portgroup.py
Fixes #1522 
If `check_dvspg_state()` returns `update`, this might crash the module if the `state` is set to `absent`. This is because `dvspg_states['absent']['update']` doesn't exist.
In that case, the module should just remove the portgroup.
https://github.com/ansible-collections/community.vmware/blob/0ff50e5f2b62a5571da4d79338b2809f6b982655/plugins/modules/vmware_dvs_portgroup.py#L658-L671
> vmware_dvs_portgroup: Fix deleting portgroups

- changelogs/fragments/1522-vmware_dvs_portgroup.yml
- plugins/modules/vmware_dvs_portgroup.py
Backport #1523 
If `check_dvspg_state()` returns `update`, this might crash the module if the `state` is set to `absent`. This is because `dvspg_states['absent']['update']` doesn't exist.
In that case, the module should just remove the portgroup.
https://github.com/ansible-collections/community.vmware/blob/6364b294a281dcbcb0b2a8b7d8bd8317fbc0f355/plugins/modules/vmware_dvs_portgroup.py#L628-L641
> 2.x: vmware_dvs_portgroup: Fix deleting portgroups

- plugins/modules/vcenter_standard_key_provider.py
- plugins/modules/vmware_content_library_manager.py
- plugins/modules/vmware_dvs_host.py
- plugins/modules/vmware_dvswitch_lacp.py
- plugins/modules/vmware_dvswitch_nioc.py
- plugins/modules/vmware_guest.py
- plugins/modules/vmware_guest_sendkey.py
- plugins/modules/vmware_host_active_directory.py
- plugins/modules/vmware_host_snmp.py
Fix various non-matching `default` values exposed by ansible/ansible#79267.
vmware_dvs_host
vmware_dvswitch_lacp
vmware_dvswitch_nioc
vmware_guest
vmware_guest_sendkey
vmware_host_active_directory
> Fix non-matching defaults in docs

- plugins/modules/vcenter_standard_key_provider.py
- plugins/modules/vmware_content_library_manager.py
- plugins/modules/vmware_dvs_host.py
- plugins/modules/vmware_dvswitch_lacp.py
- plugins/modules/vmware_dvswitch_nioc.py
- plugins/modules/vmware_guest.py
- plugins/modules/vmware_guest_network.py
- plugins/modules/vmware_guest_sendkey.py
- plugins/modules/vmware_host_active_directory.py
- plugins/modules/vmware_host_snmp.py
Fix various non-matching `default` values exposed by ansible/ansible#79267.
vmware_dvs_host
vmware_dvswitch_lacp
vmware_dvswitch_nioc
vmware_guest
vmware_guest_sendkey
vmware_host_active_directory
Backport #1530
> 2.x: Fix non-matching defaults in docs

- changelogs/fragments/1532-vmware_guest_custom_attributes.yml
- plugins/modules/vmware_guest_custom_attributes.py
- tests/integration/targets/vmware_guest_custom_attributes/tasks/main.yml
The same function executes when the state is present and absent in vmware_guest_custom_attributes module.  
I didn't think it was good code, so I refactored the function to split it for each purpose.  
And added the return value for diff as we can be checked the custom attribute difference.
related: https://github.com/ansible-collections/community.vmware/issues/1484
plugins/modules/vmware_guest_custom_attributes.py
tests/integration/targets/vmware_guest_custom_attributes/tasks/main.yml
changelogs/fragments/1532-vmware_guest_custom_attributes.yml
tested on VCSA 7.0.0
> vmware_guest_custom_attributes: Improve the code quality and add the return value for the diff

- changelogs/fragments/1540-vmware_host_lockdown.yml
- plugins/modules/vmware_host_lockdown.py
Fix `AttributeError: 'VmwareLockdownManager' object has no attribute 'warn'` in `vmware_host_lockdown`.
vmware_host_lockdown
https://github.com/ansible-collections/community.vmware/blob/9ed11829dfeac42e3d1b32536f2cb2a51c805c83/plugins/modules/vmware_host_lockdown.py#L152
https://github.com/ansible-collections/community.vmware/blob/9ed11829dfeac42e3d1b32536f2cb2a51c805c83/plugins/modules/vmware_host_lockdown.py#L155
> vmware_host_lockdown: VmwareLockdownManager object has no attribute warn

- meta/runtime.yml
- plugins/modules/vmware_custom_attribute.py
- plugins/modules/vmware_custom_attribute_manager.py
- tests/integration/targets/vmware_custom_attribute/aliases
- tests/integration/targets/vmware_custom_attribute/tasks/main.yml
- tests/integration/targets/vmware_custom_attribute_manager/aliases
- tests/integration/targets/vmware_custom_attribute_manager/tasks/main.yml
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1688
Fixes #1250 
There's a generic module for gathering custom attribute info from all object types.
But there are no generic modules to _manage_  custom attributes on all object types. Just modules to manage custom attributes on VMs and ESXi hosts.
vmware_custom_attribute
vmware_custom_attribute_manager
> Generic modules for custom attributes

- changelogs/fragments/1544-vmware_portgroup_info.yml
- plugins/modules/vmware_portgroup_info.py
Backport #1546
In some cases, a portgroup might have `spec.policy.nicTeaming.failureCriteria` set, but without `checkBeacon`. This crashes the module.
vmware_portgroup_info
See #1544 for more information.
> Backport vmware_portgroup_info fix

- changelogs/fragments/1543-vmware_guest_boot_manager.yml
- changelogs/fragments/vmware_guest_boot_manager.yml
- plugins/modules/vmware_guest_boot_manager.py
- tests/integration/targets/vmware_guest_boot_manager/tasks/main.yml
Signed-off-by: Diane Wang <dianew@vmware.com>
1. For BIOS firmware VM, when add new hard disk to SATA controller, restart VM will result VM disk order changed and VM can not boot up automatically. So in this module, add a new parameter `boot_hdd_name` to specify boot from which hard disk.
2. Remove the default values of some parameters, if these parameters are not set in the task and previous VM config is not the same as the default value, then these VM config will be changed,  which is not expected.
vmware_guest_boot_manager
```paste below
- community.vmware.vmware_guest_boot_manager:
hostname: xx.xx.xx.xx
username: xxxxx
password: xxxxx
name: test_vm
boot_delay: 20000
enter_bios_setup: false
boot_retry_enabled: false
boot_retry_delay: 2200 …
```
> vmware_guest_boot_manager: Add a new parameter 'boot_hdd_name' to specify the boot disk name

- changelogs/fragments/1511-vmware_vm_info.yml
- plugins/modules/vmware_vm_info.py
Since the vm_info module does not get the resource pool of the virtual machines i have added that functionality.
The vm_info module now additionally fetches the resource pool of  the virtual machine, if available.
> Add resource pool of vm to vm_info output

- changelogs/fragments/1541-vmware_object_custom_attributes_info.yml
- plugins/modules/vmware_object_custom_attributes_info.py
- tests/integration/targets/vmware_object_custom_attributes_info/tasks/cleanup.yml
- tests/integration/targets/vmware_object_custom_attributes_info/tasks/main.yml
- tests/integration/targets/vmware_object_custom_attributes_info/tasks/pre.yml
- tests/integration/targets/vmware_object_custom_attributes_info/tasks/vmware_object_custom_attributes_info_tests.yml
Fix the bug that occurs the error if the custom attribute is the global type.
fixes: https://github.com/ansible-collections/community.vmware/issues/1477
changelogs/fragments/1541-vmware_object_custom_attributes_info.yml
plugins/modules/vmware_object_custom_attributes_info.py
tests/integration/targets/vmware_object_custom_attributes_info/tasks/main.yml
tests/integration/targets/vmware_object_custom_attributes_info/tasks/pre.yml
tests/integration/targets/vmware_object_custom_attributes_info/tasks/vmware_object_custom_attributes_info_tests.yml
tests/integration/targets/vmware_object_custom_attributes_info/tasks/cleanup.yml
tested on VCSA 7.0
> vmware_object_custom_attributes_info: Support the global type of custom attribute

- changelogs/fragments/1555-vmware_guest_instant_clone-pyvmomi_8_0_0_1.yml
- plugins/module_utils/vmware.py
Fixes #1555
pyVmomi 8.0.0.1 breaks `find_folder_by_fqpn` and, therefor, `vmware_guest_instant_clone`.
vmware_guest_instant_clone
See the fixed issue for more information.
> vmware_guest_instant_clone: Fix an issue with pyVmomi 8.0.0.1

- changelogs/fragments/1555-vmware_guest_instant_clone-pyvmomi_8_0_0_1.yml
- plugins/module_utils/vmware.py
Backport #1557
pyVmomi 8.0.0.1 breaks `find_folder_by_fqpn` and, therefor, `vmware_guest_instant_clone`.
vmware_guest_instant_clone
#1555
> 2.x: vmware_guest_instant_clone: Fix an issue with pyVmomi 8.0.0.1

- changelogs/fragments/1477-vmware_object_custom_attributes_info.yml
- plugins/modules/vmware_object_custom_attributes_info.py
Backport #1541
Fix the bug that occurs the error if the custom attribute is the global type.
vmware_object_custom_attributes_info
#1477
> 2.x: vmware_object_custom_attributes_info: Global custom attributes

- meta/runtime.yml
- plugins/modules/vmware_custom_attribute.py
- plugins/modules/vmware_custom_attribute_manager.py
Missing `version_added` in two modules and `runtime.yml` isn't correct, either.
vmware_custom_attribute
vmware_custom_attribute_manager
> Fixes 20221201

- changelogs/fragments/1542-vmware_cluster_drs.yaml
- plugins/modules/vmware_cluster_drs.py
- tests/integration/targets/vmware_cluster_drs/tasks/main.yml
Add predictive DRS Setting
And invert drs_vmotion_rate => same like in the vCenter
vmware_cluster_drs
```paste below
```
> vmware_cluster_drs - Add predictive DRS Setting

- changelogs/fragments/1578-vmware_tools-pyvmomi_8_0_0_1.yml
- plugins/connection/vmware_tools.py
Fixes #1578
[pyVmomi 8.0.0.1](https://github.com/vmware/pyvmomi/releases/tag/v8.0.0.1) removed `connect.SmartConnectNoSSL()` used in `plugins/connection/vmware_tools.py`.
vmware_tools
See the fixed issue for more information.
> vmware_tools: Fix an issue with pyVmomi 8.0.0.1

- changelogs/fragments/1578-vmware_tools-pyvmomi_8_0_0_1.yml
- plugins/connection/vmware_tools.py
[pyVmomi 8.0.0.1](https://github.com/vmware/pyvmomi/releases/tag/v8.0.0.1) removed `connect.SmartConnectNoSSL()` used in `plugins/connection/vmware_tools.py`.
vmware_tools
Backport of #1584 to fix #1578 in the `stable-2.x` branch.
> [BACKPORT] vmware_tools: Fix an issue with pyVmomi 8.0.0.1

- changelogs/fragments/1615-wrong_key_for_return_value.yml
- docs/community.vmware.vmware_guest_disk_module.rst
- plugins/modules/vmware_guest_disk.py
Fixes #1615
Update the documentation of vmware_guest_disk to show the correct key of the return values.
> Fix wrong key in the documentation of the return values

- changelogs/fragments/1615-wrong_key_for_return_value.yml
- docs/community.vmware.vmware_guest_disk_module.rst
- plugins/modules/vmware_guest_disk.py
Update the documentation of vmware_guest_disk to show the correct key of the return values.
Backport #1623
> Backport Fix wrong key in the documentation of the return values

- changelogs/fragments/1606-vmware_guest_custom_attributes.yml
- plugins/modules/vmware_guest_custom_attributes.py
Fixes #1606
Fixes #1568
Reversed the for loops in check_exists and bumped exception check into outer for loop for existing attributes. Tested against vSphere 7.0.3 and it set a list of attributes on a new VM without issue.
vmware_guest_custom_attributes
See Issue #1606 and Issue #1568 for details.
> Issue 1606 Fix vmware_guest_custom_attributes failing on new VMs with KeyError 'value'

- changelogs/fragments/1633-missing_quotation_mark.yml
- plugins/modules/vmware_object_rename.py
Add missing quotation mark to error message
Fixes #1633
vmware_object_rename
> Add missing quotation mark to error message

- changelogs/fragments/1629-vmware_vmotion.yml
- plugins/modules/vmware_vmotion.py
Add a parameter `timeout` to the `vmware_vmotion` module in order to allow vmotions running longer than 1 hour.
vmware_vmotion
#1612
> vmware_vmotion: Add timeout parameter

- plugins/inventory/vmware_vm_inventory.py
Add an example for using the groups parameter with Jinja2 conditionals.
vmware_vm_inventory 
I found that it wasn't very intuitive for me to use the groups parameter with actual conditions (not just 'true') correctly and I thought this might help some people.
Also I kind of dislike the parameter description itself, but that's coming from here:
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/doc_fragments/constructed.py#L25
I would like to append something along the lines of "[...] { group: condition }" - but whatever.. Even though I think that could be overwritten by this plugin, the example should suffice.
> vmware_vm_inventory: add example for groups parameter

- changelogs/fragments/1653-cross_vc_clone_ssl_thumbprint.yml
- plugins/modules/vmware_guest_cross_vc_clone.py
Fixes #1433 
Fixing behaviour of SSL Validation at destination host in cross_vc_clone module. Since it is possible to define to not perform ssl validation at destination VC, there is still an error, because serviceLocatorSpec wants a thumbprint, if this is not set, it throws and ssl validation error.
vmware_guest_cross_vc_clone
What I am doing to work around the limits of the serviceLocatorSpec, is to check if ssl should be validated, if not, I just fetch the thumbprint from the destination VC and inject it to the serviceLocatorSpec.
There is also another PR currently open (https://github.com/ansible-collections/community.vmware/pull/1608) which adds a thumbprint option, this is also a really good addition. May we should bring my change and the change of @ironbishop …
> fixing ssl validation behaviour

- changelogs/fragments/1660-false_instead_no_examples.yml
- docs/community.vmware.vmware_deploy_ovf_module.rst
- docs/community.vmware.vmware_guest_disk_module.rst
- docs/community.vmware.vmware_guest_file_operation_module.rst
- docs/community.vmware.vmware_guest_storage_policy_module.rst
- docs/community.vmware.vmware_guest_vgpu_info_module.rst
- docs/community.vmware.vmware_guest_vgpu_module.rst
- docs/community.vmware.vmware_host_datastore_module.rst
- docs/community.vmware.vmware_recommended_datastore_module.rst
- plugins/modules/vmware_deploy_ovf.py
- plugins/modules/vmware_guest_disk.py
- plugins/modules/vmware_guest_file_operation.py
- plugins/modules/vmware_guest_storage_policy.py
- plugins/modules/vmware_guest_vgpu.py
- plugins/modules/vmware_guest_vgpu_info.py
- plugins/modules/vmware_host_datastore.py
- plugins/modules/vmware_recommended_datastore.py
Use `false` instead of `no` in examples.
vmware_guest_file_operation
vmware_guest_storage_policy
vmware_guest_vgpu_info
vmware_guest_vgpu
vmware_host_datastore
vmware_recommended_datastore
#1660
> Use false instead of no in examples

- changelogs/fragments/1647-uuid_vmware_tools_connections.yml
- plugins/connection/vmware_tools.py
Adding support for UUID to connect to a VM via vmware_tools plugin.
Why is it useful.
This way vmware_tools connection Plugin ist better usable in conjunction with vmware_vm_inventory, since there is no attribute for guest_path in the attributes of a VM. This way you can use the "config.uuid" attribute to connect to multiple VM's in different folders fetched via vmware_vm_inventory.
We are using vmware_tools connection plugin to easier connect to windows VM, instead of using winRM which is much more complex.
vmware_tools connection plugin
Implemented the way, that the path still can be used of course and the path is preffered of both is defined. However added a mutually exclusive hint to the doc.
Successfully tested against our vsphere 7 U3 environment.
> adds uuid support for vmware_tools connection plugin

- plugins/modules/vmware_vsan_hcl_db.py
This module can be used to upload the HCL DB to an air-gapped vCenter instance.
vmware_vsan_hcl_db
> vmware_vsan_hcl_db: Add initial module

- changelogs/fragments/1223-cross_vc_clone_timeout.yml
- plugins/modules/vmware_guest_cross_vc_clone.py
Fixes #1223
Add a parameter timeout to the vmware_guest_cross_vc_clone module in order to allow cross vc clone running longer than 1 hour.
Reconnect to destination vc after the clone to avoid the "vim.fault.NotAuthenticated" issue when the clone is long
vmware_guest_cross_vc_clone
Improve the module to fix timeout and notauthenticated issues which happened when the clone take a lot of time.
Similar to #1629
> Module vmware_guest_cross_vc_clone - fix timeout and notauthenticated issue

- changelogs/fragments/1118-vmware_migrate_vmk.yml
- plugins/modules/vmware_migrate_vmk.py
- tests/integration/targets/vmware_migrate_vmk/aliases
- tests/integration/targets/vmware_migrate_vmk/tasks/main.yml
Fixes #1118
Enable integration tests for vmware_migrate_vmk again.
#1114
#1115
> vmware_migrate_vmk: Enable integration tests again

- changelogs/fragments/1682_vmware_vm_info
- plugins/modules/vmware_vm_info.py
Fixes #1682
add parameters for faster run:
* show_cluster=dict(type='bool', default=True),
* show_datacenter=dict(type='bool', default=True),
* show_datastore=dict(type='bool', default=True),
* show_esxi_hostname=dict(type='bool', default=True),
* show_mac_address=dict(type='bool', default=True),
* show_net=dict(type='bool', default=True),
* show_resource_pool=dict(type='bool', default=True),
community.vmware.vmware_vm_info
```paste below
```
> issue_1682_vmware_vm_info_more_show_parameters

- tests/integration/targets/vmware_host_tcpip_stacks/aliases
- tests/integration/targets/vmware_host_tcpip_stacks/tasks/main.yml
- tests/integration/targets/vmware_host_tcpip_stacks/tasks/post.yml
- tests/integration/targets/vmware_host_tcpip_stacks/tasks/pre.yml
- tests/integration/targets/vmware_host_tcpip_stacks/tasks/vmware_host_tcpip_stacks_tests.yml
Fixes #1120
Enable integration tests for vmware_host_tcpip_stacks again.
vmware_host_tcpip_stacks
#1121
> vmware_host_tcpip_stacks: Enable integration tests again

- tests/integration/targets/vmware_host_service_manager/aliases
Enable integration tests for vmware_host_service_manager again.
vmware_host_service_manager
#945
> vmware_host_service_manager: Enable integration tests again

- changelogs/1713-vmware_guest-custom_attributes_on_create.yaml
- plugins/modules/vmware_guest.py
Fixes issue where custom attributes were not getting set on VM creation.
- `plugins/modules/vmware_guest.py`
```paste below
```
> vmware_guest - set custom attributes on VM create

- changelogs/fragments/1706-vmware_vsan_health_info.yml
- plugins/modules/vmware_vsan_health_info.py
Fixes #1648
While the module description says that the return type should be a dict, it actually returns a JSON string
> fix(vmware_vsan_health_info): Return dict instead of JSON string

- changelogs/fragments/1715-requirements.yml
- requirements.txt
Pin `vsphere-automation-sdk` to v8.0.0.0 since newer releases require a pyOpenssl version that is incompatible with ansible-core 2.12.
Fixes #1715
requirements.txt
> 2.x: Pin vsphere-automation-sdk to v8.0.0.0

- plugins/modules/vmware_object_role_permission.py
- plugins/modules/vmware_object_role_permission_info.py
This update to the documentation should clarify that the module is compatible with ESXi and vCenter which previously wasn't clear by reading through the module description.
vmware_object_role_permission and vmware_object_role_permission_info
This PR is similar to #1678
> docs(vmware_object_role_permission): Clarify vCenter compatibility

- plugins/modules/vmware_vsan_release_catalog.py
This module allows to manually upload the vSAN release catalog to the vCenter which is useful for airgapped environments or other environments where the vCenter cannot directly connect to the VMware cloud service.
vmware_vsan_release_catalog
Similar to #1675
> add vmware_vsan_release_catalog module

- .github/workflows/ansible-test.yml
Backport #1749: Temporarily disable 2.15 sanity tests.
> stable-2.x: Backport temporarily disable 2.15 sanity tests

- plugins/modules/vmware_vswitch.py
- tests/integration/targets/prepare_vmware_tests/tasks/setup_datastore.yml
I think this task is not really necessary:
https://github.com/ansible-collections/community.vmware/blob/f476a072745c7ab9e76a5db1b2b48fc0f2dc5f7e/tests/integration/targets/prepare_vmware_tests/tasks/setup_datastore.yml#L30-L32
> CI: Remove unnecessary prepare step

- tests/integration/targets/vmware_vm_info/tasks/main.yml
Backport #1757: The integration tests fail for vmware_vm_info when run in Zuul with ansible-core 2.15.
vmware_vm_info
> backport 1757: Fix 2.15 integration test

- changelogs/fragments/1765_vmware_guest_disk.yaml
- plugins/modules/vmware_guest_disk.py
- tests/integration/targets/vmware_guest_disk/tasks/main.yml
Fixes #1765. Do not faill when state is absent and disk is not present
```paste below
PLAY [localhost] ***********************************************************************************************************************************************************************************************************************
TASK [Remove VM disk] ******************************************************************************************************************************************************************************************************************
ok: [localhost]
PLAY RECAP ************************************************************************************************************************************************************************************* …
```
> Do not fail when state is absent and disk is not found

- changelogs/fragments/1751-autoselect_datastore-also-use-NFS-mounts.yml
- plugins/modules/vmware_guest.py
VMware allows datastores to be NFS hosted. Currently the autoselect_datastore logic only considers VMFS filesystems. NFS mounted filesystems show up as "NFS", so adjusting logic to also check and consider those filesystems.
Make autoselect_datastore consider NFS mounted filesystems.
Code change does an "or" test on the volume type looking for things that are "NFS" volume types.
Validation requires setting up NFS datastores in your ESXi environment, then calling vmware_guest as below:
```paste below
community.vmware.vmware_guest:
hostname: "{{ vmware_vcenter }}"
username: "{{ vmware_account_name }}"
password: "{{ vmware_password }}"
validate_certs: False
name: "{{ vmware_create_vm_name }}"
datacenter: "{{ vmware_datacenter }}"
cluster: "{{ vmware_cluster }}"
folder: …
```
> Also look at NFS mounted datastores, not just VMFS

- tests/sanity/ignore-2.16.txt
Ignore some sanity tests in 2.16 that haven't been fixed yet.
Backport #1783
> stable-2.x: Ignore some sanity tests in 2.16

- changelogs/fragments/1774_vmware_vasa.yaml
- changelogs/fragments/1774_vmware_vasa_info.yaml
- meta/runtime.yml
- plugins/module_utils/vmware_sms.py
- plugins/modules/vmware_vasa.py
- plugins/modules/vmware_vasa_info.py
New modules added to regiseter, unregister a VASA provider and retrieve information about an existing provider within a vCenter.
vmware_vasa
vmware_vasa_info
The `vmware_vasa` module can be used to register and unregister a VASA provider with a vCenter. That allows for instance creating vVols datastores from storage systems providing that capabilty.
In turn, the `vmware_vasa_info` can be used to retrieve the information related to a registered VASA provider.
> Add VASA modules

- tools/antsibull-docs-wrapper.sh
- tools/create_documentation_tasks.yml
- tox.ini
This is just a first test trying to use [antsibull-docs](https://github.com/ansible-community/antsibull-docs) instead of [collection_prep](https://github.com/ansible-network/collection_prep) in order to generate the documentation. If I'm lucky, it works and I don't have to change it soon.
tools/create_documentation_tasks.yml
Follow-up to #1788
#1770
cc @felixfontein
> Use antsibull-docs to create documentation

- changelogs/fragments/1069_vmware_guest.yml
- plugins/modules/vmware_guest.py
Fixes #1069 
Implements the  ability to configured vm encryption settings for vmotion or fault tolerance
vmware_guest
Fulfill  requirements of #1069
> Implement encryption configuration for vm vmotion and ft

- changelogs/fragments/1805_vmware_vm_info.yml
- plugins/modules/vmware_cluster_info.py
- plugins/modules/vmware_guest_disk.py
- plugins/modules/vmware_vm_info.py
Fixes #1805
Add `instance_uuid` to the result of `vmware_vm_info`.
vmware_vm_info
> vmware_vm_info: Add instance_uuid

- changelogs/fragments/1777-vmware_host_datastore-resignature+vvols.yaml
- changelogs/fragments/1777-vmware_host_datastore-resignature_vvols.yaml
- plugins/modules/vmware_host_datastore.py
New datastore of type `vvols` added to the possible choices of managed datastores.
Resignature VMFS datastore(s)
vmware_host_datastore
vvols - This feature provides the possibility of creating/deleting a vVols datastore in addition to VMFS and NFS datastores.
It has been widely tested on Pure Storage FlashArray storage systems, but it should work on any storage that supports VASA 3.5 and 4.0
resignature - Allows to import existing VMFS datastores preserving their original content.
> Added vvols to the managed datastore types

- plugins/modules/vmware_deploy_ovf.py
After merging #1803 the daily CI run fails the sanity tests:
```
plugins/modules/vmware_deploy_ovf.py:279:161: E501: line too long (164 > 160 characters)
plugins/modules/vmware_deploy_ovf.py:0:0: invalid-documentation: DOCUMENTATION.author: Invalid author for dictionary value @ data['author']. Got ['Alexander Nikitin (@ihumster)', 'Matt Martz ']
```
[Sanity (Ⓐstable-2.14)](https://github.com/mariolenz/community.vmware/actions/runs/5845998282/job/15850666577#logs)
> vmware_deploy_ovf: Fix sanity tests

- docs/community.vmware.vmware_guest_module.rst
- docs/community.vmware.vmware_host_graphics_module.rst
- docs/community.vmware.vmware_host_inventory_inventory.rst
- docs/community.vmware.vmware_vm_inventory_inventory.rst
- plugins/inventory/vmware_host_inventory.py
- plugins/inventory/vmware_vm_inventory.py
- This enables using of Jinja2 for templating `username` and `password`
- `community.vmware.vmware_vm_inventory`
- `community.vmware.vmware_host_inventory`
- Currently, the username and password can be set by Environment Variables, plain or using Ansible Vault. In an inventory using LDAP credentials, with multiple environments and consequently LDAP servers, it's a pain to manage those credentials in a safer way and at the same time dynamically. Also if someone is not using Ansible Vault, allows usage of different ways for storing those secrets safely. Supporting Jinja2, allows anyone to use different `lookup` plugins that best fit their needs.
> feat: add feature to allow template username and password on inventory

- plugins/modules/vcenter_root_password_expiration.py
Added a new module for managing password expiration for root user of vCSA appliance
vcenter_root_password_expiration
> Added module for managing password expiration for root user

- meta/runtime.yml
Add missing modules to `meta/runtime.yml`.
runtime.yml
#1806
#1833
> meta/runtime.yml: Add missing modules

- changelogs/fragments/1847_vmware_guest_snapshot.yml
- docs/community.vmware.vmware_guest_snapshot_module.rst
- plugins/modules/vmware_guest_snapshot.py
- tests/integration/targets/vmware_guest_snapshot/tasks/main.yml
This PR is to add snapshot_id option to the module.
fixes: https://github.com/ansible-collections/community.vmware/issues/1844
changelogs/fragments/1847_vmware_guest_snapshot.yml
docs/community.vmware.vmware_guest_snapshot_module.rst
plugins/modules/vmware_guest_snapshot.py  
tests/integration/targets/vmware_guest_snapshot/tasks/main.yml
~~I will add the integration test in a few days.~~
Done
> Add snapshot_id option to vmware_guest_snapshot module

- .github/workflows/ansible-test.yml
- .github/workflows/extra-docs-linting.yml
- changelogs/fragments/4.0.0-required_ansible_version.yml
- meta/runtime.yml
- tests/sanity/ignore-2.13.txt
- tests/sanity/ignore-2.14.txt
4.0.0 won't support ansible-core < 2.15.0.
> 4.0.0: Removing support for ansible-core version < 2.15.0

- changelogs/fragments/issue_1772.yml
- plugins/modules/vmware_guest_custom_attributes.py
Fixes  #1772 
vmware_guest_custom_attributes
> fix issue #1772

- changelogs/fragments/1517_vmware_host_lockdown.yml
- plugins/modules/vmware_host_lockdown.py
Fixes #1517
Remove deprecated states `absent` and `present`.
vmware_host_lockdown
#1514
> vmware_host_lockdown: Remove deprecated states absent and present

- changelogs/fragments/1761_vmware_vm_info.yml
- plugins/modules/vmware_vm_info.py
Fixes #1761
Add prefix length to IP addresses in `vm_network`, so they now show up as for example `10.76.33.228/24` instead of just `10.76.33.228`.
vmware_vm_info
I'm also switching to using `ipConfig` from [guest.net](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/c476b64b-c93c-4b21-9d76-be14da0148f9/04ca12ad-59b9-4e1c-8232-fd3d4276e52c/SDK/vsphere-ws/docs/ReferenceGuide/vim.vm.GuestInfo.NicInfo.html) instead of `ipAddress` because the latter is deprecated.
> vmware_vm_info: Add prefix length to IPs in vm_network

- changelogs/fragments/1872-vmware_host_acceptance.yml
- meta/runtime.yml
- plugins/modules/vmware_host_acceptance_info.py
- tests/integration/targets/vmware_host_acceptance/tasks/main.yml
- tests/integration/targets/vmware_host_acceptance_info/aliases
- tests/integration/targets/vmware_host_acceptance_info/tasks/main.yml
- tests/sanity/ignore-2.15.txt
- tests/sanity/ignore-2.16.txt
Fixes #1872
Removing `acceptance_level` and move its options to `state` so that
```
acceptance_level: 'community'
state: present
```
will become
```
state: 'community'
```
This also means there won't be a state `list` anymore. In order to get information about the current acceptance level, I will introduce a new module `vmware_host_acceptance_info`.
vmware_host_acceptance
vmware_host_acceptance_info
> vmware_host_acceptance: Remove acceptance_level

- changelogs/fragments/802-vmware_deploy_ovf.yml
- plugins/modules/vmware_deploy_ovf.py
This forces OVF properties marked as ovf:userConfigurable=false to become user configurable.
This is useful when deploying VCSA OVAs.
Backport #1838
> vmware_deploy_ovf: Add new parameter enable_hidden_properties

- plugins/modules/vmware_host_acceptance_info.py
Fix documentation of new module `vmware_host_acceptance_info`.
vmware_host_acceptance_info
#1877
> vmware_host_acceptance_info: Fix module doc

- changelogs/fragments/1898-vmware_rest_client.yml
- plugins/module_utils/vmware_rest_client.py
Fixes: #1898
Remove `get_tag_by_category()`. It's deprecated and not used anymore in the collection.
vmware_rest_client
#1605
> Module util vmware_rest_client: Remove get_tag_by_category

- plugins/modules/vmware_cluster_info.py
- plugins/modules/vmware_dvs_portgroup.py
- plugins/modules/vmware_dvswitch.py
- plugins/modules/vmware_export_ovf.py
- plugins/modules/vmware_guest_instant_clone.py
- plugins/modules/vmware_guest_vgpu.py
- plugins/modules/vmware_host_iscsi_info.py
- plugins/modules/vmware_host_user_manager.py
- plugins/modules/vmware_migrate_vmk.py
- plugins/modules/vmware_object_role_permission.py
- plugins/modules/vmware_tag_manager.py
- plugins/modules/vmware_vm_info.py
- plugins/modules/vmware_vmotion.py
- plugins/modules/vmware_vswitch.py
- plugins/modules/vmware_vswitch_info.py
Now that version 2 is nearly EOL, I don't think that it's important if something has been added in 2.2, 2.4, 2.7 or wherever.
vmware_dvswitch.py
vmware_export_ovf
vmware_guest_instant_clone
vmware_guest_vgpu
vmware_host_iscsi_info
vmware_host_user_manager
vmware_vm_info
vmware_vmotion
vmware_vswitch
vmware_vswitch_info
> Remove version_added: 2.x

- tox.ini
Fix ansible-tox-linters.
tox.ini
#1904
#1906
> stable-3.x: Fix ansible-tox-linters

- changelogs/fragments/1516-vmware_dvs_host.yml
- plugins/modules/vmware_dvs_host.py
- tox.ini
Fixes: #1516
Remove defaults for `vmnics` and `lag_uplinks`.
vmware_dvs_host
> vmware_dvs_host: Defaults for vmnics and lag_uplinks

- .github/workflows/ansible-test.yml
Disable Codecov for now. I don't think it provides valuable information to us, at least not at the moment.
Backport of #1920
> stable-3.x: Disable Codecov

- tests/integration/targets/vmware_category/tasks/main.yml
- tests/integration/targets/vmware_host_auto_start/tasks/main.yml
- tests/integration/targets/vmware_object_rename/tasks/main.yml
- tests/integration/targets/vmware_tag/tasks/main.yml
- tests/integration/targets/vmware_tag_info/tasks/main.yml
- tests/integration/targets/vmware_tag_manager/tasks/main.yml
- tests/sanity/ignore-2.17.txt
Use `include_tasks` instead of `include` in the integration tests.
vmware_host_auto_start
vmware_object_rename
vmware_tag
vmware_tag_info
#1921
> Fix integration tests: include -> include_tasks

- tests/integration/targets/vmware_category/tasks/main.yml
- tests/integration/targets/vmware_host_auto_start/tasks/main.yml
- tests/integration/targets/vmware_object_rename/tasks/main.yml
- tests/integration/targets/vmware_tag/tasks/main.yml
- tests/integration/targets/vmware_tag_info/tasks/main.yml
- tests/integration/targets/vmware_tag_manager/tasks/main.yml
- tests/sanity/ignore-2.17.txt
Use `include_tasks` instead of `include` in the integration tests.
vmware_host_auto_start
vmware_object_rename
vmware_tag
vmware_tag_info
Backport #1922
> Backport1922

- changelogs/fragments/1919-vmware_vm_info.yml
- plugins/modules/vmware_vm_info.py
According to the documentation `ipConfig` in [GuestNicInfo(vim.vm.GuestInfo.NicInfo)](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/c476b64b-c93c-4b21-9d76-be14da0148f9/04ca12ad-59b9-4e1c-8232-fd3d4276e52c/SDK/vsphere-ws/docs/ReferenceGuide/vim.vm.GuestInfo.NicInfo.html) might be unset. This can lead to an `AttributeError: 'NoneType' object has no attribute 'ipAddress'`.
I wasn't really able to reproduce this with:
- powered off VM
- powered on VM without VMware Tools installed
- powered on VM without VMware Tools installed and running
- powered on VM without VMware Tools installed and running, not all NICs configured
But it looks like [some users](https://github.com/ansible-collections/community.vmware/pull/1871#issuecomment-1807252637) run into this issue.
> vmware_vm_info: Fix AttributeError

- plugins/modules/vcenter_root_password_expiration.py
Added a missing init 
vcenter_root_password_expiration
> [BUGFIX] Added the missing init for the rest client

- tests/integration/targets/vcenter_root_password_expiration/aliases
- tests/integration/targets/vcenter_root_password_expiration/tasks/main.yml
Add a (very simple) integration test for `vcenter_root_password_expiration`.
vcenter_root_password_expiration
> vcenter_root_password_expiration: Add integration test

- changelogs/fragments/1959-vmware_guest_sendkey.yml
- plugins/modules/vmware_guest_sendkey.py
Fixes #1959
Add the windows key to support keyboard emulation in windows server.
vmware_guest_sendkey
> vmware_guest_sendkey: Add Windows key

- changelogs/fragments/1059-vmware_guest_tools_upgrade.yml
- plugins/modules/vmware_guest_tools_upgrade.py
Fixes #1059
Add parameter `installer_options` to pass command line options to the installer to modify the installation procedure for tools.
vmware_guest_tools_upgrade
> vmware_guest_tools_upgrade: New parameter installer_options

- changelogs/fragments/1969-InsecureRequestWarning.yml
- plugins/module_utils/vmware_rest_client.py
It looks like we're sometimes running into an `InsecureRequestWarning`.
[Vmware ssl certs (works in one module, not the other!)](https://forum.ansible.com/t/vmware-ssl-certs-works-in-one-module-not-the-other/3279)
> Fix InsecureRequestWarning

- changelogs/fragments/1969-InsecureRequestWarning.yml
- plugins/module_utils/vmware_rest_client.py
Backport of #1969
It looks like we're sometimes running into an `InsecureRequestWarning`.
[Vmware ssl certs (works in one module, not the other!)](https://forum.ansible.com/t/vmware-ssl-certs-works-in-one-module-not-the-other/3279)
> stable-3.x: Fix InsecureRequestWarning for VmwareRestClient based modules

- .github/workflows/import-galaxy.yml
Use shared workflow from https://github.com/ansible-community/github-action-test-galaxy-import.
CI
> Use shared workflow for Galaxy import test

- changelogs/fragments/1930-fix_ssl_deprecation_function.yml
- plugins/module_utils/vmware.py
Replaced for code based on ssl.get_server_certificate().
Fixes #1930 
> Issue #1930 Replaced for code based on ssl.get_server_certificate().

- changelogs/fragments/1848-fix-vm-reconfiguration-with-enabled-vbs.yml
- plugins/modules/vmware_guest.py
VM reconfiguration is currently broken when `virt_based_security` is configured due to checking for `vbsEnabled` on the wrong object.
vmware_guest
> Fix failure of vm reconfiguration with enabled virt_based_security

- changelogs/fragments/1848-fix-vm-reconfiguration-with-enabled-vbs.yml
- plugins/modules/vmware_guest.py
VM reconfiguration is currently broken when `virt_based_security` is configured due to checking for `vbsEnabled` on the wrong object.
vmware_guest
Backport #1848
> stable-3.x: Fix failure of vm reconfiguration with enabled virt_based_security

- changelogs/fragments/1972-vm_inventory_subproperties.yml
- plugins/inventory/vmware_vm_inventory.py
This Change adds an option 'subproperties' to the vmware_vm_inventory plugin.
```
plugin: community.vmware.vmware_vm_inventory
strict: false
hostname: 10.65.223.31
username: administrator@vsphere.local
password: Esxi@123$%
properties:
- 'name'
- 'guest.ipAddress'
- 'config.name'
- 'config.uuid'
subproperties:
- property: 'summary.runtime.host'
subelements:
- 'name'
- 'parent.name'
```
> Add subproperties option to vmware_vm_inventory

- changelogs/fragments/1994-vmware-host-facts.yml
- plugins/modules/vmware_host_facts.py
Add the possibility to get the related datacenter.
vmware_host_facts.py
```paste below
```
> vmware_host_facts - related datacenter

- changelogs/fragments/1995-vsphere_copy.yml
- plugins/modules/vsphere_copy.py
Add possiblity to tell vsphere_copy which diskformat is being uploaded
vsphere_copy
Related issue: https://github.com/vmware/pyvmomi/issues/1064
```paste below
- name: Copy file to datastore using other_system
community.vmware.vsphere_copy:
hostname: '{{ vcenter_hostname }}'
username: '{{ vcenter_username }}'
password: '{{ vcenter_password }}'
src: /other/local/streamOptimized.vmdk
datacenter: DC2 Someplace
datastore: datastore2
path: disk_imports/streamOptimized.vmdk
timeout: 360
diskformat: StreamVmdk
```
> Add possiblity to tell vsphere_copy which diskformat is being uploaded

- changelogs/fragments/1996 - vmware_first_class_disk_info.yml
- meta/runtime.yml
- plugins/module_utils/vmware.py
- plugins/modules/vmware_first_class_disk_info.py
- tests/integration/targets/vmware_first_class_disk_info/aliases
- tests/integration/targets/vmware_first_class_disk_info/tasks/main.yml
Add a module to gather infos about first class disks
Fixes #1988 
vmware.py-> find_first_class_disks(self, datastore_obj)
vmware_first_class_disk_info.py
```paste below
```
> vmware_first_class_disk_info - Add a module to gather infos about first class disks

- plugins/modules/vsphere_copy.py
This is a follow up to #1995 
I overlooked the capitalization in some of the changes suggested by maintainers, this makes it consistent across all occurrences. 
vsphere_copy
```paste below
```
> vsphere_copy: make spelling of StreamVmdk consistent

- changelogs/fragments/2024027-fix_ci.yml
- plugins/module_utils/vmware.py
- scripts/inventory/vmware_inventory.py
- tests/unit/mock/loader.py
Fix the following Pylint errors in the CI:
```
ERROR: plugins/module_utils/vmware.py:1091:13: unidiomatic-typecheck: Use isinstance() rather than type() for a typecheck.
ERROR: plugins/module_utils/vmware.py:1093:13: unidiomatic-typecheck: Use isinstance() rather than type() for a typecheck.
ERROR: plugins/module_utils/vmware.py:1095:13: unidiomatic-typecheck: Use isinstance() rather than type() for a typecheck.
ERROR: scripts/inventory/vmware_inventory.py:286:11: unidiomatic-typecheck: Use isinstance() rather than type() for a typecheck.
ERROR: tests/unit/mock/loader.py:33:15: unidiomatic-typecheck: Use isinstance() rather than type() for a typecheck.
```
scripts/inventory/vmware_inventory.py
tests/unit/mock/loader.py
> Fix Pylint errors in CI

- changelogs/fragments/2024027-fix_ci.yml
- plugins/module_utils/vmware.py
- scripts/inventory/vmware_inventory.py
- tests/unit/mock/loader.py
Fix the following Pylint errors in the CI:
```
ERROR: plugins/module_utils/vmware.py:1091:13: unidiomatic-typecheck: Use isinstance() rather than type() for a typecheck.
ERROR: plugins/module_utils/vmware.py:1093:13: unidiomatic-typecheck: Use isinstance() rather than type() for a typecheck.
ERROR: plugins/module_utils/vmware.py:1095:13: unidiomatic-typecheck: Use isinstance() rather than type() for a typecheck.
ERROR: scripts/inventory/vmware_inventory.py:286:11: unidiomatic-typecheck: Use isinstance() rather than type() for a typecheck.
ERROR: tests/unit/mock/loader.py:33:15: unidiomatic-typecheck: Use isinstance() rather than type() for a typecheck.
```
scripts/inventory/vmware_inventory.py
tests/unit/mock/loader.py
#2011
> stable-3.x: Fix Pylint errors in CI

- changelogs/fragments/2036-missing_error_msg_in_vmware_guest.yml
- plugins/modules/vmware_guest.py
Fixes missing error message in when creating VM using vmware_guest module, with template, while setting the guest_id parameter.
vmware_guest
Backport of #2036
> stable-3.x: Missing error msg in vmware_guest

- meta/runtime.yml
- plugins/modules/vmware_all_snapshots_info.py
The new module returns all snapshots in the datacenter with no need of indicating from where machine or folder they have to belong. It also lhas filters options that can be sctrict or included, based if the user wants to retrieve all snapshots that in their name contains the word "test" or all snapshots that their state is "poweredOn". There is no need to filter, if no filter is applied it just returns all snapshots.
vmware_all_snapshots_info
With the actual module community.vmware.vmware_guest_snapshot_info the user needs to write or if the uuid or the moid is not supplied, also no filters can be applied. With this module all snapshots of th vmware are returned by default and one or more filters can be aplpied.
Below to get all snapshtos of the datacenter and …
> add vmware_all_snapshots_info new module 

- changelogs/fragments/2033-vmware_guest_tools_info.yml
- plugins/modules/vmware_guest_tools_info.py
Fixes #2033 
`toolsVersionStatus` is [deprecated](https://vdc-download.vmware.com/vmwb-repository/dcr-public/184bb3ba-6fa8-4574-a767-d0c96e2a38f4/ba9422ef-405c-47dd-8553-e11b619185b2/SDK/vsphere-ws/docs/ReferenceGuide/vim.vm.Summary.GuestSummary.html) and `toolsVersionStatus2` should be used.
vmware_guest_tools_info
I've just seen that `toolsStatus` is also deprecated. But removing it would be a breaking change... ~I'll mark this PR WIP until I know what to do about it.~
Let's deprecate `vm_tools_install_status` in favour of `vm_tools_running_status` / `vm_tools_version_status` as an alternative.
> vmware_guest_tools_info: Use toolsVersionStatus2

- changelogs/fragments/2044-error_in_adding_disk_to_vm_in_vmware_guest.yml
- plugins/modules/vmware_guest.py
In update VM - while adding disk to existing VM leaves it in an invalid state
vmware_guest module
While trying to add a disk to an existing VM (in poweredoff state) using the provision_vm role
```
---
- name: Provision VM
community.vmware.vmware_guest:
hostname: "{{ vCenter_hostname }}"
username: "{{ vCenter_username }}"
password: "{{ vCenter_password }}"
cluster: ""
folder: ""
datacenter: ""
name: "vm-test-2"
cdrom:
- controller_number: 0
unit_number: 0
state: present
type: iso
iso_path: "[datastore1] ISO/rhel-9.3-x86_64-dvd.iso"
disk:
- size_gb: 40
type: thin
datastore: "datastore1"
hardware:
memory_mb: 2000
num_cpus: 4
boot_firmware: efi
secure_boot: true
guest_id: "centos64Guest"
- name: Add disk VM
community.vmware.vmware_guest:
hostname: …
```
> Fix update VM while adding a new disk

- tests/sanity/ignore-2.18.txt
Ignore some sanity tests in 2.18 that haven't been fixed yet.
_edit_:
We still have to ignore `parameter-state-invalid-choice` in `vmware_host_acceptance`. This is fixed in 4.0.0 but since this is a breaking change we can't backport it and need the ignore in 3.x.
> stable-3.x: Ignore some sanity tests in 2.18

- changelogs/fragments/2044-error_in_adding_disk_to_vm_in_vmware_guest.yml
- plugins/modules/vmware_guest.py
In update VM - while adding disk to existing VM leaves it in an invalid state ISSUE TYPE
vmware_guest module
While trying to add a disk to an existing VM (in poweredoff state) using the provision_vm role
```
---
- name: Provision VM
community.vmware.vmware_guest:
hostname: "{{ vCenter_hostname }}"
username: "{{ vCenter_username }}"
password: "{{ vCenter_password }}"
cluster: ""
folder: ""
datacenter: ""
name: "vm-test-2"
cdrom:
- controller_number: 0
unit_number: 0
state: present
type: iso
iso_path: "[datastore1] ISO/rhel-9.3-x86_64-dvd.iso"
disk:
- size_gb: 40
type: thin
datastore: "datastore1"
hardware:
memory_mb: 2000
num_cpus: 4
boot_firmware: efi
secure_boot: true
guest_id: "centos64Guest"
- name: Add disk VM
community.vmware.vmware_guest: …
```
> Fix update VM while adding a new disk (#2044)

- plugins/modules/vmware_vm_shell.py
Doc improve. Add important description to folder var info
The 'vm_id_type' variable is required to be set to 'inventory_path', otherwise folder will be None
vmware_vm_shell_module
The documentation is not clear enough. It is not clear in the vmware_vm_shell_module that with the default vm_id_type value, the folder value will be set to None and it will not work at all
```python
if module.params['vm_id_type'] == 'inventory_path':
vm = find_vm_by_id(self.content,
vm_id=module.params['vm_id'],
vm_id_type="inventory_path",
folder=folder)
else:
vm = find_vm_by_id(self.content,
vm_id=module.params['vm_id'],
vm_id_type=module.params['vm_id_type'],
datacenter=datacenter,
cluster=cluster)
def find_vm_by_id(content, vm_id, vm_id_type="vm_name", datacenter=None,
cluster=None, …
```
> vmware_vm_shell - improve doc ( folder var description )

- changelogs/fragments/1949-dvswitch_netflow_switch_ip.yml
- plugins/modules/vmware_dvswitch.py
This change makes it possible to change the `Switch IP address` parameter for the NetFlow config of a distributed vSwitch:
As this is a parameter which belongs to the NetFlow config, I added it under the conditional of the `netFlow_collector_ip`, if this unwanted I can of course pull it one layer out!
I'm not used to contributing to Modules so far, so please just point out every issue or improvement if needed, I will fix it 👍🏻
Tested with a self-built EE via navigator so far.
Thanks!
> Add switchIpAddress to vmware_dvswitch module

- changelogs/fragments/2055-vmware_dvs_portgroup-status_default.yml
- plugins/modules/vmware_dvs_portgroup.py
`vmware_dvs_portgroup` doesn't have a default for `state`. Usually, modules have this and define `present`. I think it would make sense to do it like this here, too.
https://github.com/ansible-collections/community.vmware/pull/2053#issuecomment-2075374617
cc @lennardk
> vmware_dvs_portgroup: Make status present the default

- changelogs/fragments/2053-vmware_dvs_portgroup.yml
- plugins/modules/vmware_dvs_portgroup.py
- tests/integration/targets/vmware_dvs_portgroup/tasks/main.yml
The module would report `changed` when `port_binding`=`static` and `num_ports` not specified even though the resulting update would be without actual changes.
The `vmware_dvs_portgroup` reports changes when when `port_binding`=`static` and `num_ports` isn't specified.
The resulting call would specify `vim.dvs.DistributedVirtualPortgroup.ConfigSpec.numPorts` as None though, resulting in no changes.
This PR makes sure to not report a change for `num_ports` inconsistencies if it isn't specified
Other than in the commit, I believe `num_ports` is only used [here](https://github.com/ansible-collections/community.vmware/blob/366b9fe28cfc4ab75a57df8d9f6930f2ff6e257e/plugins/modules/vmware_dvs_portgroup.py#L485).
> vmware_dvs_portgroup: don't update on non-specified num_ports

- changelogs/fragments/2056-vmware_cluster_dpm-handle-dpm-none-config.yml
- changelogs/fragments/2057-vmware_cluster_dpm-handle-dpm-none-config.yml
- plugins/modules/vmware_cluster_dpm.py
An unexpected error is thrown when trying to set/create the DPM config if no config already exists. I encountered this when using the vCenter simulation project (vcsim). 
This PR allows the module to set the DPM config even if it is missing. It treats a missing config the same as a config with an undesired `enabled` state.
vmware_cluster_dpm module
Im pretty sure that actual vCenter deployments have DPM configs by default, so this issue probably does not affect many use cases. Still, the fix is easy and doesn't change how the module behaves for those people. 
To reproduce:
```
---
tasks:
- name: Run soap vcSim
containers.podman.podman_container:
name: vmwaresoap
image: docker.io/vmware/vcsim:latest
state: started
recreate: yes …
```
> check if dpm config is None

- tests/integration/targets/vmware_content_library_manager/aliases
Broadcom is moving things from `vmware.com` to `broadcom.com` at the moment and this seems to break the integration tests for `vmware_content_library_manager`. So let's disable them temporarily.
#2061
#2063
#2064
> Disable vmware_content_library_manager integration tests

- tests/integration/targets/vmware_content_library_manager/tasks/main.yml
Fix `vmware_content_library_manager` integration tests after Broadcom moved things from `vmware.com` to `broadcom.com`.
Backport of #2067
> stable-3.x: Fix vmware_content_library_manager integration tests

- changelogs/fragments/2071-clarify-pyvmomi-requirement.yml
- plugins/module_utils/vmware.py
- plugins/modules/vmware_cluster_info.py
- plugins/modules/vmware_datacenter_info.py
- plugins/modules/vmware_datastore_info.py
- plugins/modules/vmware_dvswitch_info.py
- plugins/modules/vmware_guest_info.py
- plugins/modules/vmware_host_facts.py
- plugins/modules/vmware_vcenter_settings_info.py
- plugins/modules/vmware_vsan_health_info.py
- requirements.txt
At least some of the modules require pyVmomi 6.7.1 or later, but we didn't specify this in the `requirements.txt`.
requirements.txt
[6.7.1](https://pypi.org/project/pyvmomi/6.7.1/) has been released 2018-10-23, 5 1/2 years ago.
> Require pyVmomi 6.7.1

- changelogs/fragments/2080_bugfix_hadnle_vcls_none_config.yml
- plugins/modules/vmware_cluster_vcls.py
In pyVmomi >7.0.2, the `systemVMsConfig` attribute is `None` instead of not existing. This causes the following logic to throw an attribute error when accessing `vCLS_config.allowedDatastores`.
This PR adds support for newer pyVmomi versions while preserving the behavior for earlier versions. If `systemVMsConfig` is not defined, the module exits without doing anything. If it exists but None, the module will attempt to update/create the config so it matches the user's desired state.
vmware_cluster_vcls
Its possible this is a niche situation. I discovered it while using the vcsim for testing the module.
to reproduce:
```yaml
---
tasks:
- name: Run soap vcSim
containers.podman.podman_container:
name: vmwaresoap
image: …
```
> avoid attribute error on allowedDatastores

- plugins/modules/vmware_sdrs_vm_overrides_info.py
Added a module to check if Storage DRS Overrides are present in a given datastore cluster as in our setup these are not desired and are therefore manually removed after evaluation on a case-to-case basis.
Currently no module exists to handle this task.
vmware_sdrs_vm_overrides_info.py
```paste below
RETURN = r'''
result:
description: information about datastore clusters with VMs with SDRS enabled
returned: always
type: str
sample:  {"changed": false, "result": {"DSC_1": {"vm_overrides": {"VM_1": {"srds_enabled_status": false, "vm_behavior": null}, "VM_2": {"srds_enabled_status": false, "vm_behavior": null}}}}}
'''
```
> add module to check for VMs with Storage DRS Overrides on given datastore clusters

- changelogs/fragments/2088_bugfix_correct_vcenter_folder_docs.yml
- plugins/modules/vcenter_folder.py
The documentation for the `vcenter_folder` module says that the `folder_type` parameter has no effect when `parent_folder` is set. This is incorrect, the `folder_type` parameter is always taken into account.
vcenter_folder
> vcenter_folder - remove bad documentation

- changelogs/fragments/2080_bugfix_hadnle_vcls_none_config.yml
- plugins/modules/vmware_cluster_vcls.py
Backport #2080
In pyVmomi >7.0.2, the `systemVMsConfig` attribute is `None` instead of not existing. This causes the following logic to throw an attribute error when accessing `vCLS_config.allowedDatastores`.
This PR adds support for newer pyVmomi versions while preserving the behavior for earlier versions. If `systemVMsConfig` is not defined, the module exits without doing anything. If it exists but None, the module will attempt to update/create the config so it matches the user's desired state.
vmware_cluster_vcls
Its possible this is a niche situation. I discovered it while using the vcsim for testing the module.
to reproduce:
```yaml
---
tasks:
- name: Run soap vcSim
containers.podman.podman_container:
name: vmwaresoap …
```
> stable-3.x: avoid attribute error on allowedDatastores

- changelogs/fragments/2088_bugfix_correct_vcenter_folder_docs.yml
- plugins/modules/vcenter_folder.py
Backport #2088
The documentation for the `vcenter_folder` module says that the `folder_type` parameter has no effect when `parent_folder` is set. This is incorrect, the `folder_type` parameter is always taken into account.
vcenter_folder
> stable-3.x: vcenter_folder - remove bad documentation

- changelogs/fragments/2092-vmware_host_logbundle.yml
- plugins/modules/vmware_host_logbundle.py
- tests/integration/targets/vmware_host_logbundle/tasks/main.yml
Adding an optional timeout parameter to `vmware_host_logbundle`.
vmware_host_logbundle
#2090
It looks like the default timeout of the function the module uses is just 10s:
https://github.com/ansible/ansible/blob/6382ea168a93d80a64aab1fbd8c4f02dc5ada5bf/lib/ansible/module_utils/urls.py#L1136-L1139
> vmware_host_logbundle: Add timeout

- changelogs/fragments/2095_bugfix_vmware_guest_disk_round_size_to_int.yml
- plugins/modules/vmware_guest_disk.py
Fixes https://github.com/ansible-collections/community.vmware/issues/123
`capacityInKB` is of type `long`, but we have code in place to support `float` values for the disk size in the module. We should typecast the size by rounding the provided value.
> vmware_guest_disk: round size to int

- changelogs/fragments/2102_vm_vm_drs_rule_datacenter_argument.yml
- plugins/modules/vmware_vm_vm_drs_rule.py
Add datacenter argument to vmware_vm_vm_drs_rule module
Code adjustments copy-pasted from vmware_vm_host_drs_rule module
Fixes #2101 
vmware_vm_vm_drs_rule
Previously no datacenter could be provided. The result was that the module always tried to create/manage rules in the first cluster in vcenter that matches the name.
Now a datacenter name can be provided if nessessary.
```paste below
```
> vmware_vm_vm_drs_rule: add datacenter argument

- README.md
The page behind the old link has moved meaning it now redirects to a company landing page. The updated link takes the user to the presumed intended location.
README.md
Note the following from the [newly linked page](https://developer.broadcom.com/sdks/vsan-management-sdk-for-python/latest/#:~:text=NOTE%3A%20Starting%20with%20vSphere%208.0%20Update%203%20release%20version%2C%20the%20vSAN%20Management%20SDK%20for%20Python%20is%20integrated%20into%20the%20Python%20SDK%20for%20the%20VMware%20vSphere%20API%20(pyVmomi).%20From%20the%20Python%20Package%20Index%20(PyPi)%2C%20you%20can%20download%20a%20single%20package%20to%20manage%20vSAN%2C%20vCenter%2C%20and%20ESXi):
> Starting with vSphere 8.0 Update 3 release version, the vSAN Management SDK for Python is integrated into …
> README.md: Update vSAN SDK link which redirects

- README.md
- changelogs/fragments/2127-require-requests.yml
- requirements.txt
Fixes #2127
The collection requires `requests`, but we've never documented this since pyVmomi already pulled this in. But it looks like they've dropped the dependency and we didn't notice this up until now. So I think we should make this requirement explicit.
https://github.com/ansible-collections/community.vmware/blob/ff672be4cb07378b6c1ed1f5dcfc9823b101f6f3/plugins/module_utils/vmware.py#L1128-L1130
[Major pyVmomi update for vSphere 8.0](https://github.com/vmware/pyvmomi/commit/a90023fedfeda48cb1824200dc4530084215f99e)
> Document requirement on requests

- .github/workflows/ansible-test.yml
- tests/sanity/ignore-2.15.txt
- tests/sanity/ignore-2.16.txt
- tests/sanity/ignore-2.17.txt
- tests/sanity/ignore-2.18.txt
Temporarily disable runtime-metadata sanity test until ansible/ansible#83831 is backported to avoid false positives like in e.g. #2136.
Also changing the sanity tests from milestone to devel to see if ansible/ansible#83831 really fixes the issue.
> Temporarily disable runtime-metadata sanity test

- changelogs/fragments/2136-deprecate-vmware_cluster_drs.yml
- meta/runtime.yml
- plugins/modules/vmware_cluster_drs.py
Deprecate `community.vmware.vmware_cluster_drs` in favor of `vmware.vmware.cluster_drs`.
vmware_cluster_drs
[New vmware.vmware collection and impact on community.vmware](https://forum.ansible.com/t/5880)
> Deprecate vmware_cluster_drs

- .github/workflows/ansible-test.yml
- tests/sanity/ignore-2.18.txt
Switch back to using milestone for the sanity tests instead of devel.
Undoing parts of #2140.
> Switch back to milestone instead of devel

- changelogs/fragments/2055-vmware_guest_snapshot.yml
- plugins/modules/vmware_guest_snapshot.py
Fixes #2145
Document that `snapshot_id` parameter is also available when `state=revert`, not only when `state=absent`.
vmware_guest_snapshot
> Document snapshot_id available for state=revert

- tests/sanity/ignore-2.16.txt
- tests/sanity/ignore-2.17.txt
Enable runtime-metadata sanity test for 2.16 and 2.17 again undoing parts of #2140.
ansible/ansible#83856
ansible/ansible#83857
> Enable runtime-metadata sanity test for 2.16 and 2.17 again

- .github/workflows/ansible-test.yml
- changelogs/fragments/5.0.0-required_ansible_version.yml
- meta/runtime.yml
- tests/sanity/ignore-2.15.txt
- tests/sanity/ignore-2.16.txt
Fixes #1880
5.0.0 won't support ansible-core < 2.17.0.
> 5.0.0: Removing support for ansible-core version < 2.17.0

- changelogs/fragments/2143-deprecate-vmware_cluster.yml
- meta/runtime.yml
- plugins/modules/vmware_cluster.py
Deprecate `community.vmware.vmware_cluster` in favor of `vmware.vmware.cluster`.
vmware_cluster
[New vmware.vmware collection and impact on community.vmware](https://forum.ansible.com/t/5880)
> Deprecate vmware_cluster

- changelogs/fragments/2156-deprecate-vmware_cluster_vcls.yml
- meta/runtime.yml
- plugins/modules/vmware_cluster_vcls.py
Deprecate `community.vmware.vmware_cluster_vcls` in favor of `vmware.vmware.cluster_vcls`.
vmware_cluster_vcls
[New vmware.vmware collection and impact on community.vmware](https://forum.ansible.com/t/5880)
> Deprecate vmware_cluster_vcls

- changelogs/fragments/2143-deprecate-vmware_cluster.yml
- meta/runtime.yml
- plugins/modules/vmware_cluster.py
Deprecate `community.vmware.vmware_cluster` in favor of `vmware.vmware.cluster`.
vmware_cluster
Backport of #2143
> 4.x: Deprecate vmware_cluster

- changelogs/fragments/2156-deprecate-vmware_cluster_vcls.yml
- meta/runtime.yml
- plugins/modules/vmware_cluster_vcls.py
Deprecate `community.vmware.vmware_cluster_vcls` in favor of `vmware.vmware.cluster_vcls`.
vmware_cluster_vcls
Backport of #2156
> 4.x: Deprecate vmware_cluster_vcls

- changelogs/fragments/2159-depend-on-vmware.vmware.yml
- galaxy.yml
We've deprecated some modules in favor of ones from [vmware.vmware](https://github.com/ansible-collections/vmware.vmware). Let's make this collection a dependency, so it's already there when people want to use it.
galaxy.yml
[New vmware.vmware collection and impact on community.vmware](https://forum.ansible.com/t/5880)
> Depend on vmware.vmware

- changelogs/fragments/2138-vmware_all_snapshots_info.yml
- plugins/modules/vmware_all_snapshots_info.py
The datacenter parameter was ignored in the `vmware_all_snapshots_info` module, so all VM snapshots were returned.
I fixed the issue where the datacenter parameter was being ignored when searching for VMs.
fixes https://github.com/ansible-collections/community.vmware/issues/2138
* plugins/modules/vmware_all_snapshots_info.py
I tested in VCSA7.
> vmware_all_snapshots_info: Fix datacenter parameter being ignored

- changelogs/fragments/2138-vmware_all_snapshots_info.yml
- plugins/modules/vmware_all_snapshots_info.py
The `datacenter` parameter was ignored in the `vmware_all_snapshots_info` module, so all VM snapshots were returned.
* vmware_all_snapshots_info
Backport of #2165
> Stable-4.x: vmware_all_snapshots_info: Fix datacenter ignored

- changelogs/fragments/2078-vmware_guest_tools_info.yml
- plugins/modules/vmware_guest_tools_info.py
- tests/integration/targets/vmware_guest_tools_info/tasks/main.yml
Fixes #2078
Removing `vm_tools_install_status` which reports the [deprecated toolsStatus](https://vdc-download.vmware.com/vmwb-repository/dcr-public/184bb3ba-6fa8-4574-a767-d0c96e2a38f4/ba9422ef-405c-47dd-8553-e11b619185b2/SDK/vsphere-ws/docs/ReferenceGuide/vim.vm.Summary.GuestSummary.html) as announced in #2034.
vmware_guest_tools_info
> vmware_guest_tools_info: Remove vm_tools_install_status

- README.md
- changelogs/fragments/5.0.0-requirements.yml
- requirements.txt
Fixes #2123
Require pyVmomi >= 8.0.3.0.1 in order to be able to drop the requirement on the vSAN Management SDK for Python, which has been a pain to install.
Also, substitute the requirement for / dependency on `https://github.com/vmware/vsphere-automation-sdk-python.git` with the PyPI packages `vmware-vcenter` and `vmware-vapi-common-client`.
Additionally, at least one of those pulls in `requirements` so we can remove it, too.
Also document the dependency on ansible-core 2.17.0.
requirements.txt
README.md
[vSAN Management SDK for Python](https://developer.broadcom.com/sdks/vsan-management-sdk-for-python/latest/)
[vsphere-automation-sdk-python  PyPI package](https://github.com/vmware/vsphere-automation-sdk-python/issues/38#issuecomment-2206842664)
#2153
> Update 5.0.0 dependencies

- changelogs/2174.yml
- plugins/modules/vmware_guest_tools_upgrade.py
- plugins/modules/vmware_vm_shell.py
Fixes #2167
`vmware_vm_shell` and `vmware_guest_tools_upgrade` use [guest.toolsStatus which is deprecated](https://vdc-download.vmware.com/vmwb-repository/dcr-public/184bb3ba-6fa8-4574-a767-d0c96e2a38f4/ba9422ef-405c-47dd-8553-e11b619185b2/SDK/vsphere-ws/docs/ReferenceGuide/vim.vm.GuestInfo.html).
vmware_vm_shell.py
vmware_guest_tools_upgrade.py
> Drop using guest.toolsStatus

- .github/workflows/extra-docs-linting.yml
- changelogs/fragments/2192-fix-documentation.yml
- plugins/connection/vmware_tools.py
- plugins/modules/vcenter_standard_key_provider.py
- plugins/modules/vmware_dvswitch_nioc.py
- plugins/modules/vmware_guest.py
- plugins/modules/vmware_guest_controller.py
- plugins/modules/vmware_guest_disk.py
- plugins/modules/vmware_guest_serial_port.py
Fix documentation.
vmware_dvswitch_nioc
vmware_guest
vmware_guest_serial_port
vmware_tools
Backport of #2192
> stable-4.x: Fix documentation

- plugins/modules/vmware_vm_info.py
Correct minor typo in docs
vmware_vm_info
Found typo in documentation, submitting correction
> Correct minor typo "vminfo" to "vm_info"

- changelogs/fragments/2208-vmware_vmotion.yml
- plugins/modules/vmware_vmotion.py
I think there's a problem here:
https://github.com/ansible-collections/community.vmware/blob/7c2cc76ac4f13332802ff74c0dfdcd90cfd65bea/plugins/modules/vmware_vmotion.py#L481-L484
If vSphere doesn't give a recommendation, this might result in a `list index out of range` error.
vmware_vmotion
#2207
> vmware_vmotion: Catch no placement recommendation

- changelogs/fragments/2208-vmware_vmotion.yml
This is a follow-up to #2208 to document the change correctly as a bugfix instead of a minor change.
vmware_vmotion
> Fix changelog entry

- changelogs/fragments/2208-vmware_vmotion.yml
- plugins/modules/vmware_vmotion.py
Backport of #2208
I think there's a problem here:
https://github.com/ansible-collections/community.vmware/blob/7c2cc76ac4f13332802ff74c0dfdcd90cfd65bea/plugins/modules/vmware_vmotion.py#L481-L484
If vSphere doesn't give a recommendation, this might result in a `list index out of range` error.
vmware_vmotion
#2209
> stable-4.x: vmware_vmotion: Catch no placement recommendation

- changelogs/fragments/2208-vmware_vmotion.yml
- plugins/modules/vmware_vmotion.py
Backport of #2208
I think there's a problem here:
https://github.com/ansible-collections/community.vmware/blob/7c2cc76ac4f13332802ff74c0dfdcd90cfd65bea/plugins/modules/vmware_vmotion.py#L481-L484
If vSphere doesn't give a recommendation, this might result in a `list index out of range` error.
vmware_vmotion
#2209
> stable-3.x: vmware_vmotion: Catch no placement recommendation

- .github/workflows/extra-docs-linting.yml
Install `vmware.vmware` when doing the docs linting / checks.
#2217
#2218
ansible-collections/collection_template#82
> Install vmware.vmware for docs linting

- .github/workflows/extra-docs-linting.yml
Follow-up to #2219
Install `vmware.vmware` >= 1.6.0 for docs linting / checks.
#2217
#2218
ansible-collections/collection_template#82
> Install vmware.vmware>=1.6.0 for docs linting

- .github/workflows/extra-docs-linting.yml
Follow-up to #2221
Install `vmware.vmware` >= 1.6.0 for docs linting / checks.
#2217
#2218
ansible-collections/collection_template#82
> Install vmware.vmware>=1.6.0 for docs linting (2)

- changelogs/fragments/2218-deprecate-vmware_cluster_drs_recommendations.yml
- meta/runtime.yml
- plugins/modules/vmware_cluster_drs_recommendations.py
Deprecate `community.vmware.vmware_cluster_drs_recommendations` in favor of `vmware.vmware.cluster_drs_recommendations`.
vmware_cluster_drs_recommendations
ansible-collections/vmware.vmware#70
> Deprecate vmware_cluster_drs_recommendations

- changelogs/fragments/2218-deprecate-vmware_cluster_drs_recommendations.yml
- meta/runtime.yml
- plugins/modules/vmware_cluster_drs_recommendations.py
Backport of #2218
Deprecate `community.vmware.vmware_cluster_drs_recommendations` in favor of `vmware.vmware.cluster_drs_recommendations`.
vmware_cluster_drs_recommendations
ansible-collections/vmware.vmware#70
> stable-4.x: Deprecate vmware_cluster_drs_recommendations

- changelogs/fragments/2173-fix-existing-disk-recreation-on-vm-with-8-or-more-disks.yml
- plugins/modules/vmware_guest.py
Modifying a vm that has 8 or more disks leads to the last disk erroneously being recreated (which will fail, because it already exists), because vmware_guest uses `disks[disk_index]`  to access the disk config, and `disk_index` skips index 7, while `disks` does NOT skip that index. Therefore the module thinks the disk does not exist, even though it does exist. Having more than 8 disks this will also lead to various disk size issues because it is applying the disk size from the incorrect disk. Fix by keeping the scsi index separate.
vmware_guest
> Fix existing disk erroneously being recreated when dealing with 8 or more disks

- changelogs/fragments/2173-fix-existing-disk-recreation-on-vm-with-8-or-more-disks.yml
- plugins/modules/vmware_guest.py
Fix an issue with VMs that have 8 or more disks attached to a SCSI controller.
vmware_guest
Backport of #2173
cc @Yannik
> stable-4.x: vmware_guest: Fix issue with 8 or more disks

- changelogs/fragments/2173-fix-existing-disk-recreation-on-vm-with-8-or-more-disks.yml
- plugins/modules/vmware_guest.py
Fix an issue with VMs that have 8 or more disks attached to a SCSI controller.
vmware_guest
Backport of #2173
cc @Yannik
> stable-3.x: vmware_guest: Fix issue with 8 or more disks

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2173-fix-existing-disk-recreation-on-vm-with-8-or-more-disks.yml
- changelogs/fragments/2194-vmware_vm_info.yml
- changelogs/fragments/2208-vmware_vmotion.yml
- changelogs/fragments/2217-deprecate-vmware_cluster_dpm.yml
- changelogs/fragments/2218-deprecate-vmware_cluster_drs_recommendations.yml
- galaxy.yml
> prepare 4.8.0 release

- changelogs/fragments/2009-fix-disk-add-failing-with-invalid-configuration-for-device.yml
- plugins/module_utils/vm_device_helper.py
Under some circumstances, disk creation fails with an `invalid configuration for device` error.
Once this error shows up for a VM, it persistently happens whenever trying to add disks, however, I do not know how to make it show up for a VM, sometimes it is just there. 
In comparing the API calls done by VCenter (which works) and ansible (which fails with the error above), I noticed that VCenter sets `fileOperation` to `create`. Setting this in ansible, as done in this patch, fixes the disk creation in ansible.
The [docs](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/dce91b06-cc93-42d6-b277-78fb13a16d6e/7d3494a5-bca7-400f-a18f-f539787ec798/vim.vm.device.VirtualDeviceSpec.html#field_detail) describe the `fileOperation` parameter like this: 
> Type of operation being performed on …
> Fix disk creation resulting in 'invalid configuration for device' error

- changelogs/fragments/2010-fix-vm-hardware-version-upgrade-error-not-being-reported.yml
- plugins/modules/vmware_guest.py
This fixes #2001.
vmware_guest
> Fix errors occuring during hardware version upgrade not being reported (fixes #2001)

- changelogs/fragments/2237-vmware_guest_tools_upgrade.yml
- plugins/modules/vmware_guest_tools_upgrade.py
Fixes #2237
Account for all possible [status](https://dp-downloads.broadcom.com/api-content/apis/API_VWSA_001/8.0U3/html/ReferenceGuides/vim.vm.GuestInfo.ToolsVersionStatus.html):
- guestToolsBlacklisted
- guestToolsCurrent
- guestToolsNeedUpgrade
- guestToolsNotInstalled
- guestToolsSupportedNew
- guestToolsSupportedOld
- guestToolsTooNew
- guestToolsTooOld
- guestToolsUnmanaged
vmware_guest_tools_upgrade
https://forum.ansible.com/t/10684
> vmware_guest_tools_upgrade: All possible tools status

- changelogs/fragments/2000-fix-vmware-guest-idempotency-with-dvswitch.yml
- plugins/modules/vmware_guest.py
- tests/integration/targets/inventory_vmware_host_inventory/playbook/test_options.yml
This fixes the idempotency issue caused by `nic.device.deviceInfo.summary` containing `DVSwitch: d5 6e 22 50 dd f2 94 7b-a6 1f b2 c2 e6 aa 0f` instead of a readable portgroup name.
vmware_guest
Backport of #2000
#498
> stable-4.x: Fix vmware_guest idempotency whith dvswitch

- changelogs/fragments/2241-vmware_guest_info-make-datacenter-property-optional.yaml
- plugins/module_utils/vmware.py
- plugins/modules/vmware_guest_info.py
- tests/integration/targets/vmware_vmotion/tasks/main.yml
We run a big VMware environment featuring multiple vCenters and multiple datacenters within them.
When automating the deployment of VMs at the moment we search for existing machines with the name of the to be deployed machine in order to perform clean-up activities. At the moment we use the guest find module, but it's slow.
Therefore we looked into the guest_info module and found that if the VM is unique, the datacenter property is never actually used as it is only relevant in case multiple VMs have been found.
In case multiple VMs are found, the folder and datacenter attributes are used to decide on "the right one".
Therefore, the datacenter property could as well be an optional parameter on the module and it could simply fail in case there is more than one VM matching and "datacenter" …
> vmware_guest_info - Make "datacenter" property optional

- changelogs/fragments/2220-vmware_guest.yml
- plugins/modules/vmware_guest.py
The `vmware_guest` module did not properly handle setting vApp properties if the `VmConfigSpec` never contained an active `vAppConfig`. This resulted in an exception due to incorrectly trying to access `property` on `None`.
This PR changes the behaviour to default the current list of vApp properties to an empty list if there has never been any `vAppConfig`.
vmware_guest
A simple reproducer would be a to attempt to use `community.vmware.vmware_guest` like this:
```yaml
- name: Configure vApp options
community.vmware.vmware_guest:
state: present
hostname: xxx
username: xxx
password: xxx
name: reproducer-vm
vapp_properties:
- id: name
type: string
label: This is a test
category: Test
become: false
run_once: true
```
Doing so on any VM within …
> vmware_guest: Fix vApp property handling

- plugins/modules/vmware_guest.py
None of `name` or `vlan` is in fact required. For correct operation either one can be specified.
vmware_guest
This cost us about 2 hours of debugging because we thought that vlan is required. When we specified both name and vlan, another network was picked than we specified in name because vlan takes precedence and there was another network available with the same vlan id.
This PR might be worth backporting to all version where this applies.
Relevant code section:
https://github.com/ansible-collections/community.vmware/blob/e249a03c08c30458643e12a7a06c13692bef7a7c/plugins/modules/vmware_guest.py#L1811-L1812
```paste below
```
> Update vmware_guest.py docs

- changelogs/fragments/2216-vmware_dvswitch_pvlans.yml
- plugins/modules/vmware_dvswitch_pvlans.py
This module had a bug that caused an error if the VLAN ID was a string type.
The argument_specs and documentation have been improved to address this issue.
fixes: https://github.com/ansible-collections/community.vmware/issues/2216
* plugins/modules/vmware_dvswitch_pvlans.py
* changelogs/fragments/2216-vmware_dvswitch_pvlans.yml
Tested on VCSA 7.0
> vmware_dvswitch_pvlans: The VLAN ID type has been updated to be handled as an integer

- changelogs/fragments/2277-vmware_guest_network.yml
- plugins/modules/vmware_guest.py
- plugins/modules/vmware_guest_network.py
Speedup vmware_guest_network module. Current design loop though all networks and slow for big infrastructure with many networks (more then 100).
vmware_guest_network.py
In my scenario current module spend 5 min to find network (this function run twice during module work and lead to 10min waiting)
```py
if compute_resource:
for network in compute_resource.network:
if isinstance(network, vim.dvs.DistributedVirtualPortgroup):
dvs = network.config.distributedVirtualSwitch
if (switch_name and dvs.config.name == switch_name) or not switch_name:
if network.config.name == network_name:
return network
if hasattr(network.config.defaultPortConfig.vlan, 'vlanId') and \
network.config.defaultPortConfig.vlan.vlanId == vlan_id:
return network
if …
```
> vmware_guest_network speedup module

- changelogs/fragments/2278-vmware_guest.yml
- plugins/modules/vmware_guest.py
Speedup network search while creating VM using vmware_guest. 
vmware_guest.py
vmware_guest network search is slow. It use find_obj() from vmware.py that loop through all objects trying to find correct. I have a lag for 5 mins trying. PyVmomi.network_exists_by_name works much faster.
> vmware_guest speedup module

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/2216-vmware_dvswitch_pvlans.yml
- changelogs/fragments/2220-vmware_guest.yml
- changelogs/fragments/2260-deprecate-vmware_cluster_info.yml
- changelogs/fragments/2275-vm-ou-customization.yml
- changelogs/fragments/2277-vmware_guest_network.yml
- changelogs/fragments/2278-vmware_guest.yml
- galaxy.yml
> prepare 5.3.0 release

- plugins/modules/vmware_vmkernel.py
Improving the documentation a bit:
1. The options dealing with IP stuff is about **IPv4**.
2. `ip_address` and `subnet_mask` aren't required if [state is absent](https://github.com/ansible-collections/community.vmware/blob/af13893a84614665f6a0b700a468f9b05948c539/plugins/modules/vmware_vmkernel.py#L327-L333).
vmware_vmkernel
#1740
#2295
> vmware_vmkernel: Improve documentation

- changelogs/fragments/2304-deprecate-plugin_utils.yml
Deeprecate the inventory plugins (#2283) means we can also get rid of `ansible_collections.community.vmware.plugins.plugin_utils.inventory` / `plugins/plugin_utils/inventory.py`.
plugin_utils/inventory.py
#2283
> Deprecate plugin_utils.inventory

- changelogs/fragments/2303-deprecate-host_version_at_least.yml
There's a method `host_version_at_least`:
https://github.com/ansible-collections/community.vmware/blob/1fe4061bb83751d6221dd3dd3f37ae420da835cf/plugins/module_utils/vmware.py#L1453-L1473
It looks like the only place this is used is here:
https://github.com/ansible-collections/community.vmware/blob/1fe4061bb83751d6221dd3dd3f37ae420da835cf/plugins/modules/vmware_export_ovf.py#L247-L249
Since 6.7.0 is already EOL, I think we don't need this anymore and can remove it. But I think we should deprecate this first, just in case that someone uses this from the `vmware` module util.
vmware
> Deprecate host_version_at_least

- changelogs/fragments/2306-deprecate-plugins.httpapi.yml
I think this isn't used anywhere in the collection. So let's deprecate and finally remove it.
plugins/httpapi/
#2305
> Deprecate plugins.httpapi

- changelogs/fragments/2311-deprecate-unsed-methods-and-functions.yml
It looks like this stuff is defined bot not used anywhere:
```shell
~/github/community.vmware$ egrep -r '(is_nvdimm_controller|is_nvdimm_device|find_host_portgroup_by_name|find_host_portgroup_by_name|network_exists_by_name|vmdk_disk_path_split|find_vmdk_file|get_folder_by_name)' plugins/
plugins/module_utils/vmware_rest_client.py:    def get_folder_by_name(self, datacenter_name, folder_name):
plugins/module_utils/vm_device_helper.py:    def is_nvdimm_controller(device):
plugins/module_utils/vm_device_helper.py:    def is_nvdimm_device(device):
plugins/module_utils/vmware.py:def find_host_portgroup_by_name(host, portgroup_name):
plugins/module_utils/vmware.py:    def find_host_portgroup_by_name(host, portgroup_name):
plugins/module_utils/vmware.py:    def network_exists_by_name(self, …
```
> Deprecate unused methods / functions

- changelogs/fragments/2324-vmware_migrate_vmk.yml
- plugins/modules/vmware_migrate_vmk.py
It feels wrong that this module uses `vmware.connect_to_api` directly. I think it would be better to inherit from / sub-class `PyVmomi`
#2318
> vmware_migrate_vmk: Inherit from PyVmomi

- changelogs/fragments/2326-drop-test-lt7.yml
- plugins/modules/vmware_category.py
- plugins/modules/vmware_vc_infraprofile_info.py
vSphere versions < 7 have been EOL for some time (1 1/2 years?), so I guess we don't have to test for < 7 anymore.
vmware_vc_infraprofile_info
> Don't test for vSphere < 7 anymore

- changelogs/fragments/2327-drop-HAS_PYVMOMI.yml
- plugins/modules/vcenter_standard_key_provider.py
- plugins/modules/vmware_guest.py
- plugins/modules/vmware_guest_tpm.py
- plugins/modules/vmware_vm_config_option.py
- plugins/modules/vmware_vsan_health_info.py
These modules define `HAS_PYVMOMI`, but it doesn't look like they use it anywhere.
vmware_guest
vmware_guest_tpm
> Drop unused HAS_PYVMOMI

- changelogs/fragments/2340-deprecate-vcenter_folder.yml
- meta/runtime.yml
- plugins/modules/vcenter_folder.py
- tests/integration/targets/prepare_vmware_tests/tasks/setup_datacenter.yml
- tests/integration/targets/vmware_datastore_cluster/tasks/main.yml
- tests/integration/targets/vmware_dvswitch/tasks/main.yml
- tests/integration/targets/vmware_folder_info/tasks/main.yml
- tests/integration/targets/vmware_guest_move/tasks/main.yml
Deprecate `community.vmware.vcenter_folder` in favor of `vmware.folder`.
vcenter_folder
ansible-collections/vmware.vmware#104
> Deprecate vcenter_folder

- changelogs/fragments/2345-deprecate.vmware_content_library_manager.yml
- meta/runtime.yml
- plugins/modules/vmware_content_library_manager.py
- tests/integration/targets/prepare_vmware_tests/tasks/setup_content_library.yml
Deprecate `community.vmware.vmware_content_library_manager` in favor of `vmware.vmware.local_content_library` and `vmware.vmware.subscribed_content_library`.
ansible-collections/vmware.vmware#109
> Deprecate vmware_content_library_manager

- tests/galaxy-importer.cfg
Disable the ansible-doc part of the galaxy-importer run in Zuul jobs / tests.
- CI Pull Request
CI
I hope this stops the CI from failing when using doc fragments from another collection (like in #2369).
> Zuul: disable ansible-doc part of galaxy-importer

- tests/integration/targets/vmware_cluster_dpm/aliases
- tests/integration/targets/vmware_cluster_dpm/tasks/main.yml
- tests/integration/targets/vmware_cluster_ha/aliases
- tests/integration/targets/vmware_cluster_ha/tasks/main.yml
- tests/integration/targets/vmware_cluster_info/aliases
- tests/integration/targets/vmware_cluster_info/tasks/main.yml
- tests/integration/targets/vmware_content_deploy_template/aliases
- tests/integration/targets/vmware_content_deploy_template/tasks/main.yml
- tests/integration/targets/vmware_host/aliases
- tests/integration/targets/vmware_host/tasks/main.yml
- tests/integration/targets/vmware_maintenancemode/aliases
- tests/integration/targets/vmware_maintenancemode/tasks/main.yml
I think it's been a bad idea to remove the integration tests just because the modules have been deprecated. Let's keep them while the modules itself are still there.
vmware_cluster_dpm #2217
vmware_cluster_ha #2321
vmware_cluster_info #2260
vmware_content_deploy_ovf_template #2332
vmware_host #2337
vmware_maintenancemode #2293
Re-adding the tests for the inventory plugins (#2283) will be done in #2372.
I didn't remove any integration tests for
- vcenter_folder (#2340)
- vmware_cluster (#2143)
- vmware_cluster_drs (#2136)
- vmware_cluster_drs_recommendations (#2218)
- vmware_cluster_vcls (#2156)
- vmware_content_library_manager (#2345).
> Re-add integration tests for deprecated modules

- changelogs/fragments/2374-vmware_object_role_permission.yml
- plugins/modules/vmware_object_role_permission.py
This is a follow-up to #2348 to document how to set permissions on the vCenter level.
> vmware_object_role_permission: Document vCenter level permissions

- galaxy.yml
Allow `vmware.vmware` >= 2.0.0 (but still restrict to < 3.0.0).
galaxy.yml
> Update vmware.vmware dependency

- changelogs/fragments/2398-deprecate-vmware_guest_powerstate.yml
- meta/runtime.yml
- plugins/modules/vmware_guest_powerstate.py
- tests/integration/targets/vmware_guest_disk_info/tasks/main.yml
- tests/integration/targets/vmware_guest_instant_clone/tasks/main.yml
- tests/integration/targets/vmware_guest_register_operation/tasks/main.yml
- tests/integration/targets/vmware_guest_sendkey/tasks/main.yml
Deprecate `community.vmware.vmware_guest_powerstate` in favor of `vmware.vmware.vm_powerstate`.
vmware_guest_powerstate
ansible-collections/vmware.vmware#114
> Deprecate vmware_guest_powerstate

- README.md
- changelogs/fragments/2415-restrict-pyvmomi.yml
- requirements.txt
- tests/unit/requirements.txt
There are some breaking changes in [pyvmomi 9.0](https://github.com/vmware/pyvmomi/releases/tag/v9.0.0.0). I don't think we should try to fix this in 4.x, but restrict support for pyvmomi.
Especially since 4.x will be EOL in a few months. I doesn't make sense to me to use an old version of this collection with the latest pyvmomi.
#2413
#2414
> stable-4.x: Restrict pyvmomi to < 9

- changelogs/fragments/fix-webhandle-range-check.yaml
- plugins/modules/vmware_deploy_ovf.py
Some HTTP/2 servers, such as Sonatype Nexus, do not send the `accept-ranges` header,
even though they support ranged downloads. This causes `vmware_deploy_ovf.py` to fail
with "Site does not accept ranges", despite the server correctly supporting range requests.
This patch changes the logic to verify range support by sending a `Range: bytes=0-0` header
and checking if the response status is `206 Partial Content`, which is the actual indicator
of support.
This makes the module compatible with modern HTTP/2 servers such as Nexus and S3.
This change is also fully compatible with HTTP/1.1 servers, which respond identically to Range headers.
Thus, the new logic is both more accurate and backward-compatible.
Fixes: None directly, but observed with Nexus 3.x.
> Fix WebHandle to detect range support without relying on 'accept-ranges' header

- extensions/audit/README.md
- extensions/audit/event_query.yml
Adds a query file for the vmware_guest module. This file is only used by AAP to collect metadata about a modules usage. It has no impact on other use cases or modules.
vmware_guest
Sorry if this is a bit cryptic, I really dont have a ton more info but am happy to answer any other questions or concerns about the file
> add event query file for vmware_guest

- changelogs/fragments/2451-vcenter_license_vcf_support.yml
- plugins/modules/vcenter_license.py
Currently, the `vcenter_license` module does not support assigning vSphere VCF keys to vCenter servers. The vSphere 8 VCF keys include support vCenter Server 8.0U2 and above (https://knowledge.broadcom.com/external/article/319282/vmware-cloud-foundation-and-vsphere-foun.html)
This PR adds support for an array lookup to aid in future instances like this.
`vcenter_license`
MInimal reproduction;
~~~ yaml
- name: License vCenter
community.vmware.vcenter_license:
license: "{{ vmware_license_key }}"
state: present
~~~
Currently results in:
~~~ shell
ok: [localhost] => {
"changed": false,
"diff": {},
"cluster_name": …
> Add support for VCF license keys

- .github/workflows/extra-docs-linting.yml
- changelogs/fragments/2467-deprecate-vmware_guest_snapshot.yml
- meta/runtime.yml
- plugins/modules/vmware_guest_snapshot.py
- tests/integration/targets/vmware_guest_info/tasks/main.yml
Deprecate `community.vmware.vmware_guest_snapshot` in favor of `vmware.vmware.vm_snapshot`.
vmware_guest_snapshot
ansible-collections/vmware.vmware#126
> Deprecate vmware_guest_snapshot

- tests/sanity/ignore-2.17.txt
- tests/sanity/ignore-2.18.txt
Since we don't support Ansible-core < 2.19.0 in 6.x, we don't need those ignores anymore.
tests/sanity/ignore-2.17.txt
tests/sanity/ignore-2.18.txt
> Remove unnecessary sanity test ignores
